#include <vector>
#include <map>
#include <set>
#include "cfg.hpp"
using namespace std; 
set<Symbol> terminalSymbols = {"#", "TK_ASSIGN", "TK_DIV", "TK_EOI", "TK_EQU", "TK_GT", "TK_ID", "TK_LPAREN", "TK_LT", "TK_MINUS", "TK_MUL", "TK_NEQ", "TK_NUM", "TK_PLUS", "TK_RPAREN"};
set<Symbol> nonTerminalSymbols = {"#", "assign-expr", "assign-exprT", "compare-expr", "compare-exprT", "expr", "exprT", "factor", "primary", "prog", "rel-expr", "rel-exprT", "stmt", "term", "termT"};
typedef map<Symbol, map<Symbol, Production>> ParseTable;
ParseTable parseTable;
void initParseTable() {
	 parseTable["assign-expr"]["TK_ID"] = Production(11,"assign-expr", SymbolString({"rel-expr","assign-exprT"}));
	 parseTable["assign-expr"]["TK_LPAREN"] = Production(11,"assign-expr", SymbolString({"rel-expr","assign-exprT"}));
	 parseTable["assign-expr"]["TK_MINUS"] = Production(11,"assign-expr", SymbolString({"rel-expr","assign-exprT"}));
	 parseTable["assign-expr"]["TK_NUM"] = Production(11,"assign-expr", SymbolString({"rel-expr","assign-exprT"}));
	 parseTable["assign-exprT"]["TK_ASSIGN"] = Production(14,"assign-exprT", SymbolString({"#"}));
	 parseTable["assign-exprT"]["TK_EOI"] = Production(14,"assign-exprT", SymbolString({"#"}));
	 parseTable["assign-exprT"]["TK_EQU"] = Production(14,"assign-exprT", SymbolString({"#"}));
	 parseTable["assign-exprT"]["TK_GT"] = Production(13,"assign-exprT", SymbolString({"TK_GT","rel-expr","@@","assign-exprT"}));
	 parseTable["assign-exprT"]["TK_LT"] = Production(12,"assign-exprT", SymbolString({"TK_LT","rel-expr","@@","assign-exprT"}));
	 parseTable["assign-exprT"]["TK_NEQ"] = Production(14,"assign-exprT", SymbolString({"#"}));
	 parseTable["assign-exprT"]["TK_RPAREN"] = Production(14,"assign-exprT", SymbolString({"#"}));
	 parseTable["compare-expr"]["TK_ID"] = Production(7,"compare-expr", SymbolString({"assign-expr","compare-exprT"}));
	 parseTable["compare-expr"]["TK_LPAREN"] = Production(7,"compare-expr", SymbolString({"assign-expr","compare-exprT"}));
	 parseTable["compare-expr"]["TK_MINUS"] = Production(7,"compare-expr", SymbolString({"assign-expr","compare-exprT"}));
	 parseTable["compare-expr"]["TK_NUM"] = Production(7,"compare-expr", SymbolString({"assign-expr","compare-exprT"}));
	 parseTable["compare-exprT"]["TK_ASSIGN"] = Production(10,"compare-exprT", SymbolString({"#"}));
	 parseTable["compare-exprT"]["TK_EOI"] = Production(10,"compare-exprT", SymbolString({"#"}));
	 parseTable["compare-exprT"]["TK_EQU"] = Production(8,"compare-exprT", SymbolString({"TK_EQU","assign-expr","@@","compare-exprT"}));
	 parseTable["compare-exprT"]["TK_NEQ"] = Production(9,"compare-exprT", SymbolString({"TK_NEQ","assign-expr","@@","compare-exprT"}));
	 parseTable["compare-exprT"]["TK_RPAREN"] = Production(10,"compare-exprT", SymbolString({"#"}));
	 parseTable["expr"]["TK_ID"] = Production(4,"expr", SymbolString({"compare-expr","exprT"}));
	 parseTable["expr"]["TK_LPAREN"] = Production(4,"expr", SymbolString({"compare-expr","exprT"}));
	 parseTable["expr"]["TK_MINUS"] = Production(4,"expr", SymbolString({"compare-expr","exprT"}));
	 parseTable["expr"]["TK_NUM"] = Production(4,"expr", SymbolString({"compare-expr","exprT"}));
	 parseTable["exprT"]["TK_ASSIGN"] = Production(5,"exprT", SymbolString({"TK_ASSIGN","compare-expr","@@","exprT"}));
	 parseTable["exprT"]["TK_EOI"] = Production(6,"exprT", SymbolString({"#"}));
	 parseTable["exprT"]["TK_RPAREN"] = Production(6,"exprT", SymbolString({"#"}));
	 parseTable["factor"]["TK_ID"] = Production(24,"factor", SymbolString({"primary"}));
	 parseTable["factor"]["TK_LPAREN"] = Production(24,"factor", SymbolString({"primary"}));
	 parseTable["factor"]["TK_MINUS"] = Production(23,"factor", SymbolString({"TK_MINUS","factor","@@"}));
	 parseTable["factor"]["TK_NUM"] = Production(24,"factor", SymbolString({"primary"}));
	 parseTable["primary"]["TK_ID"] = Production(25,"primary", SymbolString({"TK_ID"}));
	 parseTable["primary"]["TK_LPAREN"] = Production(27,"primary", SymbolString({"TK_LPAREN","expr","TK_RPAREN"}));
	 parseTable["primary"]["TK_NUM"] = Production(26,"primary", SymbolString({"TK_NUM"}));
	 parseTable["prog"]["TK_EOI"] = Production(2,"prog", SymbolString({"#"}));
	 parseTable["prog"]["TK_ID"] = Production(1,"prog", SymbolString({"stmt"}));
	 parseTable["prog"]["TK_LPAREN"] = Production(1,"prog", SymbolString({"stmt"}));
	 parseTable["prog"]["TK_MINUS"] = Production(1,"prog", SymbolString({"stmt"}));
	 parseTable["prog"]["TK_NUM"] = Production(1,"prog", SymbolString({"stmt"}));
	 parseTable["rel-expr"]["TK_ID"] = Production(15,"rel-expr", SymbolString({"term","rel-exprT"}));
	 parseTable["rel-expr"]["TK_LPAREN"] = Production(15,"rel-expr", SymbolString({"term","rel-exprT"}));
	 parseTable["rel-expr"]["TK_MINUS"] = Production(15,"rel-expr", SymbolString({"term","rel-exprT"}));
	 parseTable["rel-expr"]["TK_NUM"] = Production(15,"rel-expr", SymbolString({"term","rel-exprT"}));
	 parseTable["rel-exprT"]["TK_ASSIGN"] = Production(18,"rel-exprT", SymbolString({"#"}));
	 parseTable["rel-exprT"]["TK_EOI"] = Production(18,"rel-exprT", SymbolString({"#"}));
	 parseTable["rel-exprT"]["TK_EQU"] = Production(18,"rel-exprT", SymbolString({"#"}));
	 parseTable["rel-exprT"]["TK_GT"] = Production(18,"rel-exprT", SymbolString({"#"}));
	 parseTable["rel-exprT"]["TK_LT"] = Production(18,"rel-exprT", SymbolString({"#"}));
	 parseTable["rel-exprT"]["TK_MINUS"] = Production(17,"rel-exprT", SymbolString({"TK_MINUS","term","@@","rel-exprT"}));
	 parseTable["rel-exprT"]["TK_NEQ"] = Production(18,"rel-exprT", SymbolString({"#"}));
	 parseTable["rel-exprT"]["TK_PLUS"] = Production(16,"rel-exprT", SymbolString({"TK_PLUS","term","@@","rel-exprT"}));
	 parseTable["rel-exprT"]["TK_RPAREN"] = Production(18,"rel-exprT", SymbolString({"#"}));
	 parseTable["stmt"]["TK_ID"] = Production(3,"stmt", SymbolString({"expr"}));
	 parseTable["stmt"]["TK_LPAREN"] = Production(3,"stmt", SymbolString({"expr"}));
	 parseTable["stmt"]["TK_MINUS"] = Production(3,"stmt", SymbolString({"expr"}));
	 parseTable["stmt"]["TK_NUM"] = Production(3,"stmt", SymbolString({"expr"}));
	 parseTable["term"]["TK_ID"] = Production(19,"term", SymbolString({"factor","termT"}));
	 parseTable["term"]["TK_LPAREN"] = Production(19,"term", SymbolString({"factor","termT"}));
	 parseTable["term"]["TK_MINUS"] = Production(19,"term", SymbolString({"factor","termT"}));
	 parseTable["term"]["TK_NUM"] = Production(19,"term", SymbolString({"factor","termT"}));
	 parseTable["termT"]["TK_ASSIGN"] = Production(22,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_DIV"] = Production(21,"termT", SymbolString({"TK_DIV","factor","@@","termT"}));
	 parseTable["termT"]["TK_EOI"] = Production(22,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_EQU"] = Production(22,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_GT"] = Production(22,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_LT"] = Production(22,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_MINUS"] = Production(22,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_MUL"] = Production(20,"termT", SymbolString({"TK_MUL","factor","@@","termT"}));
	 parseTable["termT"]["TK_NEQ"] = Production(22,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_PLUS"] = Production(22,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_RPAREN"] = Production(22,"termT", SymbolString({"#"}));
}
