#include <vector>
#include <map>
#include <set>
#include "cfg.hpp"
using namespace std; 
set<Symbol> terminalSymbols = {"#", "TK_ASSIGN", "TK_DIV", "TK_EOI", "TK_EQU", "TK_GT", "TK_ID", "TK_LPAREN", "TK_LT", "TK_MINUS", "TK_MUL", "TK_NEQ", "TK_NUM", "TK_PLUS", "TK_RPAREN"};
set<Symbol> nonTerminalSymbols = {"#", "assign-expr", "assign-exprT", "compare-expr", "compare-exprT", "expr", "exprT", "factor", "factorT", "primary", "prog", "rel-expr", "rel-exprT", "stmt", "term", "termT", "unary"};
typedef map<Symbol, map<Symbol, Production>> ParseTable;
ParseTable parseTable;
void initParseTable() {
	 parseTable["assign-expr"]["TK_ID"] = Production(6,"assign-expr", SymbolString({"compare-expr","assign-exprT"}));
	 parseTable["assign-expr"]["TK_LPAREN"] = Production(6,"assign-expr", SymbolString({"compare-expr","assign-exprT"}));
	 parseTable["assign-expr"]["TK_MINUS"] = Production(6,"assign-expr", SymbolString({"compare-expr","assign-exprT"}));
	 parseTable["assign-expr"]["TK_NUM"] = Production(6,"assign-expr", SymbolString({"compare-expr","assign-exprT"}));
	 parseTable["assign-exprT"]["TK_ASSIGN"] = Production(7,"assign-exprT", SymbolString({"TK_ASSIGN","compare-expr","@@","assign-exprT"}));
	 parseTable["assign-exprT"]["TK_EOI"] = Production(8,"assign-exprT", SymbolString({"#"}));
	 parseTable["assign-exprT"]["TK_RPAREN"] = Production(8,"assign-exprT", SymbolString({"#"}));
	 parseTable["compare-expr"]["TK_ID"] = Production(9,"compare-expr", SymbolString({"rel-expr","compare-exprT"}));
	 parseTable["compare-expr"]["TK_LPAREN"] = Production(9,"compare-expr", SymbolString({"rel-expr","compare-exprT"}));
	 parseTable["compare-expr"]["TK_MINUS"] = Production(9,"compare-expr", SymbolString({"rel-expr","compare-exprT"}));
	 parseTable["compare-expr"]["TK_NUM"] = Production(9,"compare-expr", SymbolString({"rel-expr","compare-exprT"}));
	 parseTable["compare-exprT"]["TK_ASSIGN"] = Production(12,"compare-exprT", SymbolString({"#"}));
	 parseTable["compare-exprT"]["TK_EOI"] = Production(12,"compare-exprT", SymbolString({"#"}));
	 parseTable["compare-exprT"]["TK_EQU"] = Production(10,"compare-exprT", SymbolString({"TK_EQU","rel-expr","@@","compare-exprT"}));
	 parseTable["compare-exprT"]["TK_NEQ"] = Production(11,"compare-exprT", SymbolString({"TK_NEQ","rel-expr","@@","compare-exprT"}));
	 parseTable["compare-exprT"]["TK_RPAREN"] = Production(12,"compare-exprT", SymbolString({"#"}));
	 parseTable["expr"]["TK_ID"] = Production(4,"expr", SymbolString({"assign-expr","exprT"}));
	 parseTable["expr"]["TK_LPAREN"] = Production(4,"expr", SymbolString({"assign-expr","exprT"}));
	 parseTable["expr"]["TK_MINUS"] = Production(4,"expr", SymbolString({"assign-expr","exprT"}));
	 parseTable["expr"]["TK_NUM"] = Production(4,"expr", SymbolString({"assign-expr","exprT"}));
	 parseTable["exprT"]["TK_EOI"] = Production(5,"exprT", SymbolString({"#"}));
	 parseTable["exprT"]["TK_RPAREN"] = Production(5,"exprT", SymbolString({"#"}));
	 parseTable["factor"]["TK_ID"] = Production(21,"factor", SymbolString({"unary","factorT"}));
	 parseTable["factor"]["TK_LPAREN"] = Production(21,"factor", SymbolString({"unary","factorT"}));
	 parseTable["factor"]["TK_MINUS"] = Production(21,"factor", SymbolString({"unary","factorT"}));
	 parseTable["factor"]["TK_NUM"] = Production(21,"factor", SymbolString({"unary","factorT"}));
	 parseTable["factorT"]["TK_ASSIGN"] = Production(24,"factorT", SymbolString({"#"}));
	 parseTable["factorT"]["TK_DIV"] = Production(23,"factorT", SymbolString({"TK_DIV","unary","@@","factorT"}));
	 parseTable["factorT"]["TK_EOI"] = Production(24,"factorT", SymbolString({"#"}));
	 parseTable["factorT"]["TK_EQU"] = Production(24,"factorT", SymbolString({"#"}));
	 parseTable["factorT"]["TK_GT"] = Production(24,"factorT", SymbolString({"#"}));
	 parseTable["factorT"]["TK_LT"] = Production(24,"factorT", SymbolString({"#"}));
	 parseTable["factorT"]["TK_MINUS"] = Production(24,"factorT", SymbolString({"#"}));
	 parseTable["factorT"]["TK_MUL"] = Production(22,"factorT", SymbolString({"TK_MUL","unary","@@","factorT"}));
	 parseTable["factorT"]["TK_NEQ"] = Production(24,"factorT", SymbolString({"#"}));
	 parseTable["factorT"]["TK_PLUS"] = Production(24,"factorT", SymbolString({"#"}));
	 parseTable["factorT"]["TK_RPAREN"] = Production(24,"factorT", SymbolString({"#"}));
	 parseTable["primary"]["TK_ID"] = Production(27,"primary", SymbolString({"TK_ID","@@"}));
	 parseTable["primary"]["TK_LPAREN"] = Production(29,"primary", SymbolString({"TK_LPAREN","expr","TK_RPAREN","@@"}));
	 parseTable["primary"]["TK_NUM"] = Production(28,"primary", SymbolString({"TK_NUM","@@"}));
	 parseTable["prog"]["TK_EOI"] = Production(2,"prog", SymbolString({"#"}));
	 parseTable["prog"]["TK_ID"] = Production(1,"prog", SymbolString({"stmt"}));
	 parseTable["prog"]["TK_LPAREN"] = Production(1,"prog", SymbolString({"stmt"}));
	 parseTable["prog"]["TK_MINUS"] = Production(1,"prog", SymbolString({"stmt"}));
	 parseTable["prog"]["TK_NUM"] = Production(1,"prog", SymbolString({"stmt"}));
	 parseTable["rel-expr"]["TK_ID"] = Production(13,"rel-expr", SymbolString({"term","rel-exprT"}));
	 parseTable["rel-expr"]["TK_LPAREN"] = Production(13,"rel-expr", SymbolString({"term","rel-exprT"}));
	 parseTable["rel-expr"]["TK_MINUS"] = Production(13,"rel-expr", SymbolString({"term","rel-exprT"}));
	 parseTable["rel-expr"]["TK_NUM"] = Production(13,"rel-expr", SymbolString({"term","rel-exprT"}));
	 parseTable["rel-exprT"]["TK_ASSIGN"] = Production(16,"rel-exprT", SymbolString({"#"}));
	 parseTable["rel-exprT"]["TK_EOI"] = Production(16,"rel-exprT", SymbolString({"#"}));
	 parseTable["rel-exprT"]["TK_EQU"] = Production(16,"rel-exprT", SymbolString({"#"}));
	 parseTable["rel-exprT"]["TK_GT"] = Production(15,"rel-exprT", SymbolString({"TK_GT","term","@@","rel-exprT"}));
	 parseTable["rel-exprT"]["TK_LT"] = Production(14,"rel-exprT", SymbolString({"TK_LT","term","@@","rel-exprT"}));
	 parseTable["rel-exprT"]["TK_NEQ"] = Production(16,"rel-exprT", SymbolString({"#"}));
	 parseTable["rel-exprT"]["TK_RPAREN"] = Production(16,"rel-exprT", SymbolString({"#"}));
	 parseTable["stmt"]["TK_ID"] = Production(3,"stmt", SymbolString({"expr"}));
	 parseTable["stmt"]["TK_LPAREN"] = Production(3,"stmt", SymbolString({"expr"}));
	 parseTable["stmt"]["TK_MINUS"] = Production(3,"stmt", SymbolString({"expr"}));
	 parseTable["stmt"]["TK_NUM"] = Production(3,"stmt", SymbolString({"expr"}));
	 parseTable["term"]["TK_ID"] = Production(17,"term", SymbolString({"factor","termT"}));
	 parseTable["term"]["TK_LPAREN"] = Production(17,"term", SymbolString({"factor","termT"}));
	 parseTable["term"]["TK_MINUS"] = Production(17,"term", SymbolString({"factor","termT"}));
	 parseTable["term"]["TK_NUM"] = Production(17,"term", SymbolString({"factor","termT"}));
	 parseTable["termT"]["TK_ASSIGN"] = Production(20,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_EOI"] = Production(20,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_EQU"] = Production(20,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_GT"] = Production(20,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_LT"] = Production(20,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_MINUS"] = Production(19,"termT", SymbolString({"TK_MINUS","factor","@@","termT"}));
	 parseTable["termT"]["TK_NEQ"] = Production(20,"termT", SymbolString({"#"}));
	 parseTable["termT"]["TK_PLUS"] = Production(18,"termT", SymbolString({"TK_PLUS","factor","@@","termT"}));
	 parseTable["termT"]["TK_RPAREN"] = Production(20,"termT", SymbolString({"#"}));
	 parseTable["unary"]["TK_ID"] = Production(26,"unary", SymbolString({"primary"}));
	 parseTable["unary"]["TK_LPAREN"] = Production(26,"unary", SymbolString({"primary"}));
	 parseTable["unary"]["TK_MINUS"] = Production(25,"unary", SymbolString({"TK_MINUS","unary","@@"}));
	 parseTable["unary"]["TK_NUM"] = Production(26,"unary", SymbolString({"primary"}));
}
