#ifndef matrix_h
#define matrix_h

/* Generated by mgclex, the simplest lexer-generator in the northeast */

enum TKSymbol {
TK_NUM,
TK_PLUS,TK_MINUS,TK_MUL,TK_DIV,TK_MOD,
TK_LPAREN,TK_RPAREN,TK_LT,TK_GT,TK_ASSIGN,
TK_ID, TK_EOI
};
static const char* tokenStr[] = {
"TK_NUM",
"TK_PLUS","TK_MINUS","TK_MUL","TK_DIV","TK_MOD",
"TK_LPAREN","TK_RPAREN","TK_LT","TK_GT","TK_ASSIGN",
"TK_ID", "TK_EOI"
};
static const int mgc_lexer_matrix_row1[] = { 73,  37,7,  40,8,  41,9,  42,4,  43,3,  45,5,  47,6,  48,2,  49,2,  50,2,  51,2,  52,2,  53,2,  54,2,  55,2,  56,2,  57,2,  58,12,  60,10,  62,11,  65,13,  66,13,  67,13,  68,13,  69,13,  70,13,  71,13,  72,13,  73,13,  74,13,  75,13,  76,13,  77,13,  78,13,  79,13,  80,13,  81,13,  82,13,  83,13,  84,13,  85,13,  86,13,  87,13,  88,13,  89,13,  90,13,  97,13,  98,13,  99,13,  100,13,  101,13,  102,13,  103,13,  104,13,  105,13,  106,13,  107,13,  108,13,  109,13,  110,13,  111,13,  112,13,  113,13,  114,13,  115,13,  116,13,  117,13,  118,13,  119,13,  120,13,  121,13,  122,13,  124,2, 0};
static const int mgc_lexer_matrix_row2[] = { 12,  46,15,  48,14,  49,14,  50,14,  51,14,  52,14,  53,14,  54,14,  55,14,  56,14,  57,14,  124,14, 0};
static const int mgc_lexer_matrix_row12[] = { 1,  61,16, 0};
static const int mgc_lexer_matrix_row13[] = { 52,  65,17,  66,17,  67,17,  68,17,  69,17,  70,17,  71,17,  72,17,  73,17,  74,17,  75,17,  76,17,  77,17,  78,17,  79,17,  80,17,  81,17,  82,17,  83,17,  84,17,  85,17,  86,17,  87,17,  88,17,  89,17,  90,17,  97,17,  98,17,  99,17,  100,17,  101,17,  102,17,  103,17,  104,17,  105,17,  106,17,  107,17,  108,17,  109,17,  110,17,  111,17,  112,17,  113,17,  114,17,  115,17,  116,17,  117,17,  118,17,  119,17,  120,17,  121,17,  122,17, 0};
static const int mgc_lexer_matrix_row14[] = { 12,  46,15,  48,14,  49,14,  50,14,  51,14,  52,14,  53,14,  54,14,  55,14,  56,14,  57,14,  124,14, 0};
static const int mgc_lexer_matrix_row15[] = { 11,  48,18,  49,18,  50,18,  51,18,  52,18,  53,18,  54,18,  55,18,  56,18,  57,18,  124,18, 0};
static const int mgc_lexer_matrix_row17[] = { 53,  45,17,  65,17,  66,17,  67,17,  68,17,  69,17,  70,17,  71,17,  72,17,  73,17,  74,17,  75,17,  76,17,  77,17,  78,17,  79,17,  80,17,  81,17,  82,17,  83,17,  84,17,  85,17,  86,17,  87,17,  88,17,  89,17,  90,17,  97,17,  98,17,  99,17,  100,17,  101,17,  102,17,  103,17,  104,17,  105,17,  106,17,  107,17,  108,17,  109,17,  110,17,  111,17,  112,17,  113,17,  114,17,  115,17,  116,17,  117,17,  118,17,  119,17,  120,17,  121,17,  122,17, 0};
static const int mgc_lexer_matrix_row18[] = { 12,  46,15,  48,18,  49,18,  50,18,  51,18,  52,18,  53,18,  54,18,  55,18,  56,18,  57,18,  124,18, 0};
static const int *mgc_lexer_matrix[] = {
NULL,
mgc_lexer_matrix_row1,
mgc_lexer_matrix_row2,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
mgc_lexer_matrix_row12,
mgc_lexer_matrix_row13,
mgc_lexer_matrix_row14,
mgc_lexer_matrix_row15,
NULL,
mgc_lexer_matrix_row17,
mgc_lexer_matrix_row18
};

static const int mgc_lex_accept[19] = {
	-1,
	-1,
	0,
	1,
	3,
	2,
	4,
	5,
	6,
	7,
	8,
	9,
	-1,
	11,
	0,
	-1,
	10,
	11,
	0
};

#endif