goTab[0] = {{"AEXPR", "14"}, {"BLOCKSTMT", "26"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"DEFSTMT", "24"}, {"EXPR", "7"}, {"EXPSTMT", "29"}, {"FACT", "18"}, {"IFSTMT", "28"}, {"LETSTMT", "23"}, {"LISTCON", "15"}, {"PRI", "16"}, {"PRINTSTMT", "25"}, {"PROG", "31"}, {"RELEXPR", "30"}, {"RETSTMT", "13"}, {"STMT", "27"}, {"STMTLIST", "19"}, {"STRUCTSTMT", "22"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[3] = {{"AEXPR", "39"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"EXPR", "7"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"RELEXPR", "30"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[6] = {{"AEXPR", "43"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"EXPR", "7"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"RELEXPR", "30"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[8] = {{"CALLEXPR", "12"}, {"LISTCON", "15"}, {"PRI", "46"}, {"SUBSCRIPT", "20"}}
goTab[9] = {{"AEXPR", "48"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"EXPLIST", "47"}, {"EXPR", "7"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"RELEXPR", "30"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[21] = {{"AEXPR", "51"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"EXPR", "7"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"RELEXPR", "30"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[27] = {{"AEXPR", "14"}, {"BLOCKSTMT", "26"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"DEFSTMT", "24"}, {"EXPR", "7"}, {"EXPSTMT", "29"}, {"FACT", "18"}, {"IFSTMT", "28"}, {"LETSTMT", "23"}, {"LISTCON", "15"}, {"PRI", "16"}, {"PRINTSTMT", "25"}, {"RELEXPR", "30"}, {"RETSTMT", "13"}, {"STMT", "27"}, {"STMTLIST", "52"}, {"STRUCTSTMT", "22"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[32] = {{"AEXPR", "14"}, {"BLOCKSTMT", "26"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"DEFSTMT", "24"}, {"EXPR", "7"}, {"EXPSTMT", "29"}, {"FACT", "18"}, {"IFSTMT", "28"}, {"LETSTMT", "23"}, {"LISTCON", "15"}, {"PRI", "16"}, {"PRINTSTMT", "25"}, {"RELEXPR", "30"}, {"RETSTMT", "13"}, {"STMT", "27"}, {"STMTLIST", "55"}, {"STRUCTSTMT", "22"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[34] = {{"AEXPR", "58"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"EXPR", "7"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"RELEXPR", "30"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[35] = {{"AEXPR", "59"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"EXPR", "7"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"RELEXPR", "30"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[36] = {{"CALLEXPR", "12"}, {"EXPR", "7"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"RELEXPR", "60"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[37] = {{"CALLEXPR", "12"}, {"EXPR", "7"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"RELEXPR", "61"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[38] = {{"BLOCKSTMT", "62"}}
goTab[41] = {{"CALLEXPR", "12"}, {"FACT", "65"}, {"LISTCON", "15"}, {"PRI", "16"}, {"SUBSCRIPT", "20"}}
goTab[42] = {{"CALLEXPR", "12"}, {"FACT", "66"}, {"LISTCON", "15"}, {"PRI", "16"}, {"SUBSCRIPT", "20"}}
goTab[44] = {{"CALLEXPR", "12"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"SUBSCRIPT", "20"}, {"TERM", "68"}}
goTab[45] = {{"CALLEXPR", "12"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"SUBSCRIPT", "20"}, {"TERM", "69"}}
goTab[49] = {{"AEXPR", "72"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"EXPR", "7"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"RELEXPR", "30"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[53] = {{"CALLEXPR", "12"}, {"EXPR", "74"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[54] = {{"CALLEXPR", "12"}, {"EXPR", "75"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[56] = {{"AEXPR", "77"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"EXPR", "7"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"RELEXPR", "30"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[57] = {{"AEXPR", "48"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"EXPLIST", "78"}, {"EXPR", "7"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"RELEXPR", "30"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[64] = {{"DECLLIST", "80"}, {"DECLSTMT", "81"}}
goTab[71] = {{"AEXPR", "48"}, {"CALLEXPR", "12"}, {"COMPEXPR", "1"}, {"EXPLIST", "83"}, {"EXPR", "7"}, {"FACT", "18"}, {"LISTCON", "15"}, {"PRI", "16"}, {"RELEXPR", "30"}, {"SUBSCRIPT", "20"}, {"TERM", "5"}}
goTab[84] = {{"BLOCKSTMT", "90"}}
goTab[87] = {{"BLOCKSTMT", "91"}}
goTab[88] = {{"DECLLIST", "92"}, {"DECLSTMT", "81"}}
actTab[0] = {{"TK_DEF", "s4"}, {"TK_ID", "s33"}, {"TK_IF", "s10"}, {"TK_LCURLY", "s32"}, {"TK_LET", "s21"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_PRINT", "s34"}, {"TK_RETURN", "s3"}, {"TK_STRING", "s11"}, {"TK_STRUCT", "s2"}}
actTab[1] = {{"TK_ASSIGN", "s35"}, {"TK_COMMA", "r26"}, {"TK_EQU", "s36"}, {"TK_NEQ", "s37"}, {"TK_RPAREN", "r26"}, {"TK_RSQB", "r26"}, {"TK_SEMI", "r26"}}
actTab[2] = {{"TK_ID", "s38"}}
actTab[3] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[4] = {{"TK_ID", "s40"}}
actTab[5] = {{"TK_ASSIGN", "r35"}, {"TK_COMMA", "r35"}, {"TK_DIV", "s41"}, {"TK_EQU", "r35"}, {"TK_GT", "r35"}, {"TK_LT", "r35"}, {"TK_MINUS", "r35"}, {"TK_MUL", "s42"}, {"TK_NEQ", "r35"}, {"TK_PLUS", "r35"}, {"TK_RPAREN", "r35"}, {"TK_RSQB", "r35"}, {"TK_SEMI", "r35"}}
actTab[6] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[7] = {{"TK_ASSIGN", "r32"}, {"TK_COMMA", "r32"}, {"TK_EQU", "r32"}, {"TK_GT", "r32"}, {"TK_LT", "r32"}, {"TK_MINUS", "s44"}, {"TK_NEQ", "r32"}, {"TK_PLUS", "s45"}, {"TK_RPAREN", "r32"}, {"TK_RSQB", "r32"}, {"TK_SEMI", "r32"}}
actTab[8] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[9] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_RPAREN", "r52"}, {"TK_RSQB", "r52"}, {"TK_STRING", "s11"}}
actTab[10] = {{"TK_LPAREN", "s49"}}
actTab[11] = {{"TK_ASSIGN", "r44"}, {"TK_COMMA", "r44"}, {"TK_DIV", "r44"}, {"TK_EQU", "r44"}, {"TK_GT", "r44"}, {"TK_LT", "r44"}, {"TK_MINUS", "r44"}, {"TK_MUL", "r44"}, {"TK_NEQ", "r44"}, {"TK_PLUS", "r44"}, {"TK_RPAREN", "r44"}, {"TK_RSQB", "r44"}, {"TK_SEMI", "r44"}}
actTab[12] = {{"TK_ASSIGN", "r45"}, {"TK_COMMA", "r45"}, {"TK_DIV", "r45"}, {"TK_EQU", "r45"}, {"TK_GT", "r45"}, {"TK_LT", "r45"}, {"TK_MINUS", "r45"}, {"TK_MUL", "r45"}, {"TK_NEQ", "r45"}, {"TK_PLUS", "r45"}, {"TK_RPAREN", "r45"}, {"TK_RSQB", "r45"}, {"TK_SEMI", "r45"}}
actTab[13] = {{"TK_DEF", "r11"}, {"TK_EOI", "r11"}, {"TK_ID", "r11"}, {"TK_IF", "r11"}, {"TK_LCURLY", "r11"}, {"TK_LET", "r11"}, {"TK_LPAREN", "r11"}, {"TK_LSQB", "r11"}, {"TK_MINUS", "r11"}, {"TK_NUM", "r11"}, {"TK_PRINT", "r11"}, {"TK_RCURLY", "r11"}, {"TK_RETURN", "r11"}, {"TK_STRING", "r11"}, {"TK_STRUCT", "r11"}}
actTab[14] = {{"TK_SEMI", "s50"}}
actTab[15] = {{"TK_ASSIGN", "r47"}, {"TK_COMMA", "r47"}, {"TK_DIV", "r47"}, {"TK_EQU", "r47"}, {"TK_GT", "r47"}, {"TK_LT", "r47"}, {"TK_MINUS", "r47"}, {"TK_MUL", "r47"}, {"TK_NEQ", "r47"}, {"TK_PLUS", "r47"}, {"TK_RPAREN", "r47"}, {"TK_RSQB", "r47"}, {"TK_SEMI", "r47"}}
actTab[16] = {{"TK_ASSIGN", "r40"}, {"TK_COMMA", "r40"}, {"TK_DIV", "r40"}, {"TK_EQU", "r40"}, {"TK_GT", "r40"}, {"TK_LT", "r40"}, {"TK_MINUS", "r40"}, {"TK_MUL", "r40"}, {"TK_NEQ", "r40"}, {"TK_PLUS", "r40"}, {"TK_RPAREN", "r40"}, {"TK_RSQB", "r40"}, {"TK_SEMI", "r40"}}
actTab[17] = {{"TK_ASSIGN", "r42"}, {"TK_COMMA", "r42"}, {"TK_DIV", "r42"}, {"TK_EQU", "r42"}, {"TK_GT", "r42"}, {"TK_LT", "r42"}, {"TK_MINUS", "r42"}, {"TK_MUL", "r42"}, {"TK_NEQ", "r42"}, {"TK_PLUS", "r42"}, {"TK_RPAREN", "r42"}, {"TK_RSQB", "r42"}, {"TK_SEMI", "r42"}}
actTab[18] = {{"TK_ASSIGN", "r38"}, {"TK_COMMA", "r38"}, {"TK_DIV", "r38"}, {"TK_EQU", "r38"}, {"TK_GT", "r38"}, {"TK_LT", "r38"}, {"TK_MINUS", "r38"}, {"TK_MUL", "r38"}, {"TK_NEQ", "r38"}, {"TK_PLUS", "r38"}, {"TK_RPAREN", "r38"}, {"TK_RSQB", "r38"}, {"TK_SEMI", "r38"}}
actTab[19] = {{"TK_EOI", "r2"}}
actTab[20] = {{"TK_ASSIGN", "r46"}, {"TK_COMMA", "r46"}, {"TK_DIV", "r46"}, {"TK_EQU", "r46"}, {"TK_GT", "r46"}, {"TK_LT", "r46"}, {"TK_MINUS", "r46"}, {"TK_MUL", "r46"}, {"TK_NEQ", "r46"}, {"TK_PLUS", "r46"}, {"TK_RPAREN", "r46"}, {"TK_RSQB", "r46"}, {"TK_SEMI", "r46"}}
actTab[21] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[22] = {{"TK_DEF", "r12"}, {"TK_EOI", "r12"}, {"TK_ID", "r12"}, {"TK_IF", "r12"}, {"TK_LCURLY", "r12"}, {"TK_LET", "r12"}, {"TK_LPAREN", "r12"}, {"TK_LSQB", "r12"}, {"TK_MINUS", "r12"}, {"TK_NUM", "r12"}, {"TK_PRINT", "r12"}, {"TK_RCURLY", "r12"}, {"TK_RETURN", "r12"}, {"TK_STRING", "r12"}, {"TK_STRUCT", "r12"}}
actTab[23] = {{"TK_DEF", "r9"}, {"TK_EOI", "r9"}, {"TK_ID", "r9"}, {"TK_IF", "r9"}, {"TK_LCURLY", "r9"}, {"TK_LET", "r9"}, {"TK_LPAREN", "r9"}, {"TK_LSQB", "r9"}, {"TK_MINUS", "r9"}, {"TK_NUM", "r9"}, {"TK_PRINT", "r9"}, {"TK_RCURLY", "r9"}, {"TK_RETURN", "r9"}, {"TK_STRING", "r9"}, {"TK_STRUCT", "r9"}}
actTab[24] = {{"TK_DEF", "r10"}, {"TK_EOI", "r10"}, {"TK_ID", "r10"}, {"TK_IF", "r10"}, {"TK_LCURLY", "r10"}, {"TK_LET", "r10"}, {"TK_LPAREN", "r10"}, {"TK_LSQB", "r10"}, {"TK_MINUS", "r10"}, {"TK_NUM", "r10"}, {"TK_PRINT", "r10"}, {"TK_RCURLY", "r10"}, {"TK_RETURN", "r10"}, {"TK_STRING", "r10"}, {"TK_STRUCT", "r10"}}
actTab[25] = {{"TK_DEF", "r8"}, {"TK_EOI", "r8"}, {"TK_ID", "r8"}, {"TK_IF", "r8"}, {"TK_LCURLY", "r8"}, {"TK_LET", "r8"}, {"TK_LPAREN", "r8"}, {"TK_LSQB", "r8"}, {"TK_MINUS", "r8"}, {"TK_NUM", "r8"}, {"TK_PRINT", "r8"}, {"TK_RCURLY", "r8"}, {"TK_RETURN", "r8"}, {"TK_STRING", "r8"}, {"TK_STRUCT", "r8"}}
actTab[26] = {{"TK_DEF", "r7"}, {"TK_EOI", "r7"}, {"TK_ID", "r7"}, {"TK_IF", "r7"}, {"TK_LCURLY", "r7"}, {"TK_LET", "r7"}, {"TK_LPAREN", "r7"}, {"TK_LSQB", "r7"}, {"TK_MINUS", "r7"}, {"TK_NUM", "r7"}, {"TK_PRINT", "r7"}, {"TK_RCURLY", "r7"}, {"TK_RETURN", "r7"}, {"TK_STRING", "r7"}, {"TK_STRUCT", "r7"}}
actTab[27] = {{"TK_DEF", "s4"}, {"TK_EOI", "r4"}, {"TK_ID", "s33"}, {"TK_IF", "s10"}, {"TK_LCURLY", "s32"}, {"TK_LET", "s21"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_PRINT", "s34"}, {"TK_RCURLY", "r4"}, {"TK_RETURN", "s3"}, {"TK_STRING", "s11"}, {"TK_STRUCT", "s2"}}
actTab[28] = {{"TK_DEF", "r6"}, {"TK_EOI", "r6"}, {"TK_ID", "r6"}, {"TK_IF", "r6"}, {"TK_LCURLY", "r6"}, {"TK_LET", "r6"}, {"TK_LPAREN", "r6"}, {"TK_LSQB", "r6"}, {"TK_MINUS", "r6"}, {"TK_NUM", "r6"}, {"TK_PRINT", "r6"}, {"TK_RCURLY", "r6"}, {"TK_RETURN", "r6"}, {"TK_STRING", "r6"}, {"TK_STRUCT", "r6"}}
actTab[29] = {{"TK_DEF", "r5"}, {"TK_EOI", "r5"}, {"TK_ID", "r5"}, {"TK_IF", "r5"}, {"TK_LCURLY", "r5"}, {"TK_LET", "r5"}, {"TK_LPAREN", "r5"}, {"TK_LSQB", "r5"}, {"TK_MINUS", "r5"}, {"TK_NUM", "r5"}, {"TK_PRINT", "r5"}, {"TK_RCURLY", "r5"}, {"TK_RETURN", "r5"}, {"TK_STRING", "r5"}, {"TK_STRUCT", "r5"}}
actTab[30] = {{"TK_ASSIGN", "r29"}, {"TK_COMMA", "r29"}, {"TK_EQU", "r29"}, {"TK_GT", "s53"}, {"TK_LT", "s54"}, {"TK_NEQ", "r29"}, {"TK_RPAREN", "r29"}, {"TK_RSQB", "r29"}, {"TK_SEMI", "r29"}}
actTab[31] = {{"$", "accept"}}
actTab[32] = {{"TK_DEF", "s4"}, {"TK_ID", "s33"}, {"TK_IF", "s10"}, {"TK_LCURLY", "s32"}, {"TK_LET", "s21"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_PRINT", "s34"}, {"TK_RETURN", "s3"}, {"TK_STRING", "s11"}, {"TK_STRUCT", "s2"}}
actTab[33] = {{"TK_ASSIGN", "r43"}, {"TK_COMMA", "r43"}, {"TK_DIV", "r43"}, {"TK_EQU", "r43"}, {"TK_GT", "r43"}, {"TK_LPAREN", "s57"}, {"TK_LSQB", "s56"}, {"TK_LT", "r43"}, {"TK_MINUS", "r43"}, {"TK_MUL", "r43"}, {"TK_NEQ", "r43"}, {"TK_PLUS", "r43"}, {"TK_RPAREN", "r43"}, {"TK_RSQB", "r43"}, {"TK_SEMI", "r43"}}
actTab[34] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[35] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[36] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[37] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[38] = {{"TK_LCURLY", "s32"}}
actTab[39] = {{"TK_SEMI", "s63"}}
actTab[40] = {{"TK_LPAREN", "s64"}}
actTab[41] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[42] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[43] = {{"TK_RPAREN", "s67"}}
actTab[44] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[45] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[46] = {{"TK_ASSIGN", "r39"}, {"TK_COMMA", "r39"}, {"TK_DIV", "r39"}, {"TK_EQU", "r39"}, {"TK_GT", "r39"}, {"TK_LT", "r39"}, {"TK_MINUS", "r39"}, {"TK_MUL", "r39"}, {"TK_NEQ", "r39"}, {"TK_PLUS", "r39"}, {"TK_RPAREN", "r39"}, {"TK_RSQB", "r39"}, {"TK_SEMI", "r39"}}
actTab[47] = {{"TK_RSQB", "s70"}}
actTab[48] = {{"TK_COMMA", "s71"}, {"TK_RPAREN", "r51"}, {"TK_RSQB", "r51"}}
actTab[49] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[50] = {{"TK_DEF", "r24"}, {"TK_EOI", "r24"}, {"TK_ID", "r24"}, {"TK_IF", "r24"}, {"TK_LCURLY", "r24"}, {"TK_LET", "r24"}, {"TK_LPAREN", "r24"}, {"TK_LSQB", "r24"}, {"TK_MINUS", "r24"}, {"TK_NUM", "r24"}, {"TK_PRINT", "r24"}, {"TK_RCURLY", "r24"}, {"TK_RETURN", "r24"}, {"TK_STRING", "r24"}, {"TK_STRUCT", "r24"}}
actTab[51] = {{"TK_SEMI", "s73"}}
actTab[52] = {{"TK_EOI", "r3"}, {"TK_RCURLY", "r3"}}
actTab[53] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[54] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[55] = {{"TK_RCURLY", "s76"}}
actTab[56] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_STRING", "s11"}}
actTab[57] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_RPAREN", "r52"}, {"TK_RSQB", "r52"}, {"TK_STRING", "s11"}}
actTab[58] = {{"TK_SEMI", "s79"}}
actTab[59] = {{"TK_COMMA", "r25"}, {"TK_RPAREN", "r25"}, {"TK_RSQB", "r25"}, {"TK_SEMI", "r25"}}
actTab[60] = {{"TK_ASSIGN", "r27"}, {"TK_COMMA", "r27"}, {"TK_EQU", "r27"}, {"TK_GT", "s53"}, {"TK_LT", "s54"}, {"TK_NEQ", "r27"}, {"TK_RPAREN", "r27"}, {"TK_RSQB", "r27"}, {"TK_SEMI", "r27"}}
actTab[61] = {{"TK_ASSIGN", "r28"}, {"TK_COMMA", "r28"}, {"TK_EQU", "r28"}, {"TK_GT", "s53"}, {"TK_LT", "s54"}, {"TK_NEQ", "r28"}, {"TK_RPAREN", "r28"}, {"TK_RSQB", "r28"}, {"TK_SEMI", "r28"}}
actTab[62] = {{"TK_DEF", "r22"}, {"TK_EOI", "r22"}, {"TK_ID", "r22"}, {"TK_IF", "r22"}, {"TK_LCURLY", "r22"}, {"TK_LET", "r22"}, {"TK_LPAREN", "r22"}, {"TK_LSQB", "r22"}, {"TK_MINUS", "r22"}, {"TK_NUM", "r22"}, {"TK_PRINT", "r22"}, {"TK_RCURLY", "r22"}, {"TK_RETURN", "r22"}, {"TK_STRING", "r22"}, {"TK_STRUCT", "r22"}}
actTab[63] = {{"TK_DEF", "r23"}, {"TK_EOI", "r23"}, {"TK_ID", "r23"}, {"TK_IF", "r23"}, {"TK_LCURLY", "r23"}, {"TK_LET", "r23"}, {"TK_LPAREN", "r23"}, {"TK_LSQB", "r23"}, {"TK_MINUS", "r23"}, {"TK_NUM", "r23"}, {"TK_PRINT", "r23"}, {"TK_RCURLY", "r23"}, {"TK_RETURN", "r23"}, {"TK_STRING", "r23"}, {"TK_STRUCT", "r23"}}
actTab[64] = {{"TK_LET", "s82"}, {"TK_RPAREN", "r16"}}
actTab[65] = {{"TK_ASSIGN", "r37"}, {"TK_COMMA", "r37"}, {"TK_DIV", "r37"}, {"TK_EQU", "r37"}, {"TK_GT", "r37"}, {"TK_LT", "r37"}, {"TK_MINUS", "r37"}, {"TK_MUL", "r37"}, {"TK_NEQ", "r37"}, {"TK_PLUS", "r37"}, {"TK_RPAREN", "r37"}, {"TK_RSQB", "r37"}, {"TK_SEMI", "r37"}}
actTab[66] = {{"TK_ASSIGN", "r36"}, {"TK_COMMA", "r36"}, {"TK_DIV", "r36"}, {"TK_EQU", "r36"}, {"TK_GT", "r36"}, {"TK_LT", "r36"}, {"TK_MINUS", "r36"}, {"TK_MUL", "r36"}, {"TK_NEQ", "r36"}, {"TK_PLUS", "r36"}, {"TK_RPAREN", "r36"}, {"TK_RSQB", "r36"}, {"TK_SEMI", "r36"}}
actTab[67] = {{"TK_ASSIGN", "r41"}, {"TK_COMMA", "r41"}, {"TK_DIV", "r41"}, {"TK_EQU", "r41"}, {"TK_GT", "r41"}, {"TK_LT", "r41"}, {"TK_MINUS", "r41"}, {"TK_MUL", "r41"}, {"TK_NEQ", "r41"}, {"TK_PLUS", "r41"}, {"TK_RPAREN", "r41"}, {"TK_RSQB", "r41"}, {"TK_SEMI", "r41"}}
actTab[68] = {{"TK_ASSIGN", "r34"}, {"TK_COMMA", "r34"}, {"TK_DIV", "s41"}, {"TK_EQU", "r34"}, {"TK_GT", "r34"}, {"TK_LT", "r34"}, {"TK_MINUS", "r34"}, {"TK_MUL", "s42"}, {"TK_NEQ", "r34"}, {"TK_PLUS", "r34"}, {"TK_RPAREN", "r34"}, {"TK_RSQB", "r34"}, {"TK_SEMI", "r34"}}
actTab[69] = {{"TK_ASSIGN", "r33"}, {"TK_COMMA", "r33"}, {"TK_DIV", "s41"}, {"TK_EQU", "r33"}, {"TK_GT", "r33"}, {"TK_LT", "r33"}, {"TK_MINUS", "r33"}, {"TK_MUL", "s42"}, {"TK_NEQ", "r33"}, {"TK_PLUS", "r33"}, {"TK_RPAREN", "r33"}, {"TK_RSQB", "r33"}, {"TK_SEMI", "r33"}}
actTab[70] = {{"TK_ASSIGN", "r53"}, {"TK_COMMA", "r53"}, {"TK_DIV", "r53"}, {"TK_EQU", "r53"}, {"TK_GT", "r53"}, {"TK_LT", "r53"}, {"TK_MINUS", "r53"}, {"TK_MUL", "r53"}, {"TK_NEQ", "r53"}, {"TK_PLUS", "r53"}, {"TK_RPAREN", "r53"}, {"TK_RSQB", "r53"}, {"TK_SEMI", "r53"}}
actTab[71] = {{"TK_ID", "s33"}, {"TK_LPAREN", "s6"}, {"TK_LSQB", "s9"}, {"TK_MINUS", "s8"}, {"TK_NUM", "s17"}, {"TK_RPAREN", "r52"}, {"TK_RSQB", "r52"}, {"TK_STRING", "s11"}}
actTab[72] = {{"TK_RPAREN", "s84"}}
actTab[73] = {{"TK_DEF", "r17"}, {"TK_EOI", "r17"}, {"TK_ID", "r17"}, {"TK_IF", "r17"}, {"TK_LCURLY", "r17"}, {"TK_LET", "r17"}, {"TK_LPAREN", "r17"}, {"TK_LSQB", "r17"}, {"TK_MINUS", "r17"}, {"TK_NUM", "r17"}, {"TK_PRINT", "r17"}, {"TK_RCURLY", "r17"}, {"TK_RETURN", "r17"}, {"TK_STRING", "r17"}, {"TK_STRUCT", "r17"}}
actTab[74] = {{"TK_ASSIGN", "r31"}, {"TK_COMMA", "r31"}, {"TK_EQU", "r31"}, {"TK_GT", "r31"}, {"TK_LT", "r31"}, {"TK_MINUS", "s44"}, {"TK_NEQ", "r31"}, {"TK_PLUS", "s45"}, {"TK_RPAREN", "r31"}, {"TK_RSQB", "r31"}, {"TK_SEMI", "r31"}}
actTab[75] = {{"TK_ASSIGN", "r30"}, {"TK_COMMA", "r30"}, {"TK_EQU", "r30"}, {"TK_GT", "r30"}, {"TK_LT", "r30"}, {"TK_MINUS", "s44"}, {"TK_NEQ", "r30"}, {"TK_PLUS", "s45"}, {"TK_RPAREN", "r30"}, {"TK_RSQB", "r30"}, {"TK_SEMI", "r30"}}
actTab[76] = {{"TK_DEF", "r19"}, {"TK_EOI", "r19"}, {"TK_ID", "r19"}, {"TK_IF", "r19"}, {"TK_LCURLY", "r19"}, {"TK_LET", "r19"}, {"TK_LPAREN", "r19"}, {"TK_LSQB", "r19"}, {"TK_MINUS", "r19"}, {"TK_NUM", "r19"}, {"TK_PRINT", "r19"}, {"TK_RCURLY", "r19"}, {"TK_RETURN", "r19"}, {"TK_STRING", "r19"}, {"TK_STRUCT", "r19"}}
actTab[77] = {{"TK_RSQB", "s85"}}
actTab[78] = {{"TK_RPAREN", "s86"}}
actTab[79] = {{"TK_DEF", "r18"}, {"TK_EOI", "r18"}, {"TK_ID", "r18"}, {"TK_IF", "r18"}, {"TK_LCURLY", "r18"}, {"TK_LET", "r18"}, {"TK_LPAREN", "r18"}, {"TK_LSQB", "r18"}, {"TK_MINUS", "r18"}, {"TK_NUM", "r18"}, {"TK_PRINT", "r18"}, {"TK_RCURLY", "r18"}, {"TK_RETURN", "r18"}, {"TK_STRING", "r18"}, {"TK_STRUCT", "r18"}}
actTab[80] = {{"TK_RPAREN", "s87"}}
actTab[81] = {{"TK_COMMA", "s88"}, {"TK_RPAREN", "r15"}}
actTab[82] = {{"TK_ID", "s89"}}
actTab[83] = {{"TK_RPAREN", "r50"}, {"TK_RSQB", "r50"}}
actTab[84] = {{"TK_LCURLY", "s32"}}
actTab[85] = {{"TK_ASSIGN", "r49"}, {"TK_COMMA", "r49"}, {"TK_DIV", "r49"}, {"TK_EQU", "r49"}, {"TK_GT", "r49"}, {"TK_LT", "r49"}, {"TK_MINUS", "r49"}, {"TK_MUL", "r49"}, {"TK_NEQ", "r49"}, {"TK_PLUS", "r49"}, {"TK_RPAREN", "r49"}, {"TK_RSQB", "r49"}, {"TK_SEMI", "r49"}}
actTab[86] = {{"TK_ASSIGN", "r48"}, {"TK_COMMA", "r48"}, {"TK_DIV", "r48"}, {"TK_EQU", "r48"}, {"TK_GT", "r48"}, {"TK_LT", "r48"}, {"TK_MINUS", "r48"}, {"TK_MUL", "r48"}, {"TK_NEQ", "r48"}, {"TK_PLUS", "r48"}, {"TK_RPAREN", "r48"}, {"TK_RSQB", "r48"}, {"TK_SEMI", "r48"}}
actTab[87] = {{"TK_LCURLY", "s32"}}
actTab[88] = {{"TK_LET", "s82"}, {"TK_RPAREN", "r16"}}
actTab[89] = {{"TK_COMMA", "r13"}, {"TK_RPAREN", "r13"}}
actTab[90] = {{"TK_DEF", "r20"}, {"TK_EOI", "r20"}, {"TK_ID", "r20"}, {"TK_IF", "r20"}, {"TK_LCURLY", "r20"}, {"TK_LET", "r20"}, {"TK_LPAREN", "r20"}, {"TK_LSQB", "r20"}, {"TK_MINUS", "r20"}, {"TK_NUM", "r20"}, {"TK_PRINT", "r20"}, {"TK_RCURLY", "r20"}, {"TK_RETURN", "r20"}, {"TK_STRING", "r20"}, {"TK_STRUCT", "r20"}}
actTab[91] = {{"TK_DEF", "r21"}, {"TK_EOI", "r21"}, {"TK_ID", "r21"}, {"TK_IF", "r21"}, {"TK_LCURLY", "r21"}, {"TK_LET", "r21"}, {"TK_LPAREN", "r21"}, {"TK_LSQB", "r21"}, {"TK_MINUS", "r21"}, {"TK_NUM", "r21"}, {"TK_PRINT", "r21"}, {"TK_RCURLY", "r21"}, {"TK_RETURN", "r21"}, {"TK_STRING", "r21"}, {"TK_STRUCT", "r21"}}
actTab[92] = {{"TK_RPAREN", "r14"}}
