#include <vector>
#include <map>
#include <set>
#include "production.hpp"
using namespace std; 
enum NTSYMBOL {
AEXPR, BLESSEXPR, BLOCKSTMT, CALLEXPR, COMPEXPR, 
DECLLIST, DECLSTMT, DEFSTMT, EXPLIST, EXPR, 
EXPSTMT, FACT, IFSTMT, LAMBDAEXPR, LETSTMT, 
LISTCON, PRI, PRINTSTMT, PROG, RELEXPR, 
RETSTMT, STMT, STMTLIST, STRUCTSTMT, SUBSCRIPT, 
TERM, sp
};
map<int, Production> prod;
void initprod() {
	 prod[1]  = Production(1,"sp", SymbolString({"PROG"}),"");
	 prod[2]  = Production(2,"PROG", SymbolString({"STMTLIST"}),"");
	 prod[3]  = Production(3,"STMTLIST", SymbolString({"STMT","STMTLIST"}),"@mklist");
	 prod[4]  = Production(4,"STMTLIST", SymbolString({"STMT"}),"");
	 prod[5]  = Production(5,"STMT", SymbolString({"EXPSTMT"}),"");
	 prod[6]  = Production(6,"STMT", SymbolString({"IFSTMT"}),"");
	 prod[7]  = Production(7,"STMT", SymbolString({"BLOCKSTMT"}),"");
	 prod[8]  = Production(8,"STMT", SymbolString({"PRINTSTMT"}),"");
	 prod[9]  = Production(9,"STMT", SymbolString({"LETSTMT"}),"");
	 prod[10]  = Production(10,"STMT", SymbolString({"DEFSTMT"}),"");
	 prod[11]  = Production(11,"STMT", SymbolString({"RETSTMT"}),"");
	 prod[12]  = Production(12,"STMT", SymbolString({"STRUCTSTMT"}),"");
	 prod[13]  = Production(13,"DECLSTMT", SymbolString({"TK_LET","TK_ID"}),"@mklet");
	 prod[14]  = Production(14,"DECLLIST", SymbolString({"DECLSTMT","TK_COMMA","DECLLIST"}),"@mklist");
	 prod[15]  = Production(15,"DECLLIST", SymbolString({"DECLSTMT"}),"");
	 prod[16]  = Production(16,"DECLLIST", SymbolString(),"");
	 prod[17]  = Production(17,"LETSTMT", SymbolString({"TK_LET","AEXPR","TK_SEMI"}),"@mklet");
	 prod[18]  = Production(18,"PRINTSTMT", SymbolString({"TK_PRINT","AEXPR","TK_SEMI"}),"@mkprint");
	 prod[19]  = Production(19,"BLOCKSTMT", SymbolString({"TK_LCURLY","STMTLIST","TK_RCURLY"}),"@mkblock");
	 prod[20]  = Production(20,"IFSTMT", SymbolString({"TK_IF","TK_LPAREN","AEXPR","TK_RPAREN","BLOCKSTMT"}),"@mkif");
	 prod[21]  = Production(21,"DEFSTMT", SymbolString({"TK_DEF","TK_ID","TK_LPAREN","DECLLIST","TK_RPAREN","BLOCKSTMT"}),"@mkfunc");
	 prod[22]  = Production(22,"STRUCTSTMT", SymbolString({"TK_STRUCT","TK_ID","BLOCKSTMT"}),"@mkstruct");
	 prod[23]  = Production(23,"RETSTMT", SymbolString({"TK_RETURN","AEXPR","TK_SEMI"}),"@mkret");
	 prod[24]  = Production(24,"EXPSTMT", SymbolString({"AEXPR","TK_SEMI"}),"@mkexprstmt");
	 prod[25]  = Production(25,"AEXPR", SymbolString({"COMPEXPR","TK_ASSIGN","AEXPR"}),"@binop");
	 prod[26]  = Production(26,"AEXPR", SymbolString({"COMPEXPR"}),"");
	 prod[27]  = Production(27,"COMPEXPR", SymbolString({"COMPEXPR","TK_EQU","RELEXPR"}),"@binop");
	 prod[28]  = Production(28,"COMPEXPR", SymbolString({"COMPEXPR","TK_NEQ","RELEXPR"}),"@binop");
	 prod[29]  = Production(29,"COMPEXPR", SymbolString({"RELEXPR"}),"");
	 prod[30]  = Production(30,"RELEXPR", SymbolString({"RELEXPR","TK_LT","EXPR"}),"@binop");
	 prod[31]  = Production(31,"RELEXPR", SymbolString({"RELEXPR","TK_GT","EXPR"}),"@binop");
	 prod[32]  = Production(32,"RELEXPR", SymbolString({"EXPR"}),"");
	 prod[33]  = Production(33,"EXPR", SymbolString({"EXPR","TK_PLUS","TERM"}),"@binop");
	 prod[34]  = Production(34,"EXPR", SymbolString({"EXPR","TK_MINUS","TERM"}),"@binop");
	 prod[35]  = Production(35,"EXPR", SymbolString({"TERM"}),"");
	 prod[36]  = Production(36,"TERM", SymbolString({"TERM","TK_MUL","FACT"}),"@binop");
	 prod[37]  = Production(37,"TERM", SymbolString({"TERM","TK_DIV","FACT"}),"@binop");
	 prod[38]  = Production(38,"TERM", SymbolString({"FACT"}),"");
	 prod[39]  = Production(39,"FACT", SymbolString({"TK_MINUS","PRI"}),"@unary");
	 prod[40]  = Production(40,"FACT", SymbolString({"PRI"}),"");
	 prod[41]  = Production(41,"PRI", SymbolString({"TK_LPAREN","AEXPR","TK_RPAREN"}),"@pass");
	 prod[42]  = Production(42,"PRI", SymbolString({"TK_NUM"}),"@num");
	 prod[43]  = Production(43,"PRI", SymbolString({"TK_ID"}),"@id");
	 prod[44]  = Production(44,"PRI", SymbolString({"TK_STRING"}),"@string");
	 prod[45]  = Production(45,"PRI", SymbolString({"CALLEXPR"}),"");
	 prod[46]  = Production(46,"PRI", SymbolString({"SUBSCRIPT"}),"");
	 prod[47]  = Production(47,"PRI", SymbolString({"LISTCON"}),"");
	 prod[48]  = Production(48,"PRI", SymbolString({"BLESSEXPR"}),"");
	 prod[49]  = Production(49,"PRI", SymbolString({"LAMBDAEXPR"}),"");
	 prod[50]  = Production(50,"CALLEXPR", SymbolString({"TK_ID","TK_LPAREN","EXPLIST","TK_RPAREN"}),"@mkcall");
	 prod[51]  = Production(51,"SUBSCRIPT", SymbolString({"TK_ID","TK_LSQB","AEXPR","TK_RSQB"}),"@mksubscript");
	 prod[52]  = Production(52,"EXPLIST", SymbolString({"AEXPR","TK_COMMA","EXPLIST"}),"@mklist");
	 prod[53]  = Production(53,"EXPLIST", SymbolString({"AEXPR"}),"");
	 prod[54]  = Production(54,"EXPLIST", SymbolString(),"");
	 prod[55]  = Production(55,"LISTCON", SymbolString({"TK_LSQB","EXPLIST","TK_RSQB"}),"@mklistcon");
	 prod[56]  = Production(56,"BLESSEXPR", SymbolString({"TK_NEW","TK_ID","TK_LPAREN","EXPLIST","TK_RPAREN"}),"@mkbless");
	 prod[57]  = Production(57,"LAMBDAEXPR", SymbolString({"TK_AMPER","TK_LPAREN","DECLLIST","TK_RPAREN","BLOCKSTMT"}),"@mklambda");
}
map<int,map<string,string>> goTab;
void initgoTab() {
	 goTab[0] = {{"AEXPR", "18"}, {"BLESSEXPR", "22"}, {"BLOCKSTMT", "33"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"DEFSTMT", "31"}, {"EXPR", "15"}, {"EXPSTMT", "36"}, {"FACT", "26"}, {"IFSTMT", "35"}, {"LAMBDAEXPR", "10"}, {"LETSTMT", "30"}, {"LISTCON", "19"}, {"PRI", "21"}, {"PRINTSTMT", "32"}, {"PROG", "37"}, {"RELEXPR", "38"}, {"RETSTMT", "17"}, {"STMT", "34"}, {"STMTLIST", "27"}, {"STRUCTSTMT", "29"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[3] = {{"AEXPR", "43"}, {"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "38"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[5] = {{"AEXPR", "18"}, {"BLESSEXPR", "22"}, {"BLOCKSTMT", "33"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"DEFSTMT", "31"}, {"EXPR", "15"}, {"EXPSTMT", "36"}, {"FACT", "26"}, {"IFSTMT", "35"}, {"LAMBDAEXPR", "10"}, {"LETSTMT", "30"}, {"LISTCON", "19"}, {"PRI", "21"}, {"PRINTSTMT", "32"}, {"RELEXPR", "38"}, {"RETSTMT", "17"}, {"STMT", "34"}, {"STMTLIST", "45"}, {"STRUCTSTMT", "29"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[7] = {{"AEXPR", "47"}, {"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "38"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[12] = {{"AEXPR", "50"}, {"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"EXPLIST", "51"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "38"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[14] = {{"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "53"}, {"SUBSCRIPT", "11"}};
	 goTab[23] = {{"AEXPR", "58"}, {"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "38"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[28] = {{"AEXPR", "61"}, {"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "38"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[34] = {{"AEXPR", "18"}, {"BLESSEXPR", "22"}, {"BLOCKSTMT", "33"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"DEFSTMT", "31"}, {"EXPR", "15"}, {"EXPSTMT", "36"}, {"FACT", "26"}, {"IFSTMT", "35"}, {"LAMBDAEXPR", "10"}, {"LETSTMT", "30"}, {"LISTCON", "19"}, {"PRI", "21"}, {"PRINTSTMT", "32"}, {"RELEXPR", "38"}, {"RETSTMT", "17"}, {"STMT", "34"}, {"STMTLIST", "62"}, {"STRUCTSTMT", "29"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[39] = {{"AEXPR", "65"}, {"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "38"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[40] = {{"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "66"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[41] = {{"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "67"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[42] = {{"BLOCKSTMT", "68"}};
	 goTab[46] = {{"AEXPR", "72"}, {"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "38"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[48] = {{"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"FACT", "74"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"SUBSCRIPT", "11"}};
	 goTab[49] = {{"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"FACT", "75"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"SUBSCRIPT", "11"}};
	 goTab[52] = {{"DECLLIST", "78"}, {"DECLSTMT", "79"}};
	 goTab[54] = {{"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"SUBSCRIPT", "11"}, {"TERM", "81"}};
	 goTab[55] = {{"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"SUBSCRIPT", "11"}, {"TERM", "82"}};
	 goTab[59] = {{"AEXPR", "85"}, {"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "38"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[60] = {{"AEXPR", "50"}, {"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"EXPLIST", "86"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "38"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[63] = {{"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"EXPR", "88"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[64] = {{"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"EXPR", "89"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[70] = {{"DECLLIST", "90"}, {"DECLSTMT", "79"}};
	 goTab[76] = {{"AEXPR", "50"}, {"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"EXPLIST", "92"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "38"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[83] = {{"AEXPR", "50"}, {"BLESSEXPR", "22"}, {"CALLEXPR", "16"}, {"COMPEXPR", "1"}, {"EXPLIST", "96"}, {"EXPR", "15"}, {"FACT", "26"}, {"LAMBDAEXPR", "10"}, {"LISTCON", "19"}, {"PRI", "21"}, {"RELEXPR", "38"}, {"SUBSCRIPT", "11"}, {"TERM", "9"}};
	 goTab[91] = {{"BLOCKSTMT", "100"}};
	 goTab[93] = {{"BLOCKSTMT", "101"}};
	 goTab[94] = {{"DECLLIST", "102"}, {"DECLSTMT", "79"}};
	 goTab[99] = {{"BLOCKSTMT", "104"}};
}
map<int,map<string,string>> actTab;
void initactTab() {
	 actTab[0] = {{"TK_AMPER", "s13"}, {"TK_DEF", "s4"}, {"TK_ID", "s24"}, {"TK_IF", "s6"}, {"TK_LCURLY", "s5"}, {"TK_LET", "s28"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_PRINT", "s23"}, {"TK_RETURN", "s3"}, {"TK_STRING", "s8"}, {"TK_STRUCT", "s2"}};
	 actTab[1] = {{"TK_ASSIGN", "s39"}, {"TK_COMMA", "r26"}, {"TK_EQU", "s40"}, {"TK_NEQ", "s41"}, {"TK_RPAREN", "r26"}, {"TK_RSQB", "r26"}, {"TK_SEMI", "r26"}};
	 actTab[2] = {{"TK_ID", "s42"}};
	 actTab[3] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[4] = {{"TK_ID", "s44"}};
	 actTab[5] = {{"TK_AMPER", "s13"}, {"TK_DEF", "s4"}, {"TK_ID", "s24"}, {"TK_IF", "s6"}, {"TK_LCURLY", "s5"}, {"TK_LET", "s28"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_PRINT", "s23"}, {"TK_RETURN", "s3"}, {"TK_STRING", "s8"}, {"TK_STRUCT", "s2"}};
	 actTab[6] = {{"TK_LPAREN", "s46"}};
	 actTab[7] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[8] = {{"TK_ASSIGN", "r44"}, {"TK_COMMA", "r44"}, {"TK_DIV", "r44"}, {"TK_EQU", "r44"}, {"TK_GT", "r44"}, {"TK_LT", "r44"}, {"TK_MINUS", "r44"}, {"TK_MUL", "r44"}, {"TK_NEQ", "r44"}, {"TK_PLUS", "r44"}, {"TK_RPAREN", "r44"}, {"TK_RSQB", "r44"}, {"TK_SEMI", "r44"}};
	 actTab[9] = {{"TK_ASSIGN", "r35"}, {"TK_COMMA", "r35"}, {"TK_DIV", "s48"}, {"TK_EQU", "r35"}, {"TK_GT", "r35"}, {"TK_LT", "r35"}, {"TK_MINUS", "r35"}, {"TK_MUL", "s49"}, {"TK_NEQ", "r35"}, {"TK_PLUS", "r35"}, {"TK_RPAREN", "r35"}, {"TK_RSQB", "r35"}, {"TK_SEMI", "r35"}};
	 actTab[10] = {{"TK_ASSIGN", "r49"}, {"TK_COMMA", "r49"}, {"TK_DIV", "r49"}, {"TK_EQU", "r49"}, {"TK_GT", "r49"}, {"TK_LT", "r49"}, {"TK_MINUS", "r49"}, {"TK_MUL", "r49"}, {"TK_NEQ", "r49"}, {"TK_PLUS", "r49"}, {"TK_RPAREN", "r49"}, {"TK_RSQB", "r49"}, {"TK_SEMI", "r49"}};
	 actTab[11] = {{"TK_ASSIGN", "r46"}, {"TK_COMMA", "r46"}, {"TK_DIV", "r46"}, {"TK_EQU", "r46"}, {"TK_GT", "r46"}, {"TK_LT", "r46"}, {"TK_MINUS", "r46"}, {"TK_MUL", "r46"}, {"TK_NEQ", "r46"}, {"TK_PLUS", "r46"}, {"TK_RPAREN", "r46"}, {"TK_RSQB", "r46"}, {"TK_SEMI", "r46"}};
	 actTab[12] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_RPAREN", "r54"}, {"TK_RSQB", "r54"}, {"TK_STRING", "s8"}};
	 actTab[13] = {{"TK_LPAREN", "s52"}};
	 actTab[14] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[15] = {{"TK_ASSIGN", "r32"}, {"TK_COMMA", "r32"}, {"TK_EQU", "r32"}, {"TK_GT", "r32"}, {"TK_LT", "r32"}, {"TK_MINUS", "s54"}, {"TK_NEQ", "r32"}, {"TK_PLUS", "s55"}, {"TK_RPAREN", "r32"}, {"TK_RSQB", "r32"}, {"TK_SEMI", "r32"}};
	 actTab[16] = {{"TK_ASSIGN", "r45"}, {"TK_COMMA", "r45"}, {"TK_DIV", "r45"}, {"TK_EQU", "r45"}, {"TK_GT", "r45"}, {"TK_LT", "r45"}, {"TK_MINUS", "r45"}, {"TK_MUL", "r45"}, {"TK_NEQ", "r45"}, {"TK_PLUS", "r45"}, {"TK_RPAREN", "r45"}, {"TK_RSQB", "r45"}, {"TK_SEMI", "r45"}};
	 actTab[17] = {{"TK_AMPER", "r11"}, {"TK_DEF", "r11"}, {"TK_EOI", "r11"}, {"TK_ID", "r11"}, {"TK_IF", "r11"}, {"TK_LCURLY", "r11"}, {"TK_LET", "r11"}, {"TK_LPAREN", "r11"}, {"TK_LSQB", "r11"}, {"TK_MINUS", "r11"}, {"TK_NEW", "r11"}, {"TK_NUM", "r11"}, {"TK_PRINT", "r11"}, {"TK_RCURLY", "r11"}, {"TK_RETURN", "r11"}, {"TK_STRING", "r11"}, {"TK_STRUCT", "r11"}};
	 actTab[18] = {{"TK_SEMI", "s56"}};
	 actTab[19] = {{"TK_ASSIGN", "r47"}, {"TK_COMMA", "r47"}, {"TK_DIV", "r47"}, {"TK_EQU", "r47"}, {"TK_GT", "r47"}, {"TK_LT", "r47"}, {"TK_MINUS", "r47"}, {"TK_MUL", "r47"}, {"TK_NEQ", "r47"}, {"TK_PLUS", "r47"}, {"TK_RPAREN", "r47"}, {"TK_RSQB", "r47"}, {"TK_SEMI", "r47"}};
	 actTab[20] = {{"TK_ID", "s57"}};
	 actTab[21] = {{"TK_ASSIGN", "r40"}, {"TK_COMMA", "r40"}, {"TK_DIV", "r40"}, {"TK_EQU", "r40"}, {"TK_GT", "r40"}, {"TK_LT", "r40"}, {"TK_MINUS", "r40"}, {"TK_MUL", "r40"}, {"TK_NEQ", "r40"}, {"TK_PLUS", "r40"}, {"TK_RPAREN", "r40"}, {"TK_RSQB", "r40"}, {"TK_SEMI", "r40"}};
	 actTab[22] = {{"TK_ASSIGN", "r48"}, {"TK_COMMA", "r48"}, {"TK_DIV", "r48"}, {"TK_EQU", "r48"}, {"TK_GT", "r48"}, {"TK_LT", "r48"}, {"TK_MINUS", "r48"}, {"TK_MUL", "r48"}, {"TK_NEQ", "r48"}, {"TK_PLUS", "r48"}, {"TK_RPAREN", "r48"}, {"TK_RSQB", "r48"}, {"TK_SEMI", "r48"}};
	 actTab[23] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[24] = {{"TK_ASSIGN", "r43"}, {"TK_COMMA", "r43"}, {"TK_DIV", "r43"}, {"TK_EQU", "r43"}, {"TK_GT", "r43"}, {"TK_LPAREN", "s60"}, {"TK_LSQB", "s59"}, {"TK_LT", "r43"}, {"TK_MINUS", "r43"}, {"TK_MUL", "r43"}, {"TK_NEQ", "r43"}, {"TK_PLUS", "r43"}, {"TK_RPAREN", "r43"}, {"TK_RSQB", "r43"}, {"TK_SEMI", "r43"}};
	 actTab[25] = {{"TK_ASSIGN", "r42"}, {"TK_COMMA", "r42"}, {"TK_DIV", "r42"}, {"TK_EQU", "r42"}, {"TK_GT", "r42"}, {"TK_LT", "r42"}, {"TK_MINUS", "r42"}, {"TK_MUL", "r42"}, {"TK_NEQ", "r42"}, {"TK_PLUS", "r42"}, {"TK_RPAREN", "r42"}, {"TK_RSQB", "r42"}, {"TK_SEMI", "r42"}};
	 actTab[26] = {{"TK_ASSIGN", "r38"}, {"TK_COMMA", "r38"}, {"TK_DIV", "r38"}, {"TK_EQU", "r38"}, {"TK_GT", "r38"}, {"TK_LT", "r38"}, {"TK_MINUS", "r38"}, {"TK_MUL", "r38"}, {"TK_NEQ", "r38"}, {"TK_PLUS", "r38"}, {"TK_RPAREN", "r38"}, {"TK_RSQB", "r38"}, {"TK_SEMI", "r38"}};
	 actTab[27] = {{"TK_EOI", "r2"}};
	 actTab[28] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[29] = {{"TK_AMPER", "r12"}, {"TK_DEF", "r12"}, {"TK_EOI", "r12"}, {"TK_ID", "r12"}, {"TK_IF", "r12"}, {"TK_LCURLY", "r12"}, {"TK_LET", "r12"}, {"TK_LPAREN", "r12"}, {"TK_LSQB", "r12"}, {"TK_MINUS", "r12"}, {"TK_NEW", "r12"}, {"TK_NUM", "r12"}, {"TK_PRINT", "r12"}, {"TK_RCURLY", "r12"}, {"TK_RETURN", "r12"}, {"TK_STRING", "r12"}, {"TK_STRUCT", "r12"}};
	 actTab[30] = {{"TK_AMPER", "r9"}, {"TK_DEF", "r9"}, {"TK_EOI", "r9"}, {"TK_ID", "r9"}, {"TK_IF", "r9"}, {"TK_LCURLY", "r9"}, {"TK_LET", "r9"}, {"TK_LPAREN", "r9"}, {"TK_LSQB", "r9"}, {"TK_MINUS", "r9"}, {"TK_NEW", "r9"}, {"TK_NUM", "r9"}, {"TK_PRINT", "r9"}, {"TK_RCURLY", "r9"}, {"TK_RETURN", "r9"}, {"TK_STRING", "r9"}, {"TK_STRUCT", "r9"}};
	 actTab[31] = {{"TK_AMPER", "r10"}, {"TK_DEF", "r10"}, {"TK_EOI", "r10"}, {"TK_ID", "r10"}, {"TK_IF", "r10"}, {"TK_LCURLY", "r10"}, {"TK_LET", "r10"}, {"TK_LPAREN", "r10"}, {"TK_LSQB", "r10"}, {"TK_MINUS", "r10"}, {"TK_NEW", "r10"}, {"TK_NUM", "r10"}, {"TK_PRINT", "r10"}, {"TK_RCURLY", "r10"}, {"TK_RETURN", "r10"}, {"TK_STRING", "r10"}, {"TK_STRUCT", "r10"}};
	 actTab[32] = {{"TK_AMPER", "r8"}, {"TK_DEF", "r8"}, {"TK_EOI", "r8"}, {"TK_ID", "r8"}, {"TK_IF", "r8"}, {"TK_LCURLY", "r8"}, {"TK_LET", "r8"}, {"TK_LPAREN", "r8"}, {"TK_LSQB", "r8"}, {"TK_MINUS", "r8"}, {"TK_NEW", "r8"}, {"TK_NUM", "r8"}, {"TK_PRINT", "r8"}, {"TK_RCURLY", "r8"}, {"TK_RETURN", "r8"}, {"TK_STRING", "r8"}, {"TK_STRUCT", "r8"}};
	 actTab[33] = {{"TK_AMPER", "r7"}, {"TK_DEF", "r7"}, {"TK_EOI", "r7"}, {"TK_ID", "r7"}, {"TK_IF", "r7"}, {"TK_LCURLY", "r7"}, {"TK_LET", "r7"}, {"TK_LPAREN", "r7"}, {"TK_LSQB", "r7"}, {"TK_MINUS", "r7"}, {"TK_NEW", "r7"}, {"TK_NUM", "r7"}, {"TK_PRINT", "r7"}, {"TK_RCURLY", "r7"}, {"TK_RETURN", "r7"}, {"TK_STRING", "r7"}, {"TK_STRUCT", "r7"}};
	 actTab[34] = {{"TK_AMPER", "s13"}, {"TK_DEF", "s4"}, {"TK_EOI", "r4"}, {"TK_ID", "s24"}, {"TK_IF", "s6"}, {"TK_LCURLY", "s5"}, {"TK_LET", "s28"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_PRINT", "s23"}, {"TK_RCURLY", "r4"}, {"TK_RETURN", "s3"}, {"TK_STRING", "s8"}, {"TK_STRUCT", "s2"}};
	 actTab[35] = {{"TK_AMPER", "r6"}, {"TK_DEF", "r6"}, {"TK_EOI", "r6"}, {"TK_ID", "r6"}, {"TK_IF", "r6"}, {"TK_LCURLY", "r6"}, {"TK_LET", "r6"}, {"TK_LPAREN", "r6"}, {"TK_LSQB", "r6"}, {"TK_MINUS", "r6"}, {"TK_NEW", "r6"}, {"TK_NUM", "r6"}, {"TK_PRINT", "r6"}, {"TK_RCURLY", "r6"}, {"TK_RETURN", "r6"}, {"TK_STRING", "r6"}, {"TK_STRUCT", "r6"}};
	 actTab[36] = {{"TK_AMPER", "r5"}, {"TK_DEF", "r5"}, {"TK_EOI", "r5"}, {"TK_ID", "r5"}, {"TK_IF", "r5"}, {"TK_LCURLY", "r5"}, {"TK_LET", "r5"}, {"TK_LPAREN", "r5"}, {"TK_LSQB", "r5"}, {"TK_MINUS", "r5"}, {"TK_NEW", "r5"}, {"TK_NUM", "r5"}, {"TK_PRINT", "r5"}, {"TK_RCURLY", "r5"}, {"TK_RETURN", "r5"}, {"TK_STRING", "r5"}, {"TK_STRUCT", "r5"}};
	 actTab[37] = {{"$", "accept"}};
	 actTab[38] = {{"TK_ASSIGN", "r29"}, {"TK_COMMA", "r29"}, {"TK_EQU", "r29"}, {"TK_GT", "s63"}, {"TK_LT", "s64"}, {"TK_NEQ", "r29"}, {"TK_RPAREN", "r29"}, {"TK_RSQB", "r29"}, {"TK_SEMI", "r29"}};
	 actTab[39] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[40] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[41] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[42] = {{"TK_LCURLY", "s5"}};
	 actTab[43] = {{"TK_SEMI", "s69"}};
	 actTab[44] = {{"TK_LPAREN", "s70"}};
	 actTab[45] = {{"TK_RCURLY", "s71"}};
	 actTab[46] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[47] = {{"TK_RPAREN", "s73"}};
	 actTab[48] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[49] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[50] = {{"TK_COMMA", "s76"}, {"TK_RPAREN", "r53"}, {"TK_RSQB", "r53"}};
	 actTab[51] = {{"TK_RSQB", "s77"}};
	 actTab[52] = {{"TK_LET", "s80"}, {"TK_RPAREN", "r16"}};
	 actTab[53] = {{"TK_ASSIGN", "r39"}, {"TK_COMMA", "r39"}, {"TK_DIV", "r39"}, {"TK_EQU", "r39"}, {"TK_GT", "r39"}, {"TK_LT", "r39"}, {"TK_MINUS", "r39"}, {"TK_MUL", "r39"}, {"TK_NEQ", "r39"}, {"TK_PLUS", "r39"}, {"TK_RPAREN", "r39"}, {"TK_RSQB", "r39"}, {"TK_SEMI", "r39"}};
	 actTab[54] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[55] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[56] = {{"TK_AMPER", "r24"}, {"TK_DEF", "r24"}, {"TK_EOI", "r24"}, {"TK_ID", "r24"}, {"TK_IF", "r24"}, {"TK_LCURLY", "r24"}, {"TK_LET", "r24"}, {"TK_LPAREN", "r24"}, {"TK_LSQB", "r24"}, {"TK_MINUS", "r24"}, {"TK_NEW", "r24"}, {"TK_NUM", "r24"}, {"TK_PRINT", "r24"}, {"TK_RCURLY", "r24"}, {"TK_RETURN", "r24"}, {"TK_STRING", "r24"}, {"TK_STRUCT", "r24"}};
	 actTab[57] = {{"TK_LPAREN", "s83"}};
	 actTab[58] = {{"TK_SEMI", "s84"}};
	 actTab[59] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[60] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_RPAREN", "r54"}, {"TK_RSQB", "r54"}, {"TK_STRING", "s8"}};
	 actTab[61] = {{"TK_SEMI", "s87"}};
	 actTab[62] = {{"TK_EOI", "r3"}, {"TK_RCURLY", "r3"}};
	 actTab[63] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[64] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_STRING", "s8"}};
	 actTab[65] = {{"TK_COMMA", "r25"}, {"TK_RPAREN", "r25"}, {"TK_RSQB", "r25"}, {"TK_SEMI", "r25"}};
	 actTab[66] = {{"TK_ASSIGN", "r27"}, {"TK_COMMA", "r27"}, {"TK_EQU", "r27"}, {"TK_GT", "s63"}, {"TK_LT", "s64"}, {"TK_NEQ", "r27"}, {"TK_RPAREN", "r27"}, {"TK_RSQB", "r27"}, {"TK_SEMI", "r27"}};
	 actTab[67] = {{"TK_ASSIGN", "r28"}, {"TK_COMMA", "r28"}, {"TK_EQU", "r28"}, {"TK_GT", "s63"}, {"TK_LT", "s64"}, {"TK_NEQ", "r28"}, {"TK_RPAREN", "r28"}, {"TK_RSQB", "r28"}, {"TK_SEMI", "r28"}};
	 actTab[68] = {{"TK_AMPER", "r22"}, {"TK_DEF", "r22"}, {"TK_EOI", "r22"}, {"TK_ID", "r22"}, {"TK_IF", "r22"}, {"TK_LCURLY", "r22"}, {"TK_LET", "r22"}, {"TK_LPAREN", "r22"}, {"TK_LSQB", "r22"}, {"TK_MINUS", "r22"}, {"TK_NEW", "r22"}, {"TK_NUM", "r22"}, {"TK_PRINT", "r22"}, {"TK_RCURLY", "r22"}, {"TK_RETURN", "r22"}, {"TK_STRING", "r22"}, {"TK_STRUCT", "r22"}};
	 actTab[69] = {{"TK_AMPER", "r23"}, {"TK_DEF", "r23"}, {"TK_EOI", "r23"}, {"TK_ID", "r23"}, {"TK_IF", "r23"}, {"TK_LCURLY", "r23"}, {"TK_LET", "r23"}, {"TK_LPAREN", "r23"}, {"TK_LSQB", "r23"}, {"TK_MINUS", "r23"}, {"TK_NEW", "r23"}, {"TK_NUM", "r23"}, {"TK_PRINT", "r23"}, {"TK_RCURLY", "r23"}, {"TK_RETURN", "r23"}, {"TK_STRING", "r23"}, {"TK_STRUCT", "r23"}};
	 actTab[70] = {{"TK_LET", "s80"}, {"TK_RPAREN", "r16"}};
	 actTab[71] = {{"TK_AMPER", "r19"}, {"TK_ASSIGN", "r19"}, {"TK_COMMA", "r19"}, {"TK_DEF", "r19"}, {"TK_DIV", "r19"}, {"TK_EOI", "r19"}, {"TK_EQU", "r19"}, {"TK_GT", "r19"}, {"TK_ID", "r19"}, {"TK_IF", "r19"}, {"TK_LCURLY", "r19"}, {"TK_LET", "r19"}, {"TK_LPAREN", "r19"}, {"TK_LSQB", "r19"}, {"TK_LT", "r19"}, {"TK_MINUS", "r19"}, {"TK_MUL", "r19"}, {"TK_NEQ", "r19"}, {"TK_NEW", "r19"}, {"TK_NUM", "r19"}, {"TK_PLUS", "r19"}, {"TK_PRINT", "r19"}, {"TK_RCURLY", "r19"}, {"TK_RETURN", "r19"}, {"TK_RPAREN", "r19"}, {"TK_RSQB", "r19"}, {"TK_SEMI", "r19"}, {"TK_STRING", "r19"}, {"TK_STRUCT", "r19"}};
	 actTab[72] = {{"TK_RPAREN", "s91"}};
	 actTab[73] = {{"TK_ASSIGN", "r41"}, {"TK_COMMA", "r41"}, {"TK_DIV", "r41"}, {"TK_EQU", "r41"}, {"TK_GT", "r41"}, {"TK_LT", "r41"}, {"TK_MINUS", "r41"}, {"TK_MUL", "r41"}, {"TK_NEQ", "r41"}, {"TK_PLUS", "r41"}, {"TK_RPAREN", "r41"}, {"TK_RSQB", "r41"}, {"TK_SEMI", "r41"}};
	 actTab[74] = {{"TK_ASSIGN", "r37"}, {"TK_COMMA", "r37"}, {"TK_DIV", "r37"}, {"TK_EQU", "r37"}, {"TK_GT", "r37"}, {"TK_LT", "r37"}, {"TK_MINUS", "r37"}, {"TK_MUL", "r37"}, {"TK_NEQ", "r37"}, {"TK_PLUS", "r37"}, {"TK_RPAREN", "r37"}, {"TK_RSQB", "r37"}, {"TK_SEMI", "r37"}};
	 actTab[75] = {{"TK_ASSIGN", "r36"}, {"TK_COMMA", "r36"}, {"TK_DIV", "r36"}, {"TK_EQU", "r36"}, {"TK_GT", "r36"}, {"TK_LT", "r36"}, {"TK_MINUS", "r36"}, {"TK_MUL", "r36"}, {"TK_NEQ", "r36"}, {"TK_PLUS", "r36"}, {"TK_RPAREN", "r36"}, {"TK_RSQB", "r36"}, {"TK_SEMI", "r36"}};
	 actTab[76] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_RPAREN", "r54"}, {"TK_RSQB", "r54"}, {"TK_STRING", "s8"}};
	 actTab[77] = {{"TK_ASSIGN", "r55"}, {"TK_COMMA", "r55"}, {"TK_DIV", "r55"}, {"TK_EQU", "r55"}, {"TK_GT", "r55"}, {"TK_LT", "r55"}, {"TK_MINUS", "r55"}, {"TK_MUL", "r55"}, {"TK_NEQ", "r55"}, {"TK_PLUS", "r55"}, {"TK_RPAREN", "r55"}, {"TK_RSQB", "r55"}, {"TK_SEMI", "r55"}};
	 actTab[78] = {{"TK_RPAREN", "s93"}};
	 actTab[79] = {{"TK_COMMA", "s94"}, {"TK_RPAREN", "r15"}};
	 actTab[80] = {{"TK_ID", "s95"}};
	 actTab[81] = {{"TK_ASSIGN", "r34"}, {"TK_COMMA", "r34"}, {"TK_DIV", "s48"}, {"TK_EQU", "r34"}, {"TK_GT", "r34"}, {"TK_LT", "r34"}, {"TK_MINUS", "r34"}, {"TK_MUL", "s49"}, {"TK_NEQ", "r34"}, {"TK_PLUS", "r34"}, {"TK_RPAREN", "r34"}, {"TK_RSQB", "r34"}, {"TK_SEMI", "r34"}};
	 actTab[82] = {{"TK_ASSIGN", "r33"}, {"TK_COMMA", "r33"}, {"TK_DIV", "s48"}, {"TK_EQU", "r33"}, {"TK_GT", "r33"}, {"TK_LT", "r33"}, {"TK_MINUS", "r33"}, {"TK_MUL", "s49"}, {"TK_NEQ", "r33"}, {"TK_PLUS", "r33"}, {"TK_RPAREN", "r33"}, {"TK_RSQB", "r33"}, {"TK_SEMI", "r33"}};
	 actTab[83] = {{"TK_AMPER", "s13"}, {"TK_ID", "s24"}, {"TK_LPAREN", "s7"}, {"TK_LSQB", "s12"}, {"TK_MINUS", "s14"}, {"TK_NEW", "s20"}, {"TK_NUM", "s25"}, {"TK_RPAREN", "r54"}, {"TK_RSQB", "r54"}, {"TK_STRING", "s8"}};
	 actTab[84] = {{"TK_AMPER", "r18"}, {"TK_DEF", "r18"}, {"TK_EOI", "r18"}, {"TK_ID", "r18"}, {"TK_IF", "r18"}, {"TK_LCURLY", "r18"}, {"TK_LET", "r18"}, {"TK_LPAREN", "r18"}, {"TK_LSQB", "r18"}, {"TK_MINUS", "r18"}, {"TK_NEW", "r18"}, {"TK_NUM", "r18"}, {"TK_PRINT", "r18"}, {"TK_RCURLY", "r18"}, {"TK_RETURN", "r18"}, {"TK_STRING", "r18"}, {"TK_STRUCT", "r18"}};
	 actTab[85] = {{"TK_RSQB", "s97"}};
	 actTab[86] = {{"TK_RPAREN", "s98"}};
	 actTab[87] = {{"TK_AMPER", "r17"}, {"TK_DEF", "r17"}, {"TK_EOI", "r17"}, {"TK_ID", "r17"}, {"TK_IF", "r17"}, {"TK_LCURLY", "r17"}, {"TK_LET", "r17"}, {"TK_LPAREN", "r17"}, {"TK_LSQB", "r17"}, {"TK_MINUS", "r17"}, {"TK_NEW", "r17"}, {"TK_NUM", "r17"}, {"TK_PRINT", "r17"}, {"TK_RCURLY", "r17"}, {"TK_RETURN", "r17"}, {"TK_STRING", "r17"}, {"TK_STRUCT", "r17"}};
	 actTab[88] = {{"TK_ASSIGN", "r31"}, {"TK_COMMA", "r31"}, {"TK_EQU", "r31"}, {"TK_GT", "r31"}, {"TK_LT", "r31"}, {"TK_MINUS", "s54"}, {"TK_NEQ", "r31"}, {"TK_PLUS", "s55"}, {"TK_RPAREN", "r31"}, {"TK_RSQB", "r31"}, {"TK_SEMI", "r31"}};
	 actTab[89] = {{"TK_ASSIGN", "r30"}, {"TK_COMMA", "r30"}, {"TK_EQU", "r30"}, {"TK_GT", "r30"}, {"TK_LT", "r30"}, {"TK_MINUS", "s54"}, {"TK_NEQ", "r30"}, {"TK_PLUS", "s55"}, {"TK_RPAREN", "r30"}, {"TK_RSQB", "r30"}, {"TK_SEMI", "r30"}};
	 actTab[90] = {{"TK_RPAREN", "s99"}};
	 actTab[91] = {{"TK_LCURLY", "s5"}};
	 actTab[92] = {{"TK_RPAREN", "r52"}, {"TK_RSQB", "r52"}};
	 actTab[93] = {{"TK_LCURLY", "s5"}};
	 actTab[94] = {{"TK_LET", "s80"}, {"TK_RPAREN", "r16"}};
	 actTab[95] = {{"TK_COMMA", "r13"}, {"TK_RPAREN", "r13"}};
	 actTab[96] = {{"TK_RPAREN", "s103"}};
	 actTab[97] = {{"TK_ASSIGN", "r51"}, {"TK_COMMA", "r51"}, {"TK_DIV", "r51"}, {"TK_EQU", "r51"}, {"TK_GT", "r51"}, {"TK_LT", "r51"}, {"TK_MINUS", "r51"}, {"TK_MUL", "r51"}, {"TK_NEQ", "r51"}, {"TK_PLUS", "r51"}, {"TK_RPAREN", "r51"}, {"TK_RSQB", "r51"}, {"TK_SEMI", "r51"}};
	 actTab[98] = {{"TK_ASSIGN", "r50"}, {"TK_COMMA", "r50"}, {"TK_DIV", "r50"}, {"TK_EQU", "r50"}, {"TK_GT", "r50"}, {"TK_LT", "r50"}, {"TK_MINUS", "r50"}, {"TK_MUL", "r50"}, {"TK_NEQ", "r50"}, {"TK_PLUS", "r50"}, {"TK_RPAREN", "r50"}, {"TK_RSQB", "r50"}, {"TK_SEMI", "r50"}};
	 actTab[99] = {{"TK_LCURLY", "s5"}};
	 actTab[100] = {{"TK_AMPER", "r20"}, {"TK_DEF", "r20"}, {"TK_EOI", "r20"}, {"TK_ID", "r20"}, {"TK_IF", "r20"}, {"TK_LCURLY", "r20"}, {"TK_LET", "r20"}, {"TK_LPAREN", "r20"}, {"TK_LSQB", "r20"}, {"TK_MINUS", "r20"}, {"TK_NEW", "r20"}, {"TK_NUM", "r20"}, {"TK_PRINT", "r20"}, {"TK_RCURLY", "r20"}, {"TK_RETURN", "r20"}, {"TK_STRING", "r20"}, {"TK_STRUCT", "r20"}};
	 actTab[101] = {{"TK_ASSIGN", "r57"}, {"TK_COMMA", "r57"}, {"TK_DIV", "r57"}, {"TK_EQU", "r57"}, {"TK_GT", "r57"}, {"TK_LT", "r57"}, {"TK_MINUS", "r57"}, {"TK_MUL", "r57"}, {"TK_NEQ", "r57"}, {"TK_PLUS", "r57"}, {"TK_RPAREN", "r57"}, {"TK_RSQB", "r57"}, {"TK_SEMI", "r57"}};
	 actTab[102] = {{"TK_RPAREN", "r14"}};
	 actTab[103] = {{"TK_ASSIGN", "r56"}, {"TK_COMMA", "r56"}, {"TK_DIV", "r56"}, {"TK_EQU", "r56"}, {"TK_GT", "r56"}, {"TK_LT", "r56"}, {"TK_MINUS", "r56"}, {"TK_MUL", "r56"}, {"TK_NEQ", "r56"}, {"TK_PLUS", "r56"}, {"TK_RPAREN", "r56"}, {"TK_RSQB", "r56"}, {"TK_SEMI", "r56"}};
	 actTab[104] = {{"TK_AMPER", "r21"}, {"TK_DEF", "r21"}, {"TK_EOI", "r21"}, {"TK_ID", "r21"}, {"TK_IF", "r21"}, {"TK_LCURLY", "r21"}, {"TK_LET", "r21"}, {"TK_LPAREN", "r21"}, {"TK_LSQB", "r21"}, {"TK_MINUS", "r21"}, {"TK_NEW", "r21"}, {"TK_NUM", "r21"}, {"TK_PRINT", "r21"}, {"TK_RCURLY", "r21"}, {"TK_RETURN", "r21"}, {"TK_STRING", "r21"}, {"TK_STRUCT", "r21"}};
}
