#include <vector>
#include <map>
#include <set>
#include <functional>
#include "production.hpp"
using namespace std; 
enum NTSYMBOL {
ADDOP, ARGLIST, COMPOUNDSTMT, DECLLIST, DECLSTMT, 
EXPR, EXPRLIST, FACT, IDENTLIST, IFSTMT, 
MULOP, OPTSTMT, PARAMLIST, POST, PRI, 
PRINTSTMT, PROCSTMT, PROCTSMT, PROG, PROGHEADER, 
PROGT, RELOP, RETSTMT, SIMPEXPR, STANDTYPE, 
STMT, STMTLIST, SUBDECL, SUBDECLLIST, SUBHEAD, 
TERM, TYPE, VAR, WHILESTMT, sp

};
map<int, Production> prod;
void initprod() {
	 prod[1]  = Production(1,"sp", SymbolString({"PROG"}),"");
	 prod[2]  = Production(2,"PROG", SymbolString({"PROGHEADER","DECLLIST","SUBDECLLIST","PROGT"}),"@mkList");
	 prod[3]  = Production(3,"PROGHEADER", SymbolString({"TK_PROGRAM","TK_ID","TK_LPAREN","IDENTLIST","TK_RPAREN","TK_SEMI"}),"");
	 prod[4]  = Production(4,"PROGT", SymbolString({"COMPOUNDSTMT","TK_PERIOD"}),"");
	 prod[5]  = Production(5,"IDENTLIST", SymbolString({"PRI","TK_COMMA","IDENTLIST"}),"@mkList");
	 prod[6]  = Production(6,"IDENTLIST", SymbolString({"PRI"}),"");
	 prod[7]  = Production(7,"DECLLIST", SymbolString({"DECLSTMT","TK_SEMI","DECLLIST"}),"@mkList");
	 prod[8]  = Production(8,"DECLLIST", SymbolString(),"");
	 prod[9]  = Production(9,"DECLSTMT", SymbolString({"TK_VAR","IDENTLIST","TK_COLON","TYPE"}),"@mkLet");
	 prod[10]  = Production(10,"TYPE", SymbolString({"STANDTYPE"}),"");
	 prod[11]  = Production(11,"STANDTYPE", SymbolString({"TK_INTEGER"}),"");
	 prod[12]  = Production(12,"STANDTYPE", SymbolString({"TK_REAL"}),"");
	 prod[13]  = Production(13,"SUBDECLLIST", SymbolString({"SUBDECL","TK_SEMI","SUBDECLLIST"}),"");
	 prod[14]  = Production(14,"SUBDECLLIST", SymbolString(),"");
	 prod[15]  = Production(15,"SUBDECL", SymbolString({"SUBHEAD","DECLLIST","COMPOUNDSTMT"}),"@mkFunc");
	 prod[16]  = Production(16,"SUBHEAD", SymbolString({"TK_DEF","TK_ID","ARGLIST","TK_COLON","TYPE","TK_SEMI"}),"@mkFuncHeader");
	 prod[17]  = Production(17,"ARGLIST", SymbolString({"TK_LPAREN","PARAMLIST","TK_RPAREN"}),"@pass");
	 prod[18]  = Production(18,"PARAMLIST", SymbolString({"PARAMLIST","TK_SEMI","IDENTLIST","TK_COLON","TYPE"}),"@mkList");
	 prod[19]  = Production(19,"PARAMLIST", SymbolString({"IDENTLIST","TK_COLON","TYPE"}),"");
	 prod[20]  = Production(20,"COMPOUNDSTMT", SymbolString({"TK_BEGIN","OPTSTMT","TK_END"}),"@mkBlock");
	 prod[21]  = Production(21,"OPTSTMT", SymbolString({"STMTLIST"}),"");
	 prod[22]  = Production(22,"OPTSTMT", SymbolString(),"");
	 prod[23]  = Production(23,"STMTLIST", SymbolString({"STMT","TK_SEMI","STMTLIST"}),"@mkList");
	 prod[24]  = Production(24,"STMTLIST", SymbolString({"STMT"}),"");
	 prod[25]  = Production(25,"STMT", SymbolString({"VAR","TK_ASSIGN","EXPR"}),"@binop");
	 prod[26]  = Production(26,"STMT", SymbolString({"PROCSTMT"}),"");
	 prod[27]  = Production(27,"STMT", SymbolString({"COMPOUNDSTMT"}),"");
	 prod[28]  = Production(28,"STMT", SymbolString({"IFSTMT"}),"");
	 prod[29]  = Production(29,"STMT", SymbolString({"WHILESTMT"}),"");
	 prod[30]  = Production(30,"STMT", SymbolString({"PRINTSTMT"}),"");
	 prod[31]  = Production(31,"STMT", SymbolString({"RETSTMT"}),"");
	 prod[32]  = Production(32,"IFSTMT", SymbolString({"TK_IF","EXPR","TK_THEN","STMT","TK_ELSE","STMT"}),"@mkIf");
	 prod[33]  = Production(33,"WHILESTMT", SymbolString({"TK_WHILE","EXPR","TK_DO","STMT"}),"@mkWhile");
	 prod[34]  = Production(34,"PRINTSTMT", SymbolString({"TK_PRINT","EXPR"}),"@mkPrint");
	 prod[35]  = Production(35,"RETSTMT", SymbolString({"TK_RETURN","EXPR"}),"@mkRet");
	 prod[36]  = Production(36,"VAR", SymbolString({"TK_ID"}),"@mkId");
	 prod[37]  = Production(37,"VAR", SymbolString({"TK_ID","TK_LSQB","EXPR","TK_RSQB"}),"@mkSubscript");
	 prod[38]  = Production(38,"PROCTSMT", SymbolString({"TK_ID","TK_LPAREN","EXPRLIST","TK_RPAREN"}),"@mkCall");
	 prod[39]  = Production(39,"EXPRLIST", SymbolString({"EXPRLIST","TK_COMMA","EXPR"}),"@mkList");
	 prod[40]  = Production(40,"EXPRLIST", SymbolString({"EXPR"}),"");
	 prod[41]  = Production(41,"EXPR", SymbolString({"SIMPEXPR","RELOP","SIMPEXPR"}),"@binop");
	 prod[42]  = Production(42,"EXPR", SymbolString({"SIMPEXPR"}),"");
	 prod[43]  = Production(43,"SIMPEXPR", SymbolString({"SIMPEXPR","ADDOP","TERM"}),"@binop");
	 prod[44]  = Production(44,"SIMPEXPR", SymbolString({"TERM"}),"");
	 prod[45]  = Production(45,"TERM", SymbolString({"TERM","MULOP","FACT"}),"@binop");
	 prod[46]  = Production(46,"TERM", SymbolString({"FACT"}),"");
	 prod[47]  = Production(47,"FACT", SymbolString({"TK_MINUS","POST"}),"@unary");
	 prod[48]  = Production(48,"FACT", SymbolString({"POST"}),"");
	 prod[49]  = Production(49,"POST", SymbolString({"PRI","TK_LPAREN","EXPRLIST","TK_RPAREN"}),"@mkCall");
	 prod[50]  = Production(50,"POST", SymbolString({"PRI"}),"");
	 prod[51]  = Production(51,"PRI", SymbolString({"TK_ID"}),"@mkId");
	 prod[52]  = Production(52,"PRI", SymbolString({"TK_NUM"}),"@mkNum");
	 prod[53]  = Production(53,"PRI", SymbolString({"TK_LPAREN","EXPR","TK_RPAREN"}),"@pass");
	 prod[54]  = Production(54,"RELOP", SymbolString({"TK_LT"}),"");
	 prod[55]  = Production(55,"RELOP", SymbolString({"TK_GT"}),"");
	 prod[56]  = Production(56,"RELOP", SymbolString({"TK_EQU"}),"");
	 prod[57]  = Production(57,"RELOP", SymbolString({"TK_NEQ"}),"");
	 prod[58]  = Production(58,"ADDOP", SymbolString({"TK_PLUS"}),"");
	 prod[59]  = Production(59,"ADDOP", SymbolString({"TK_MINUS"}),"");
	 prod[60]  = Production(60,"ADDOP", SymbolString({"TK_OR"}),"");
	 prod[61]  = Production(61,"MULOP", SymbolString({"TK_MUL"}),"");
	 prod[62]  = Production(62,"MULOP", SymbolString({"TK_DIV"}),"");
	 prod[63]  = Production(63,"MULOP", SymbolString({"TK_MOD"}),"");
	 prod[64]  = Production(64,"MULOP", SymbolString({"TK_AND"}),"");
}
map<int,map<string,string>> goTab;
void initgoTab() {
	 goTab[0] = {{"PROG", "3"}, {"PROGHEADER", "2"}};
	 goTab[2] = {{"DECLLIST", "7"}, {"DECLSTMT", "6"}};
	 goTab[5] = {{"IDENTLIST", "13"}, {"PRI", "12"}};
	 goTab[7] = {{"SUBDECL", "17"}, {"SUBDECLLIST", "18"}, {"SUBHEAD", "16"}};
	 goTab[8] = {{"IDENTLIST", "19"}, {"PRI", "12"}};
	 goTab[9] = {{"EXPR", "26"}, {"FACT", "22"}, {"POST", "21"}, {"PRI", "20"}, {"SIMPEXPR", "24"}, {"TERM", "23"}};
	 goTab[14] = {{"DECLLIST", "29"}, {"DECLSTMT", "6"}};
	 goTab[16] = {{"DECLLIST", "31"}, {"DECLSTMT", "6"}};
	 goTab[18] = {{"COMPOUNDSTMT", "34"}, {"PROGT", "35"}};
	 goTab[23] = {{"MULOP", "42"}};
	 goTab[24] = {{"ADDOP", "50"}, {"RELOP", "51"}};
	 goTab[25] = {{"POST", "52"}, {"PRI", "20"}};
	 goTab[27] = {{"IDENTLIST", "54"}, {"PRI", "12"}};
	 goTab[28] = {{"STANDTYPE", "57"}, {"TYPE", "58"}};
	 goTab[30] = {{"ARGLIST", "60"}};
	 goTab[31] = {{"COMPOUNDSTMT", "61"}};
	 goTab[32] = {{"SUBDECL", "17"}, {"SUBDECLLIST", "62"}, {"SUBHEAD", "16"}};
	 goTab[33] = {{"COMPOUNDSTMT", "71"}, {"IFSTMT", "72"}, {"OPTSTMT", "64"}, {"PRINTSTMT", "74"}, {"PROCSTMT", "68"}, {"RETSTMT", "75"}, {"STMT", "66"}, {"STMTLIST", "77"}, {"VAR", "67"}, {"WHILESTMT", "73"}};
	 goTab[37] = {{"EXPR", "80"}, {"EXPRLIST", "81"}, {"FACT", "22"}, {"POST", "21"}, {"PRI", "20"}, {"SIMPEXPR", "24"}, {"TERM", "23"}};
	 goTab[42] = {{"FACT", "82"}, {"POST", "21"}, {"PRI", "20"}};
	 goTab[50] = {{"FACT", "22"}, {"POST", "21"}, {"PRI", "20"}, {"TERM", "83"}};
	 goTab[51] = {{"FACT", "22"}, {"POST", "21"}, {"PRI", "20"}, {"SIMPEXPR", "84"}, {"TERM", "23"}};
	 goTab[59] = {{"IDENTLIST", "85"}, {"PARAMLIST", "86"}, {"PRI", "12"}};
	 goTab[63] = {{"EXPR", "88"}, {"FACT", "22"}, {"POST", "21"}, {"PRI", "20"}, {"SIMPEXPR", "24"}, {"TERM", "23"}};
	 goTab[69] = {{"EXPR", "93"}, {"FACT", "22"}, {"POST", "21"}, {"PRI", "20"}, {"SIMPEXPR", "24"}, {"TERM", "23"}};
	 goTab[70] = {{"EXPR", "94"}, {"FACT", "22"}, {"POST", "21"}, {"PRI", "20"}, {"SIMPEXPR", "24"}, {"TERM", "23"}};
	 goTab[76] = {{"EXPR", "95"}, {"FACT", "22"}, {"POST", "21"}, {"PRI", "20"}, {"SIMPEXPR", "24"}, {"TERM", "23"}};
	 goTab[83] = {{"MULOP", "42"}};
	 goTab[84] = {{"ADDOP", "50"}};
	 goTab[87] = {{"STANDTYPE", "57"}, {"TYPE", "101"}};
	 goTab[90] = {{"EXPR", "102"}, {"FACT", "22"}, {"POST", "21"}, {"PRI", "20"}, {"SIMPEXPR", "24"}, {"TERM", "23"}};
	 goTab[91] = {{"COMPOUNDSTMT", "71"}, {"IFSTMT", "72"}, {"PRINTSTMT", "74"}, {"PROCSTMT", "68"}, {"RETSTMT", "75"}, {"STMT", "66"}, {"STMTLIST", "103"}, {"VAR", "67"}, {"WHILESTMT", "73"}};
	 goTab[92] = {{"EXPR", "104"}, {"FACT", "22"}, {"POST", "21"}, {"PRI", "20"}, {"SIMPEXPR", "24"}, {"TERM", "23"}};
	 goTab[96] = {{"EXPR", "107"}, {"FACT", "22"}, {"POST", "21"}, {"PRI", "20"}, {"SIMPEXPR", "24"}, {"TERM", "23"}};
	 goTab[98] = {{"STANDTYPE", "57"}, {"TYPE", "108"}};
	 goTab[99] = {{"IDENTLIST", "109"}, {"PRI", "12"}};
	 goTab[105] = {{"COMPOUNDSTMT", "71"}, {"IFSTMT", "72"}, {"PRINTSTMT", "74"}, {"PROCSTMT", "68"}, {"RETSTMT", "75"}, {"STMT", "112"}, {"VAR", "67"}, {"WHILESTMT", "73"}};
	 goTab[106] = {{"COMPOUNDSTMT", "71"}, {"IFSTMT", "72"}, {"PRINTSTMT", "74"}, {"PROCSTMT", "68"}, {"RETSTMT", "75"}, {"STMT", "113"}, {"VAR", "67"}, {"WHILESTMT", "73"}};
	 goTab[114] = {{"STANDTYPE", "57"}, {"TYPE", "116"}};
	 goTab[115] = {{"COMPOUNDSTMT", "71"}, {"IFSTMT", "72"}, {"PRINTSTMT", "74"}, {"PROCSTMT", "68"}, {"RETSTMT", "75"}, {"STMT", "117"}, {"VAR", "67"}, {"WHILESTMT", "73"}};
}
map<int,map<string,string>> actTab;
void initactTab() {
	 actTab[0] = {{"TK_PROGRAM", "s1"}};
	 actTab[1] = {{"TK_ID", "s4"}};
	 actTab[2] = {{"TK_BEGIN", "r8"}, {"TK_DEF", "r8"}, {"TK_EOI", "r8"}, {"TK_VAR", "s5"}};
	 actTab[3] = {{"$", "accept"}};
	 actTab[4] = {{"TK_LPAREN", "s8"}};
	 actTab[5] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_NUM", "s10"}};
	 actTab[6] = {{"TK_SEMI", "s14"}};
	 actTab[7] = {{"TK_BEGIN", "r14"}, {"TK_DEF", "s15"}};
	 actTab[8] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_NUM", "s10"}};
	 actTab[9] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s25"}, {"TK_NUM", "s10"}};
	 actTab[10] = {{"TK_AND", "r52"}, {"TK_COLON", "r52"}, {"TK_COMMA", "r52"}, {"TK_DIV", "r52"}, {"TK_DO", "r52"}, {"TK_ELSE", "r52"}, {"TK_END", "r52"}, {"TK_EQU", "r52"}, {"TK_GT", "r52"}, {"TK_LPAREN", "r52"}, {"TK_LT", "r52"}, {"TK_MINUS", "r52"}, {"TK_MOD", "r52"}, {"TK_MUL", "r52"}, {"TK_NEQ", "r52"}, {"TK_OR", "r52"}, {"TK_PLUS", "r52"}, {"TK_RPAREN", "r52"}, {"TK_RSQB", "r52"}, {"TK_SEMI", "r52"}, {"TK_THEN", "r52"}};
	 actTab[11] = {{"TK_AND", "r51"}, {"TK_COLON", "r51"}, {"TK_COMMA", "r51"}, {"TK_DIV", "r51"}, {"TK_DO", "r51"}, {"TK_ELSE", "r51"}, {"TK_END", "r51"}, {"TK_EQU", "r51"}, {"TK_GT", "r51"}, {"TK_LPAREN", "r51"}, {"TK_LT", "r51"}, {"TK_MINUS", "r51"}, {"TK_MOD", "r51"}, {"TK_MUL", "r51"}, {"TK_NEQ", "r51"}, {"TK_OR", "r51"}, {"TK_PLUS", "r51"}, {"TK_RPAREN", "r51"}, {"TK_RSQB", "r51"}, {"TK_SEMI", "r51"}, {"TK_THEN", "r51"}};
	 actTab[12] = {{"TK_COLON", "r6"}, {"TK_COMMA", "s27"}, {"TK_RPAREN", "r6"}};
	 actTab[13] = {{"TK_COLON", "s28"}};
	 actTab[14] = {{"TK_BEGIN", "r8"}, {"TK_DEF", "r8"}, {"TK_EOI", "r8"}, {"TK_VAR", "s5"}};
	 actTab[15] = {{"TK_ID", "s30"}};
	 actTab[16] = {{"TK_BEGIN", "r8"}, {"TK_VAR", "s5"}};
	 actTab[17] = {{"TK_SEMI", "s32"}};
	 actTab[18] = {{"TK_BEGIN", "s33"}};
	 actTab[19] = {{"TK_RPAREN", "s36"}};
	 actTab[20] = {{"TK_AND", "r50"}, {"TK_COMMA", "r50"}, {"TK_DIV", "r50"}, {"TK_DO", "r50"}, {"TK_ELSE", "r50"}, {"TK_END", "r50"}, {"TK_EQU", "r50"}, {"TK_GT", "r50"}, {"TK_LPAREN", "s37"}, {"TK_LT", "r50"}, {"TK_MINUS", "r50"}, {"TK_MOD", "r50"}, {"TK_MUL", "r50"}, {"TK_NEQ", "r50"}, {"TK_OR", "r50"}, {"TK_PLUS", "r50"}, {"TK_RPAREN", "r50"}, {"TK_RSQB", "r50"}, {"TK_SEMI", "r50"}, {"TK_THEN", "r50"}};
	 actTab[21] = {{"TK_AND", "r48"}, {"TK_COMMA", "r48"}, {"TK_DIV", "r48"}, {"TK_DO", "r48"}, {"TK_ELSE", "r48"}, {"TK_END", "r48"}, {"TK_EQU", "r48"}, {"TK_GT", "r48"}, {"TK_LT", "r48"}, {"TK_MINUS", "r48"}, {"TK_MOD", "r48"}, {"TK_MUL", "r48"}, {"TK_NEQ", "r48"}, {"TK_OR", "r48"}, {"TK_PLUS", "r48"}, {"TK_RPAREN", "r48"}, {"TK_RSQB", "r48"}, {"TK_SEMI", "r48"}, {"TK_THEN", "r48"}};
	 actTab[22] = {{"TK_AND", "r46"}, {"TK_COMMA", "r46"}, {"TK_DIV", "r46"}, {"TK_DO", "r46"}, {"TK_ELSE", "r46"}, {"TK_END", "r46"}, {"TK_EQU", "r46"}, {"TK_GT", "r46"}, {"TK_LT", "r46"}, {"TK_MINUS", "r46"}, {"TK_MOD", "r46"}, {"TK_MUL", "r46"}, {"TK_NEQ", "r46"}, {"TK_OR", "r46"}, {"TK_PLUS", "r46"}, {"TK_RPAREN", "r46"}, {"TK_RSQB", "r46"}, {"TK_SEMI", "r46"}, {"TK_THEN", "r46"}};
	 actTab[23] = {{"TK_AND", "s40"}, {"TK_COMMA", "r44"}, {"TK_DIV", "s39"}, {"TK_DO", "r44"}, {"TK_ELSE", "r44"}, {"TK_END", "r44"}, {"TK_EQU", "r44"}, {"TK_GT", "r44"}, {"TK_LT", "r44"}, {"TK_MINUS", "r44"}, {"TK_MOD", "s38"}, {"TK_MUL", "s41"}, {"TK_NEQ", "r44"}, {"TK_OR", "r44"}, {"TK_PLUS", "r44"}, {"TK_RPAREN", "r44"}, {"TK_RSQB", "r44"}, {"TK_SEMI", "r44"}, {"TK_THEN", "r44"}};
	 actTab[24] = {{"TK_COMMA", "r42"}, {"TK_DO", "r42"}, {"TK_ELSE", "r42"}, {"TK_END", "r42"}, {"TK_EQU", "s46"}, {"TK_GT", "s47"}, {"TK_LT", "s48"}, {"TK_MINUS", "s43"}, {"TK_NEQ", "s45"}, {"TK_OR", "s44"}, {"TK_PLUS", "s49"}, {"TK_RPAREN", "r42"}, {"TK_RSQB", "r42"}, {"TK_SEMI", "r42"}, {"TK_THEN", "r42"}};
	 actTab[25] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_NUM", "s10"}};
	 actTab[26] = {{"TK_RPAREN", "s53"}};
	 actTab[27] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_NUM", "s10"}};
	 actTab[28] = {{"TK_INTEGER", "s56"}, {"TK_REAL", "s55"}};
	 actTab[29] = {{"TK_BEGIN", "r7"}, {"TK_DEF", "r7"}, {"TK_EOI", "r7"}};
	 actTab[30] = {{"TK_LPAREN", "s59"}};
	 actTab[31] = {{"TK_BEGIN", "s33"}};
	 actTab[32] = {{"TK_BEGIN", "r14"}, {"TK_DEF", "s15"}};
	 actTab[33] = {{"TK_BEGIN", "s33"}, {"TK_END", "r22"}, {"TK_ID", "s65"}, {"TK_IF", "s69"}, {"TK_PRINT", "s70"}, {"TK_RETURN", "s63"}, {"TK_WHILE", "s76"}};
	 actTab[34] = {{"TK_PERIOD", "s78"}};
	 actTab[35] = {{"TK_EOI", "r2"}};
	 actTab[36] = {{"TK_SEMI", "s79"}};
	 actTab[37] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s25"}, {"TK_NUM", "s10"}};
	 actTab[38] = {{"TK_ID", "r63"}, {"TK_LPAREN", "r63"}, {"TK_MINUS", "r63"}, {"TK_NUM", "r63"}};
	 actTab[39] = {{"TK_ID", "r62"}, {"TK_LPAREN", "r62"}, {"TK_MINUS", "r62"}, {"TK_NUM", "r62"}};
	 actTab[40] = {{"TK_ID", "r64"}, {"TK_LPAREN", "r64"}, {"TK_MINUS", "r64"}, {"TK_NUM", "r64"}};
	 actTab[41] = {{"TK_ID", "r61"}, {"TK_LPAREN", "r61"}, {"TK_MINUS", "r61"}, {"TK_NUM", "r61"}};
	 actTab[42] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s25"}, {"TK_NUM", "s10"}};
	 actTab[43] = {{"TK_ID", "r59"}, {"TK_LPAREN", "r59"}, {"TK_MINUS", "r59"}, {"TK_NUM", "r59"}};
	 actTab[44] = {{"TK_ID", "r60"}, {"TK_LPAREN", "r60"}, {"TK_MINUS", "r60"}, {"TK_NUM", "r60"}};
	 actTab[45] = {{"TK_ID", "r57"}, {"TK_LPAREN", "r57"}, {"TK_MINUS", "r57"}, {"TK_NUM", "r57"}};
	 actTab[46] = {{"TK_ID", "r56"}, {"TK_LPAREN", "r56"}, {"TK_MINUS", "r56"}, {"TK_NUM", "r56"}};
	 actTab[47] = {{"TK_ID", "r55"}, {"TK_LPAREN", "r55"}, {"TK_MINUS", "r55"}, {"TK_NUM", "r55"}};
	 actTab[48] = {{"TK_ID", "r54"}, {"TK_LPAREN", "r54"}, {"TK_MINUS", "r54"}, {"TK_NUM", "r54"}};
	 actTab[49] = {{"TK_ID", "r58"}, {"TK_LPAREN", "r58"}, {"TK_MINUS", "r58"}, {"TK_NUM", "r58"}};
	 actTab[50] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s25"}, {"TK_NUM", "s10"}};
	 actTab[51] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s25"}, {"TK_NUM", "s10"}};
	 actTab[52] = {{"TK_AND", "r47"}, {"TK_COMMA", "r47"}, {"TK_DIV", "r47"}, {"TK_DO", "r47"}, {"TK_ELSE", "r47"}, {"TK_END", "r47"}, {"TK_EQU", "r47"}, {"TK_GT", "r47"}, {"TK_LT", "r47"}, {"TK_MINUS", "r47"}, {"TK_MOD", "r47"}, {"TK_MUL", "r47"}, {"TK_NEQ", "r47"}, {"TK_OR", "r47"}, {"TK_PLUS", "r47"}, {"TK_RPAREN", "r47"}, {"TK_RSQB", "r47"}, {"TK_SEMI", "r47"}, {"TK_THEN", "r47"}};
	 actTab[53] = {{"TK_AND", "r53"}, {"TK_COLON", "r53"}, {"TK_COMMA", "r53"}, {"TK_DIV", "r53"}, {"TK_DO", "r53"}, {"TK_ELSE", "r53"}, {"TK_END", "r53"}, {"TK_EQU", "r53"}, {"TK_GT", "r53"}, {"TK_LPAREN", "r53"}, {"TK_LT", "r53"}, {"TK_MINUS", "r53"}, {"TK_MOD", "r53"}, {"TK_MUL", "r53"}, {"TK_NEQ", "r53"}, {"TK_OR", "r53"}, {"TK_PLUS", "r53"}, {"TK_RPAREN", "r53"}, {"TK_RSQB", "r53"}, {"TK_SEMI", "r53"}, {"TK_THEN", "r53"}};
	 actTab[54] = {{"TK_COLON", "r5"}, {"TK_RPAREN", "r5"}};
	 actTab[55] = {{"TK_RPAREN", "r12"}, {"TK_SEMI", "r12"}};
	 actTab[56] = {{"TK_RPAREN", "r11"}, {"TK_SEMI", "r11"}};
	 actTab[57] = {{"TK_RPAREN", "r10"}, {"TK_SEMI", "r10"}};
	 actTab[58] = {{"TK_SEMI", "r9"}};
	 actTab[59] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_NUM", "s10"}};
	 actTab[60] = {{"TK_COLON", "s87"}};
	 actTab[61] = {{"TK_SEMI", "r15"}};
	 actTab[62] = {{"TK_BEGIN", "r13"}};
	 actTab[63] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s25"}, {"TK_NUM", "s10"}};
	 actTab[64] = {{"TK_END", "s89"}};
	 actTab[65] = {{"TK_ASSIGN", "r36"}, {"TK_LSQB", "s90"}};
	 actTab[66] = {{"TK_END", "r24"}, {"TK_SEMI", "s91"}};
	 actTab[67] = {{"TK_ASSIGN", "s92"}};
	 actTab[68] = {{"TK_ELSE", "r26"}, {"TK_END", "r26"}, {"TK_SEMI", "r26"}};
	 actTab[69] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s25"}, {"TK_NUM", "s10"}};
	 actTab[70] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s25"}, {"TK_NUM", "s10"}};
	 actTab[71] = {{"TK_ELSE", "r27"}, {"TK_END", "r27"}, {"TK_SEMI", "r27"}};
	 actTab[72] = {{"TK_ELSE", "r28"}, {"TK_END", "r28"}, {"TK_SEMI", "r28"}};
	 actTab[73] = {{"TK_ELSE", "r29"}, {"TK_END", "r29"}, {"TK_SEMI", "r29"}};
	 actTab[74] = {{"TK_ELSE", "r30"}, {"TK_END", "r30"}, {"TK_SEMI", "r30"}};
	 actTab[75] = {{"TK_ELSE", "r31"}, {"TK_END", "r31"}, {"TK_SEMI", "r31"}};
	 actTab[76] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s25"}, {"TK_NUM", "s10"}};
	 actTab[77] = {{"TK_END", "r21"}};
	 actTab[78] = {{"TK_EOI", "r4"}};
	 actTab[79] = {{"TK_BEGIN", "r3"}, {"TK_DEF", "r3"}, {"TK_EOI", "r3"}, {"TK_VAR", "r3"}};
	 actTab[80] = {{"TK_COMMA", "r40"}, {"TK_RPAREN", "r40"}};
	 actTab[81] = {{"TK_COMMA", "s96"}, {"TK_RPAREN", "s97"}};
	 actTab[82] = {{"TK_AND", "r45"}, {"TK_COMMA", "r45"}, {"TK_DIV", "r45"}, {"TK_DO", "r45"}, {"TK_ELSE", "r45"}, {"TK_END", "r45"}, {"TK_EQU", "r45"}, {"TK_GT", "r45"}, {"TK_LT", "r45"}, {"TK_MINUS", "r45"}, {"TK_MOD", "r45"}, {"TK_MUL", "r45"}, {"TK_NEQ", "r45"}, {"TK_OR", "r45"}, {"TK_PLUS", "r45"}, {"TK_RPAREN", "r45"}, {"TK_RSQB", "r45"}, {"TK_SEMI", "r45"}, {"TK_THEN", "r45"}};
	 actTab[83] = {{"TK_AND", "s40"}, {"TK_COMMA", "r43"}, {"TK_DIV", "s39"}, {"TK_DO", "r43"}, {"TK_ELSE", "r43"}, {"TK_END", "r43"}, {"TK_EQU", "r43"}, {"TK_GT", "r43"}, {"TK_LT", "r43"}, {"TK_MINUS", "r43"}, {"TK_MOD", "s38"}, {"TK_MUL", "s41"}, {"TK_NEQ", "r43"}, {"TK_OR", "r43"}, {"TK_PLUS", "r43"}, {"TK_RPAREN", "r43"}, {"TK_RSQB", "r43"}, {"TK_SEMI", "r43"}, {"TK_THEN", "r43"}};
	 actTab[84] = {{"TK_COMMA", "r41"}, {"TK_DO", "r41"}, {"TK_ELSE", "r41"}, {"TK_END", "r41"}, {"TK_MINUS", "s43"}, {"TK_OR", "s44"}, {"TK_PLUS", "s49"}, {"TK_RPAREN", "r41"}, {"TK_RSQB", "r41"}, {"TK_SEMI", "r41"}, {"TK_THEN", "r41"}};
	 actTab[85] = {{"TK_COLON", "s98"}};
	 actTab[86] = {{"TK_RPAREN", "s100"}, {"TK_SEMI", "s99"}};
	 actTab[87] = {{"TK_INTEGER", "s56"}, {"TK_REAL", "s55"}};
	 actTab[88] = {{"TK_ELSE", "r35"}, {"TK_END", "r35"}, {"TK_SEMI", "r35"}};
	 actTab[89] = {{"TK_ELSE", "r20"}, {"TK_END", "r20"}, {"TK_PERIOD", "r20"}, {"TK_SEMI", "r20"}};
	 actTab[90] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s25"}, {"TK_NUM", "s10"}};
	 actTab[91] = {{"TK_BEGIN", "s33"}, {"TK_ID", "s65"}, {"TK_IF", "s69"}, {"TK_PRINT", "s70"}, {"TK_RETURN", "s63"}, {"TK_WHILE", "s76"}};
	 actTab[92] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s25"}, {"TK_NUM", "s10"}};
	 actTab[93] = {{"TK_THEN", "s105"}};
	 actTab[94] = {{"TK_ELSE", "r34"}, {"TK_END", "r34"}, {"TK_SEMI", "r34"}};
	 actTab[95] = {{"TK_DO", "s106"}};
	 actTab[96] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s25"}, {"TK_NUM", "s10"}};
	 actTab[97] = {{"TK_AND", "r49"}, {"TK_COMMA", "r49"}, {"TK_DIV", "r49"}, {"TK_DO", "r49"}, {"TK_ELSE", "r49"}, {"TK_END", "r49"}, {"TK_EQU", "r49"}, {"TK_GT", "r49"}, {"TK_LT", "r49"}, {"TK_MINUS", "r49"}, {"TK_MOD", "r49"}, {"TK_MUL", "r49"}, {"TK_NEQ", "r49"}, {"TK_OR", "r49"}, {"TK_PLUS", "r49"}, {"TK_RPAREN", "r49"}, {"TK_RSQB", "r49"}, {"TK_SEMI", "r49"}, {"TK_THEN", "r49"}};
	 actTab[98] = {{"TK_INTEGER", "s56"}, {"TK_REAL", "s55"}};
	 actTab[99] = {{"TK_ID", "s11"}, {"TK_LPAREN", "s9"}, {"TK_NUM", "s10"}};
	 actTab[100] = {{"TK_COLON", "r17"}};
	 actTab[101] = {{"TK_SEMI", "s110"}};
	 actTab[102] = {{"TK_RSQB", "s111"}};
	 actTab[103] = {{"TK_END", "r23"}};
	 actTab[104] = {{"TK_ELSE", "r25"}, {"TK_END", "r25"}, {"TK_SEMI", "r25"}};
	 actTab[105] = {{"TK_BEGIN", "s33"}, {"TK_ID", "s65"}, {"TK_IF", "s69"}, {"TK_PRINT", "s70"}, {"TK_RETURN", "s63"}, {"TK_WHILE", "s76"}};
	 actTab[106] = {{"TK_BEGIN", "s33"}, {"TK_ID", "s65"}, {"TK_IF", "s69"}, {"TK_PRINT", "s70"}, {"TK_RETURN", "s63"}, {"TK_WHILE", "s76"}};
	 actTab[107] = {{"TK_COMMA", "r39"}, {"TK_RPAREN", "r39"}};
	 actTab[108] = {{"TK_RPAREN", "r19"}, {"TK_SEMI", "r19"}};
	 actTab[109] = {{"TK_COLON", "s114"}};
	 actTab[110] = {{"TK_BEGIN", "r16"}, {"TK_SEMI", "r16"}, {"TK_VAR", "r16"}};
	 actTab[111] = {{"TK_ASSIGN", "r37"}};
	 actTab[112] = {{"TK_ELSE", "s115"}};
	 actTab[113] = {{"TK_ELSE", "r33"}, {"TK_END", "r33"}, {"TK_SEMI", "r33"}};
	 actTab[114] = {{"TK_INTEGER", "s56"}, {"TK_REAL", "s55"}};
	 actTab[115] = {{"TK_BEGIN", "s33"}, {"TK_ID", "s65"}, {"TK_IF", "s69"}, {"TK_PRINT", "s70"}, {"TK_RETURN", "s63"}, {"TK_WHILE", "s76"}};
	 actTab[116] = {{"TK_RPAREN", "r18"}, {"TK_SEMI", "r18"}};
	 actTab[117] = {{"TK_ELSE", "r32"}, {"TK_END", "r32"}, {"TK_SEMI", "r32"}};
}
map<string, function<AST*(vector<AST*>&)>> actions;
void initActions() {
	 actions.insert({"binop",binop});
	 actions.insert({"mkBlock",mkBlock});
	 actions.insert({"mkCall",mkCall});
	 actions.insert({"mkFunc",mkFunc});
	 actions.insert({"mkFuncHeader",mkFuncHeader});
	 actions.insert({"mkId",mkId});
	 actions.insert({"mkIf",mkIf});
	 actions.insert({"mkLet",mkLet});
	 actions.insert({"mkList",mkList});
	 actions.insert({"mkNum",mkNum});
	 actions.insert({"mkPrint",mkPrint});
	 actions.insert({"mkRet",mkRet});
	 actions.insert({"mkSubscript",mkSubscript});
	 actions.insert({"mkWhile",mkWhile});
	 actions.insert({"pass",pass});
	 actions.insert({"unary",unary});
}
