r#include <vector>
#include <map>
#include <set>
#include "production.hpp"
using namespace std; 
enum NTSYMBOL {
AEXPR, BLESSEXPR, BLOCKSTMT, DECLLIST, DECLSTMT, 
DEFSTMT, EXPLIST, EXPSTMT, IFSTMT, LAMBDAEXPR, 
LAMBDAEXPRT, LETSTMT, LISTCON, PARAMLIST, PRI, 
PRINTSTMT, PROG, RETSTMT, STMT, STMTLIST, 
STRUCTSTMT, WHILESTMT, sp
};
map<int, Production> prod;
void initprod() {
	 prod[1]  = Production(1,"sp", SymbolString({"PROG"}),"");
	 prod[2]  = Production(2,"PROG", SymbolString({"STMTLIST"}),"");
	 prod[3]  = Production(3,"STMTLIST", SymbolString({"STMT","STMTLIST"}),"@mklist");
	 prod[4]  = Production(4,"STMTLIST", SymbolString({"STMT"}),"");
	 prod[5]  = Production(5,"STMT", SymbolString({"EXPSTMT"}),"");
	 prod[6]  = Production(6,"STMT", SymbolString({"IFSTMT"}),"");
	 prod[7]  = Production(7,"STMT", SymbolString({"WHILESTMT"}),"");
	 prod[8]  = Production(8,"STMT", SymbolString({"BLOCKSTMT"}),"");
	 prod[9]  = Production(9,"STMT", SymbolString({"PRINTSTMT"}),"");
	 prod[10]  = Production(10,"STMT", SymbolString({"LETSTMT"}),"");
	 prod[11]  = Production(11,"STMT", SymbolString({"DEFSTMT"}),"");
	 prod[12]  = Production(12,"STMT", SymbolString({"RETSTMT"}),"");
	 prod[13]  = Production(13,"STMT", SymbolString({"STRUCTSTMT"}),"");
	 prod[14]  = Production(14,"PARAMLIST", SymbolString({"DECLLIST"}),"");
	 prod[15]  = Production(15,"PARAMLIST", SymbolString(),"");
	 prod[16]  = Production(16,"DECLSTMT", SymbolString({"TK_LET","TK_ID"}),"@mklet");
	 prod[17]  = Production(17,"DECLLIST", SymbolString({"DECLSTMT","TK_COMMA","DECLLIST"}),"@mklist");
	 prod[18]  = Production(18,"DECLLIST", SymbolString({"DECLSTMT"}),"");
	 prod[19]  = Production(19,"LETSTMT", SymbolString({"TK_LET","AEXPR","TK_SEMI"}),"@mklet");
	 prod[20]  = Production(20,"PRINTSTMT", SymbolString({"TK_PRINT","AEXPR","TK_SEMI"}),"@mkprint");
	 prod[21]  = Production(21,"BLOCKSTMT", SymbolString({"TK_LCURLY","STMTLIST","TK_RCURLY"}),"@mkblock");
	 prod[22]  = Production(22,"IFSTMT", SymbolString({"TK_IF","TK_LPAREN","AEXPR","TK_RPAREN","BLOCKSTMT"}),"@mkif");
	 prod[23]  = Production(23,"WHILESTMT", SymbolString({"TK_WHILE","TK_LPAREN","AEXPR","TK_RPAREN","BLOCKSTMT"}),"@mkwhile");
	 prod[24]  = Production(24,"DEFSTMT", SymbolString({"TK_DEF","TK_ID","TK_LPAREN","PARAMLIST","TK_RPAREN","BLOCKSTMT"}),"@mkfunc");
	 prod[25]  = Production(25,"STRUCTSTMT", SymbolString({"TK_STRUCT","TK_ID","BLOCKSTMT","TK_SEMI"}),"@mkstruct");
	 prod[26]  = Production(26,"RETSTMT", SymbolString({"TK_RETURN","AEXPR","TK_SEMI"}),"@mkret");
	 prod[27]  = Production(27,"EXPSTMT", SymbolString({"AEXPR","TK_SEMI"}),"@mkexprstmt");
	 prod[28]  = Production(28,"AEXPR", SymbolString({"AEXPR","TK_ASSIGN","AEXPR"}),"@binop");
	 prod[29]  = Production(29,"AEXPR", SymbolString({"AEXPR","TK_EQU","AEXPR"}),"@binop");
	 prod[30]  = Production(30,"AEXPR", SymbolString({"AEXPR","TK_NEQ","AEXPR"}),"@binop");
	 prod[31]  = Production(31,"AEXPR", SymbolString({"AEXPR","TK_LT","AEXPR"}),"@binop");
	 prod[32]  = Production(32,"AEXPR", SymbolString({"AEXPR","TK_GT","AEXPR"}),"@binop");
	 prod[33]  = Production(33,"AEXPR", SymbolString({"AEXPR","TK_PLUS","AEXPR"}),"@binop");
	 prod[34]  = Production(34,"AEXPR", SymbolString({"AEXPR","TK_MINUS","AEXPR"}),"@binop");
	 prod[35]  = Production(35,"AEXPR", SymbolString({"AEXPR","TK_MUL","AEXPR"}),"@binop");
	 prod[36]  = Production(36,"AEXPR", SymbolString({"AEXPR","TK_DIV","AEXPR"}),"@binop");
	 prod[37]  = Production(37,"AEXPR", SymbolString({"TK_MINUS","AEXPR"}),"@unary");
	 prod[38]  = Production(38,"AEXPR", SymbolString({"AEXPR","TK_LSQB","PRI","TK_RSQB"}),"@mksubscript");
	 prod[39]  = Production(39,"AEXPR", SymbolString({"AEXPR","TK_LPAREN","EXPLIST","TK_RPAREN"}),"@mkcall");
	 prod[40]  = Production(40,"AEXPR", SymbolString({"PRI"}),"");
	 prod[41]  = Production(41,"PRI", SymbolString({"TK_LPAREN","AEXPR","TK_RPAREN"}),"@pass");
	 prod[42]  = Production(42,"PRI", SymbolString({"TK_NUM"}),"@num");
	 prod[43]  = Production(43,"PRI", SymbolString({"TK_ID"}),"@id");
	 prod[44]  = Production(44,"PRI", SymbolString({"TK_STRING"}),"@string");
	 prod[45]  = Production(45,"PRI", SymbolString({"LISTCON"}),"");
	 prod[46]  = Production(46,"PRI", SymbolString({"BLESSEXPR"}),"");
	 prod[47]  = Production(47,"PRI", SymbolString({"LAMBDAEXPR"}),"");
	 prod[48]  = Production(48,"EXPLIST", SymbolString({"AEXPR","TK_COMMA","EXPLIST"}),"@mklist");
	 prod[49]  = Production(49,"EXPLIST", SymbolString({"AEXPR"}),"");
	 prod[50]  = Production(50,"LISTCON", SymbolString({"TK_LSQB","EXPLIST","TK_RSQB"}),"@mklistcon");
	 prod[51]  = Production(51,"BLESSEXPR", SymbolString({"TK_NEW","TK_ID","TK_LPAREN","EXPLIST","TK_RPAREN"}),"@mkbless");
	 prod[52]  = Production(52,"LAMBDAEXPR", SymbolString({"TK_AMPER","TK_LPAREN","PARAMLIST","TK_RPAREN","LAMBDAEXPRT"}),"@mklambda");
	 prod[53]  = Production(53,"LAMBDAEXPRT", SymbolString({"BLOCKSTMT"}),"");
	 prod[54]  = Production(54,"LAMBDAEXPRT", SymbolString({"TK_PRODUCE","AEXPR"}),"");
}
map<int,map<string,string>> goTab;
void initgoTab() {
	 goTab[0] = {{"AEXPR", "17"}, {"BLESSEXPR", "18"}, {"BLOCKSTMT", "20"}, {"DEFSTMT", "26"}, {"EXPSTMT", "23"}, {"IFSTMT", "24"}, {"LAMBDAEXPR", "13"}, {"LETSTMT", "3"}, {"LISTCON", "14"}, {"PRI", "19"}, {"PRINTSTMT", "27"}, {"PROG", "1"}, {"RETSTMT", "16"}, {"STMT", "21"}, {"STMTLIST", "28"}, {"STRUCTSTMT", "30"}, {"WHILESTMT", "25"}};
	 goTab[6] = {{"AEXPR", "36"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[7] = {{"AEXPR", "37"}, {"BLESSEXPR", "18"}, {"EXPLIST", "38"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[10] = {{"AEXPR", "41"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[11] = {{"AEXPR", "42"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[21] = {{"AEXPR", "17"}, {"BLESSEXPR", "18"}, {"BLOCKSTMT", "20"}, {"DEFSTMT", "26"}, {"EXPSTMT", "23"}, {"IFSTMT", "24"}, {"LAMBDAEXPR", "13"}, {"LETSTMT", "3"}, {"LISTCON", "14"}, {"PRI", "19"}, {"PRINTSTMT", "27"}, {"RETSTMT", "16"}, {"STMT", "21"}, {"STMTLIST", "56"}, {"STRUCTSTMT", "30"}, {"WHILESTMT", "25"}};
	 goTab[22] = {{"AEXPR", "17"}, {"BLESSEXPR", "18"}, {"BLOCKSTMT", "20"}, {"DEFSTMT", "26"}, {"EXPSTMT", "23"}, {"IFSTMT", "24"}, {"LAMBDAEXPR", "13"}, {"LETSTMT", "3"}, {"LISTCON", "14"}, {"PRI", "19"}, {"PRINTSTMT", "27"}, {"RETSTMT", "16"}, {"STMT", "21"}, {"STMTLIST", "57"}, {"STRUCTSTMT", "30"}, {"WHILESTMT", "25"}};
	 goTab[29] = {{"AEXPR", "58"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[33] = {{"AEXPR", "60"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[34] = {{"AEXPR", "61"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[35] = {{"BLOCKSTMT", "62"}};
	 goTab[39] = {{"DECLLIST", "66"}, {"DECLSTMT", "65"}, {"PARAMLIST", "68"}};
	 goTab[44] = {{"AEXPR", "73"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[45] = {{"AEXPR", "74"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[46] = {{"AEXPR", "37"}, {"BLESSEXPR", "18"}, {"EXPLIST", "75"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[47] = {{"AEXPR", "76"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[48] = {{"AEXPR", "77"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[49] = {{"AEXPR", "78"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[50] = {{"AEXPR", "79"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[52] = {{"AEXPR", "80"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[53] = {{"AEXPR", "81"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[54] = {{"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "82"}};
	 goTab[55] = {{"AEXPR", "83"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[59] = {{"AEXPR", "86"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[63] = {{"AEXPR", "37"}, {"BLESSEXPR", "18"}, {"EXPLIST", "90"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[69] = {{"DECLLIST", "66"}, {"DECLSTMT", "65"}, {"PARAMLIST", "94"}};
	 goTab[72] = {{"AEXPR", "37"}, {"BLESSEXPR", "18"}, {"EXPLIST", "95"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[88] = {{"BLOCKSTMT", "99"}};
	 goTab[91] = {{"DECLLIST", "100"}, {"DECLSTMT", "65"}};
	 goTab[93] = {{"BLOCKSTMT", "102"}, {"LAMBDAEXPRT", "101"}};
	 goTab[98] = {{"BLOCKSTMT", "106"}};
	 goTab[103] = {{"AEXPR", "107"}, {"BLESSEXPR", "18"}, {"LAMBDAEXPR", "13"}, {"LISTCON", "14"}, {"PRI", "19"}};
	 goTab[104] = {{"BLOCKSTMT", "108"}};
}
map<int,map<string,string>> actTab;
void initactTab() {
	 actTab[0] = {{"TK_AMPER", "s8"}, {"TK_DEF", "s9"}, {"TK_ID", "s31"}, {"TK_IF", "s2"}, {"TK_LCURLY", "s22"}, {"TK_LET", "s29"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_PRINT", "s33"}, {"TK_RETURN", "s11"}, {"TK_STRING", "s12"}, {"TK_STRUCT", "s4"}, {"TK_WHILE", "s32"}};
	 actTab[1] = {{"$", "accept"}};
	 actTab[2] = {{"TK_LPAREN", "s34"}};
	 actTab[3] = {{"TK_AMPER", "r10"}, {"TK_DEF", "r10"}, {"TK_EOI", "r10"}, {"TK_ID", "r10"}, {"TK_IF", "r10"}, {"TK_LCURLY", "r10"}, {"TK_LET", "r10"}, {"TK_LPAREN", "r10"}, {"TK_LSQB", "r10"}, {"TK_MINUS", "r10"}, {"TK_NEW", "r10"}, {"TK_NUM", "r10"}, {"TK_PRINT", "r10"}, {"TK_RCURLY", "r10"}, {"TK_RETURN", "r10"}, {"TK_STRING", "r10"}, {"TK_STRUCT", "r10"}, {"TK_WHILE", "r10"}};
	 actTab[4] = {{"TK_ID", "s35"}};
	 actTab[5] = {{"TK_ASSIGN", "r42"}, {"TK_COMMA", "r42"}, {"TK_DIV", "r42"}, {"TK_EQU", "r42"}, {"TK_GT", "r42"}, {"TK_LPAREN", "r42"}, {"TK_LSQB", "r42"}, {"TK_LT", "r42"}, {"TK_MINUS", "r42"}, {"TK_MUL", "r42"}, {"TK_NEQ", "r42"}, {"TK_PLUS", "r42"}, {"TK_RPAREN", "r42"}, {"TK_RSQB", "r42"}, {"TK_SEMI", "r42"}};
	 actTab[6] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[7] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[8] = {{"TK_LPAREN", "s39"}};
	 actTab[9] = {{"TK_ID", "s40"}};
	 actTab[10] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[11] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[12] = {{"TK_ASSIGN", "r44"}, {"TK_COMMA", "r44"}, {"TK_DIV", "r44"}, {"TK_EQU", "r44"}, {"TK_GT", "r44"}, {"TK_LPAREN", "r44"}, {"TK_LSQB", "r44"}, {"TK_LT", "r44"}, {"TK_MINUS", "r44"}, {"TK_MUL", "r44"}, {"TK_NEQ", "r44"}, {"TK_PLUS", "r44"}, {"TK_RPAREN", "r44"}, {"TK_RSQB", "r44"}, {"TK_SEMI", "r44"}};
	 actTab[13] = {{"TK_ASSIGN", "r47"}, {"TK_COMMA", "r47"}, {"TK_DIV", "r47"}, {"TK_EQU", "r47"}, {"TK_GT", "r47"}, {"TK_LPAREN", "r47"}, {"TK_LSQB", "r47"}, {"TK_LT", "r47"}, {"TK_MINUS", "r47"}, {"TK_MUL", "r47"}, {"TK_NEQ", "r47"}, {"TK_PLUS", "r47"}, {"TK_RPAREN", "r47"}, {"TK_RSQB", "r47"}, {"TK_SEMI", "r47"}};
	 actTab[14] = {{"TK_ASSIGN", "r45"}, {"TK_COMMA", "r45"}, {"TK_DIV", "r45"}, {"TK_EQU", "r45"}, {"TK_GT", "r45"}, {"TK_LPAREN", "r45"}, {"TK_LSQB", "r45"}, {"TK_LT", "r45"}, {"TK_MINUS", "r45"}, {"TK_MUL", "r45"}, {"TK_NEQ", "r45"}, {"TK_PLUS", "r45"}, {"TK_RPAREN", "r45"}, {"TK_RSQB", "r45"}, {"TK_SEMI", "r45"}};
	 actTab[15] = {{"TK_ID", "s43"}};
	 actTab[16] = {{"TK_AMPER", "r12"}, {"TK_DEF", "r12"}, {"TK_EOI", "r12"}, {"TK_ID", "r12"}, {"TK_IF", "r12"}, {"TK_LCURLY", "r12"}, {"TK_LET", "r12"}, {"TK_LPAREN", "r12"}, {"TK_LSQB", "r12"}, {"TK_MINUS", "r12"}, {"TK_NEW", "r12"}, {"TK_NUM", "r12"}, {"TK_PRINT", "r12"}, {"TK_RCURLY", "r12"}, {"TK_RETURN", "r12"}, {"TK_STRING", "r12"}, {"TK_STRUCT", "r12"}, {"TK_WHILE", "r12"}};
	 actTab[17] = {{"TK_ASSIGN", "s48"}, {"TK_DIV", "s52"}, {"TK_EQU", "s45"}, {"TK_GT", "s49"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "s55"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "s44"}, {"TK_PLUS", "s53"}, {"TK_SEMI", "s51"}};
	 actTab[18] = {{"TK_ASSIGN", "r46"}, {"TK_COMMA", "r46"}, {"TK_DIV", "r46"}, {"TK_EQU", "r46"}, {"TK_GT", "r46"}, {"TK_LPAREN", "r46"}, {"TK_LSQB", "r46"}, {"TK_LT", "r46"}, {"TK_MINUS", "r46"}, {"TK_MUL", "r46"}, {"TK_NEQ", "r46"}, {"TK_PLUS", "r46"}, {"TK_RPAREN", "r46"}, {"TK_RSQB", "r46"}, {"TK_SEMI", "r46"}};
	 actTab[19] = {{"TK_ASSIGN", "r40"}, {"TK_COMMA", "r40"}, {"TK_DIV", "r40"}, {"TK_EQU", "r40"}, {"TK_GT", "r40"}, {"TK_LPAREN", "r40"}, {"TK_LSQB", "r40"}, {"TK_LT", "r40"}, {"TK_MINUS", "r40"}, {"TK_MUL", "r40"}, {"TK_NEQ", "r40"}, {"TK_PLUS", "r40"}, {"TK_RPAREN", "r40"}, {"TK_RSQB", "r40"}, {"TK_SEMI", "r40"}};
	 actTab[20] = {{"TK_AMPER", "r8"}, {"TK_DEF", "r8"}, {"TK_EOI", "r8"}, {"TK_ID", "r8"}, {"TK_IF", "r8"}, {"TK_LCURLY", "r8"}, {"TK_LET", "r8"}, {"TK_LPAREN", "r8"}, {"TK_LSQB", "r8"}, {"TK_MINUS", "r8"}, {"TK_NEW", "r8"}, {"TK_NUM", "r8"}, {"TK_PRINT", "r8"}, {"TK_RCURLY", "r8"}, {"TK_RETURN", "r8"}, {"TK_STRING", "r8"}, {"TK_STRUCT", "r8"}, {"TK_WHILE", "r8"}};
	 actTab[21] = {{"TK_AMPER", "s8"}, {"TK_DEF", "s9"}, {"TK_EOI", "r4"}, {"TK_ID", "s31"}, {"TK_IF", "s2"}, {"TK_LCURLY", "s22"}, {"TK_LET", "s29"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_PRINT", "s33"}, {"TK_RCURLY", "r4"}, {"TK_RETURN", "s11"}, {"TK_STRING", "s12"}, {"TK_STRUCT", "s4"}, {"TK_WHILE", "s32"}};
	 actTab[22] = {{"TK_AMPER", "s8"}, {"TK_DEF", "s9"}, {"TK_ID", "s31"}, {"TK_IF", "s2"}, {"TK_LCURLY", "s22"}, {"TK_LET", "s29"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_PRINT", "s33"}, {"TK_RETURN", "s11"}, {"TK_STRING", "s12"}, {"TK_STRUCT", "s4"}, {"TK_WHILE", "s32"}};
	 actTab[23] = {{"TK_AMPER", "r5"}, {"TK_DEF", "r5"}, {"TK_EOI", "r5"}, {"TK_ID", "r5"}, {"TK_IF", "r5"}, {"TK_LCURLY", "r5"}, {"TK_LET", "r5"}, {"TK_LPAREN", "r5"}, {"TK_LSQB", "r5"}, {"TK_MINUS", "r5"}, {"TK_NEW", "r5"}, {"TK_NUM", "r5"}, {"TK_PRINT", "r5"}, {"TK_RCURLY", "r5"}, {"TK_RETURN", "r5"}, {"TK_STRING", "r5"}, {"TK_STRUCT", "r5"}, {"TK_WHILE", "r5"}};
	 actTab[24] = {{"TK_AMPER", "r6"}, {"TK_DEF", "r6"}, {"TK_EOI", "r6"}, {"TK_ID", "r6"}, {"TK_IF", "r6"}, {"TK_LCURLY", "r6"}, {"TK_LET", "r6"}, {"TK_LPAREN", "r6"}, {"TK_LSQB", "r6"}, {"TK_MINUS", "r6"}, {"TK_NEW", "r6"}, {"TK_NUM", "r6"}, {"TK_PRINT", "r6"}, {"TK_RCURLY", "r6"}, {"TK_RETURN", "r6"}, {"TK_STRING", "r6"}, {"TK_STRUCT", "r6"}, {"TK_WHILE", "r6"}};
	 actTab[25] = {{"TK_AMPER", "r7"}, {"TK_DEF", "r7"}, {"TK_EOI", "r7"}, {"TK_ID", "r7"}, {"TK_IF", "r7"}, {"TK_LCURLY", "r7"}, {"TK_LET", "r7"}, {"TK_LPAREN", "r7"}, {"TK_LSQB", "r7"}, {"TK_MINUS", "r7"}, {"TK_NEW", "r7"}, {"TK_NUM", "r7"}, {"TK_PRINT", "r7"}, {"TK_RCURLY", "r7"}, {"TK_RETURN", "r7"}, {"TK_STRING", "r7"}, {"TK_STRUCT", "r7"}, {"TK_WHILE", "r7"}};
	 actTab[26] = {{"TK_AMPER", "r11"}, {"TK_DEF", "r11"}, {"TK_EOI", "r11"}, {"TK_ID", "r11"}, {"TK_IF", "r11"}, {"TK_LCURLY", "r11"}, {"TK_LET", "r11"}, {"TK_LPAREN", "r11"}, {"TK_LSQB", "r11"}, {"TK_MINUS", "r11"}, {"TK_NEW", "r11"}, {"TK_NUM", "r11"}, {"TK_PRINT", "r11"}, {"TK_RCURLY", "r11"}, {"TK_RETURN", "r11"}, {"TK_STRING", "r11"}, {"TK_STRUCT", "r11"}, {"TK_WHILE", "r11"}};
	 actTab[27] = {{"TK_AMPER", "r9"}, {"TK_DEF", "r9"}, {"TK_EOI", "r9"}, {"TK_ID", "r9"}, {"TK_IF", "r9"}, {"TK_LCURLY", "r9"}, {"TK_LET", "r9"}, {"TK_LPAREN", "r9"}, {"TK_LSQB", "r9"}, {"TK_MINUS", "r9"}, {"TK_NEW", "r9"}, {"TK_NUM", "r9"}, {"TK_PRINT", "r9"}, {"TK_RCURLY", "r9"}, {"TK_RETURN", "r9"}, {"TK_STRING", "r9"}, {"TK_STRUCT", "r9"}, {"TK_WHILE", "r9"}};
	 actTab[28] = {{"TK_EOI", "r2"}};
	 actTab[29] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[30] = {{"TK_AMPER", "r13"}, {"TK_DEF", "r13"}, {"TK_EOI", "r13"}, {"TK_ID", "r13"}, {"TK_IF", "r13"}, {"TK_LCURLY", "r13"}, {"TK_LET", "r13"}, {"TK_LPAREN", "r13"}, {"TK_LSQB", "r13"}, {"TK_MINUS", "r13"}, {"TK_NEW", "r13"}, {"TK_NUM", "r13"}, {"TK_PRINT", "r13"}, {"TK_RCURLY", "r13"}, {"TK_RETURN", "r13"}, {"TK_STRING", "r13"}, {"TK_STRUCT", "r13"}, {"TK_WHILE", "r13"}};
	 actTab[31] = {{"TK_ASSIGN", "r43"}, {"TK_COMMA", "r43"}, {"TK_DIV", "r43"}, {"TK_EQU", "r43"}, {"TK_GT", "r43"}, {"TK_LPAREN", "r43"}, {"TK_LSQB", "r43"}, {"TK_LT", "r43"}, {"TK_MINUS", "r43"}, {"TK_MUL", "r43"}, {"TK_NEQ", "r43"}, {"TK_PLUS", "r43"}, {"TK_RPAREN", "r43"}, {"TK_RSQB", "r43"}, {"TK_SEMI", "r43"}};
	 actTab[32] = {{"TK_LPAREN", "s59"}};
	 actTab[33] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[34] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[35] = {{"TK_LCURLY", "s22"}};
	 actTab[36] = {{"TK_ASSIGN", "r37"}, {"TK_COMMA", "r37"}, {"TK_DIV", "r37"}, {"TK_EQU", "r37"}, {"TK_GT", "r37"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "r37"}, {"TK_MINUS", "r37"}, {"TK_MUL", "r37"}, {"TK_NEQ", "r37"}, {"TK_PLUS", "r37"}, {"TK_RPAREN", "r37"}, {"TK_RSQB", "r37"}, {"TK_SEMI", "r37"}};
	 actTab[37] = {{"TK_ASSIGN", "s48"}, {"TK_COMMA", "s63"}, {"TK_DIV", "s52"}, {"TK_EQU", "s45"}, {"TK_GT", "s49"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "s55"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "s44"}, {"TK_PLUS", "s53"}, {"TK_RPAREN", "r49"}, {"TK_RSQB", "r49"}};
	 actTab[38] = {{"TK_RSQB", "s64"}};
	 actTab[39] = {{"TK_LET", "s67"}, {"TK_RPAREN", "r15"}};
	 actTab[40] = {{"TK_LPAREN", "s69"}};
	 actTab[41] = {{"TK_ASSIGN", "s48"}, {"TK_DIV", "s52"}, {"TK_EQU", "s45"}, {"TK_GT", "s49"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "s55"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "s44"}, {"TK_PLUS", "s53"}, {"TK_RPAREN", "s70"}};
	 actTab[42] = {{"TK_ASSIGN", "s48"}, {"TK_DIV", "s52"}, {"TK_EQU", "s45"}, {"TK_GT", "s49"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "s55"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "s44"}, {"TK_PLUS", "s53"}, {"TK_SEMI", "s71"}};
	 actTab[43] = {{"TK_LPAREN", "s72"}};
	 actTab[44] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[45] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[46] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[47] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[48] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[49] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[50] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[51] = {{"TK_AMPER", "r27"}, {"TK_DEF", "r27"}, {"TK_EOI", "r27"}, {"TK_ID", "r27"}, {"TK_IF", "r27"}, {"TK_LCURLY", "r27"}, {"TK_LET", "r27"}, {"TK_LPAREN", "r27"}, {"TK_LSQB", "r27"}, {"TK_MINUS", "r27"}, {"TK_NEW", "r27"}, {"TK_NUM", "r27"}, {"TK_PRINT", "r27"}, {"TK_RCURLY", "r27"}, {"TK_RETURN", "r27"}, {"TK_STRING", "r27"}, {"TK_STRUCT", "r27"}, {"TK_WHILE", "r27"}};
	 actTab[52] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[53] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[54] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[55] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[56] = {{"TK_EOI", "r3"}, {"TK_RCURLY", "r3"}};
	 actTab[57] = {{"TK_RCURLY", "s84"}};
	 actTab[58] = {{"TK_ASSIGN", "s48"}, {"TK_DIV", "s52"}, {"TK_EQU", "s45"}, {"TK_GT", "s49"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "s55"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "s44"}, {"TK_PLUS", "s53"}, {"TK_SEMI", "s85"}};
	 actTab[59] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[60] = {{"TK_ASSIGN", "s48"}, {"TK_DIV", "s52"}, {"TK_EQU", "s45"}, {"TK_GT", "s49"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "s55"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "s44"}, {"TK_PLUS", "s53"}, {"TK_SEMI", "s87"}};
	 actTab[61] = {{"TK_ASSIGN", "s48"}, {"TK_DIV", "s52"}, {"TK_EQU", "s45"}, {"TK_GT", "s49"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "s55"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "s44"}, {"TK_PLUS", "s53"}, {"TK_RPAREN", "s88"}};
	 actTab[62] = {{"TK_SEMI", "s89"}};
	 actTab[63] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[64] = {{"TK_ASSIGN", "r50"}, {"TK_COMMA", "r50"}, {"TK_DIV", "r50"}, {"TK_EQU", "r50"}, {"TK_GT", "r50"}, {"TK_LPAREN", "r50"}, {"TK_LSQB", "r50"}, {"TK_LT", "r50"}, {"TK_MINUS", "r50"}, {"TK_MUL", "r50"}, {"TK_NEQ", "r50"}, {"TK_PLUS", "r50"}, {"TK_RPAREN", "r50"}, {"TK_RSQB", "r50"}, {"TK_SEMI", "r50"}};
	 actTab[65] = {{"TK_COMMA", "s91"}, {"TK_RPAREN", "r18"}};
	 actTab[66] = {{"TK_RPAREN", "r14"}};
	 actTab[67] = {{"TK_ID", "s92"}};
	 actTab[68] = {{"TK_RPAREN", "s93"}};
	 actTab[69] = {{"TK_LET", "s67"}, {"TK_RPAREN", "r15"}};
	 actTab[70] = {{"TK_ASSIGN", "r41"}, {"TK_COMMA", "r41"}, {"TK_DIV", "r41"}, {"TK_EQU", "r41"}, {"TK_GT", "r41"}, {"TK_LPAREN", "r41"}, {"TK_LSQB", "r41"}, {"TK_LT", "r41"}, {"TK_MINUS", "r41"}, {"TK_MUL", "r41"}, {"TK_NEQ", "r41"}, {"TK_PLUS", "r41"}, {"TK_RPAREN", "r41"}, {"TK_RSQB", "r41"}, {"TK_SEMI", "r41"}};
	 actTab[71] = {{"TK_AMPER", "r26"}, {"TK_DEF", "r26"}, {"TK_EOI", "r26"}, {"TK_ID", "r26"}, {"TK_IF", "r26"}, {"TK_LCURLY", "r26"}, {"TK_LET", "r26"}, {"TK_LPAREN", "r26"}, {"TK_LSQB", "r26"}, {"TK_MINUS", "r26"}, {"TK_NEW", "r26"}, {"TK_NUM", "r26"}, {"TK_PRINT", "r26"}, {"TK_RCURLY", "r26"}, {"TK_RETURN", "r26"}, {"TK_STRING", "r26"}, {"TK_STRUCT", "r26"}, {"TK_WHILE", "r26"}};
	 actTab[72] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[73] = {{"TK_ASSIGN", "r30"}, {"TK_COMMA", "r30"}, {"TK_DIV", "s52"}, {"TK_EQU", "r30"}, {"TK_GT", "s49"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "s55"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "r30"}, {"TK_PLUS", "s53"}, {"TK_RPAREN", "r30"}, {"TK_RSQB", "r30"}, {"TK_SEMI", "r30"}};
	 actTab[74] = {{"TK_ASSIGN", "r29"}, {"TK_COMMA", "r29"}, {"TK_DIV", "s52"}, {"TK_EQU", "r29"}, {"TK_GT", "s49"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "s55"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "r29"}, {"TK_PLUS", "s53"}, {"TK_RPAREN", "r29"}, {"TK_RSQB", "r29"}, {"TK_SEMI", "r29"}};
	 actTab[75] = {{"TK_RPAREN", "s96"}};
	 actTab[76] = {{"TK_ASSIGN", "r35"}, {"TK_COMMA", "r35"}, {"TK_DIV", "r35"}, {"TK_EQU", "r35"}, {"TK_GT", "r35"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "r35"}, {"TK_MINUS", "r35"}, {"TK_MUL", "r35"}, {"TK_NEQ", "r35"}, {"TK_PLUS", "r35"}, {"TK_RPAREN", "r35"}, {"TK_RSQB", "r35"}, {"TK_SEMI", "r35"}};
	 actTab[77] = {{"TK_ASSIGN", "s48"}, {"TK_COMMA", "r28"}, {"TK_DIV", "s52"}, {"TK_EQU", "s45"}, {"TK_GT", "s49"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "s55"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "s44"}, {"TK_PLUS", "s53"}, {"TK_RPAREN", "r28"}, {"TK_RSQB", "r28"}, {"TK_SEMI", "r28"}};
	 actTab[78] = {{"TK_ASSIGN", "r32"}, {"TK_COMMA", "r32"}, {"TK_DIV", "s52"}, {"TK_EQU", "r32"}, {"TK_GT", "r32"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "r32"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "r32"}, {"TK_PLUS", "s53"}, {"TK_RPAREN", "r32"}, {"TK_RSQB", "r32"}, {"TK_SEMI", "r32"}};
	 actTab[79] = {{"TK_ASSIGN", "r34"}, {"TK_COMMA", "r34"}, {"TK_DIV", "s52"}, {"TK_EQU", "r34"}, {"TK_GT", "r34"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "r34"}, {"TK_MINUS", "r34"}, {"TK_MUL", "s47"}, {"TK_NEQ", "r34"}, {"TK_PLUS", "r34"}, {"TK_RPAREN", "r34"}, {"TK_RSQB", "r34"}, {"TK_SEMI", "r34"}};
	 actTab[80] = {{"TK_ASSIGN", "r36"}, {"TK_COMMA", "r36"}, {"TK_DIV", "r36"}, {"TK_EQU", "r36"}, {"TK_GT", "r36"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "r36"}, {"TK_MINUS", "r36"}, {"TK_MUL", "r36"}, {"TK_NEQ", "r36"}, {"TK_PLUS", "r36"}, {"TK_RPAREN", "r36"}, {"TK_RSQB", "r36"}, {"TK_SEMI", "r36"}};
	 actTab[81] = {{"TK_ASSIGN", "r33"}, {"TK_COMMA", "r33"}, {"TK_DIV", "s52"}, {"TK_EQU", "r33"}, {"TK_GT", "r33"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "r33"}, {"TK_MINUS", "r33"}, {"TK_MUL", "s47"}, {"TK_NEQ", "r33"}, {"TK_PLUS", "r33"}, {"TK_RPAREN", "r33"}, {"TK_RSQB", "r33"}, {"TK_SEMI", "r33"}};
	 actTab[82] = {{"TK_RSQB", "s97"}};
	 actTab[83] = {{"TK_ASSIGN", "r31"}, {"TK_COMMA", "r31"}, {"TK_DIV", "s52"}, {"TK_EQU", "r31"}, {"TK_GT", "r31"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "r31"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "r31"}, {"TK_PLUS", "s53"}, {"TK_RPAREN", "r31"}, {"TK_RSQB", "r31"}, {"TK_SEMI", "r31"}};
	 actTab[84] = {{"TK_AMPER", "r21"}, {"TK_ASSIGN", "r21"}, {"TK_COMMA", "r21"}, {"TK_DEF", "r21"}, {"TK_DIV", "r21"}, {"TK_EOI", "r21"}, {"TK_EQU", "r21"}, {"TK_GT", "r21"}, {"TK_ID", "r21"}, {"TK_IF", "r21"}, {"TK_LCURLY", "r21"}, {"TK_LET", "r21"}, {"TK_LPAREN", "r21"}, {"TK_LSQB", "r21"}, {"TK_LT", "r21"}, {"TK_MINUS", "r21"}, {"TK_MUL", "r21"}, {"TK_NEQ", "r21"}, {"TK_NEW", "r21"}, {"TK_NUM", "r21"}, {"TK_PLUS", "r21"}, {"TK_PRINT", "r21"}, {"TK_RCURLY", "r21"}, {"TK_RETURN", "r21"}, {"TK_RPAREN", "r21"}, {"TK_RSQB", "r21"}, {"TK_SEMI", "r21"}, {"TK_STRING", "r21"}, {"TK_STRUCT", "r21"}, {"TK_WHILE", "r21"}};
	 actTab[85] = {{"TK_AMPER", "r19"}, {"TK_DEF", "r19"}, {"TK_EOI", "r19"}, {"TK_ID", "r19"}, {"TK_IF", "r19"}, {"TK_LCURLY", "r19"}, {"TK_LET", "r19"}, {"TK_LPAREN", "r19"}, {"TK_LSQB", "r19"}, {"TK_MINUS", "r19"}, {"TK_NEW", "r19"}, {"TK_NUM", "r19"}, {"TK_PRINT", "r19"}, {"TK_RCURLY", "r19"}, {"TK_RETURN", "r19"}, {"TK_STRING", "r19"}, {"TK_STRUCT", "r19"}, {"TK_WHILE", "r19"}};
	 actTab[86] = {{"TK_ASSIGN", "s48"}, {"TK_DIV", "s52"}, {"TK_EQU", "s45"}, {"TK_GT", "s49"}, {"TK_LPAREN", "s46"}, {"TK_LSQB", "s54"}, {"TK_LT", "s55"}, {"TK_MINUS", "s50"}, {"TK_MUL", "s47"}, {"TK_NEQ", "s44"}, {"TK_PLUS", "s53"}, {"TK_RPAREN", "s98"}};
	 actTab[87] = {{"TK_AMPER", "r20"}, {"TK_DEF", "r20"}, {"TK_EOI", "r20"}, {"TK_ID", "r20"}, {"TK_IF", "r20"}, {"TK_LCURLY", "r20"}, {"TK_LET", "r20"}, {"TK_LPAREN", "r20"}, {"TK_LSQB", "r20"}, {"TK_MINUS", "r20"}, {"TK_NEW", "r20"}, {"TK_NUM", "r20"}, {"TK_PRINT", "r20"}, {"TK_RCURLY", "r20"}, {"TK_RETURN", "r20"}, {"TK_STRING", "r20"}, {"TK_STRUCT", "r20"}, {"TK_WHILE", "r20"}};
	 actTab[88] = {{"TK_LCURLY", "s22"}};
	 actTab[89] = {{"TK_AMPER", "r25"}, {"TK_DEF", "r25"}, {"TK_EOI", "r25"}, {"TK_ID", "r25"}, {"TK_IF", "r25"}, {"TK_LCURLY", "r25"}, {"TK_LET", "r25"}, {"TK_LPAREN", "r25"}, {"TK_LSQB", "r25"}, {"TK_MINUS", "r25"}, {"TK_NEW", "r25"}, {"TK_NUM", "r25"}, {"TK_PRINT", "r25"}, {"TK_RCURLY", "r25"}, {"TK_RETURN", "r25"}, {"TK_STRING", "r25"}, {"TK_STRUCT", "r25"}, {"TK_WHILE", "r25"}};
	 actTab[90] = {{"TK_RPAREN", "r48"}, {"TK_RSQB", "r48"}};
	 actTab[91] = {{"TK_LET", "s67"}};
	 actTab[92] = {{"TK_COMMA", "r16"}, {"TK_RPAREN", "r16"}};
	 actTab[93] = {{"TK_LCURLY", "s22"}, {"TK_PRODUCE", "s103"}};
	 actTab[94] = {{"TK_RPAREN", "s104"}};
	 actTab[95] = {{"TK_RPAREN", "s105"}};
	 actTab[96] = {{"TK_ASSIGN", "r39"}, {"TK_COMMA", "r39"}, {"TK_DIV", "r39"}, {"TK_EQU", "r39"}, {"TK_GT", "r39"}, {"TK_LPAREN", "r39"}, {"TK_LSQB", "r39"}, {"TK_LT", "r39"}, {"TK_MINUS", "r39"}, {"TK_MUL", "r39"}, {"TK_NEQ", "r39"}, {"TK_PLUS", "r39"}, {"TK_RPAREN", "r39"}, {"TK_RSQB", "r39"}, {"TK_SEMI", "r39"}};
	 actTab[97] = {{"TK_ASSIGN", "r38"}, {"TK_COMMA", "r38"}, {"TK_DIV", "r38"}, {"TK_EQU", "r38"}, {"TK_GT", "r38"}, {"TK_LPAREN", "r38"}, {"TK_LSQB", "r38"}, {"TK_LT", "r38"}, {"TK_MINUS", "r38"}, {"TK_MUL", "r38"}, {"TK_NEQ", "r38"}, {"TK_PLUS", "r38"}, {"TK_RPAREN", "r38"}, {"TK_RSQB", "r38"}, {"TK_SEMI", "r38"}};
	 actTab[98] = {{"TK_LCURLY", "s22"}};
	 actTab[99] = {{"TK_AMPER", "r22"}, {"TK_DEF", "r22"}, {"TK_EOI", "r22"}, {"TK_ID", "r22"}, {"TK_IF", "r22"}, {"TK_LCURLY", "r22"}, {"TK_LET", "r22"}, {"TK_LPAREN", "r22"}, {"TK_LSQB", "r22"}, {"TK_MINUS", "r22"}, {"TK_NEW", "r22"}, {"TK_NUM", "r22"}, {"TK_PRINT", "r22"}, {"TK_RCURLY", "r22"}, {"TK_RETURN", "r22"}, {"TK_STRING", "r22"}, {"TK_STRUCT", "r22"}, {"TK_WHILE", "r22"}};
	 actTab[100] = {{"TK_RPAREN", "r17"}};
	 actTab[101] = {{"TK_ASSIGN", "r52"}, {"TK_COMMA", "r52"}, {"TK_DIV", "r52"}, {"TK_EQU", "r52"}, {"TK_GT", "r52"}, {"TK_LPAREN", "r52"}, {"TK_LSQB", "r52"}, {"TK_LT", "r52"}, {"TK_MINUS", "r52"}, {"TK_MUL", "r52"}, {"TK_NEQ", "r52"}, {"TK_PLUS", "r52"}, {"TK_RPAREN", "r52"}, {"TK_RSQB", "r52"}, {"TK_SEMI", "r52"}};
	 actTab[102] = {{"TK_ASSIGN", "r53"}, {"TK_COMMA", "r53"}, {"TK_DIV", "r53"}, {"TK_EQU", "r53"}, {"TK_GT", "r53"}, {"TK_LPAREN", "r53"}, {"TK_LSQB", "r53"}, {"TK_LT", "r53"}, {"TK_MINUS", "r53"}, {"TK_MUL", "r53"}, {"TK_NEQ", "r53"}, {"TK_PLUS", "r53"}, {"TK_RPAREN", "r53"}, {"TK_RSQB", "r53"}, {"TK_SEMI", "r53"}};
	 actTab[103] = {{"TK_AMPER", "s8"}, {"TK_ID", "s31"}, {"TK_LPAREN", "s10"}, {"TK_LSQB", "s7"}, {"TK_MINUS", "s6"}, {"TK_NEW", "s15"}, {"TK_NUM", "s5"}, {"TK_STRING", "s12"}};
	 actTab[104] = {{"TK_LCURLY", "s22"}};
	 actTab[105] = {{"TK_ASSIGN", "r51"}, {"TK_COMMA", "r51"}, {"TK_DIV", "r51"}, {"TK_EQU", "r51"}, {"TK_GT", "r51"}, {"TK_LPAREN", "r51"}, {"TK_LSQB", "r51"}, {"TK_LT", "r51"}, {"TK_MINUS", "r51"}, {"TK_MUL", "r51"}, {"TK_NEQ", "r51"}, {"TK_PLUS", "r51"}, {"TK_RPAREN", "r51"}, {"TK_RSQB", "r51"}, {"TK_SEMI", "r51"}};
	 actTab[106] = {{"TK_AMPER", "r23"}, {"TK_DEF", "r23"}, {"TK_EOI", "r23"}, {"TK_ID", "r23"}, {"TK_IF", "r23"}, {"TK_LCURLY", "r23"}, {"TK_LET", "r23"}, {"TK_LPAREN", "r23"}, {"TK_LSQB", "r23"}, {"TK_MINUS", "r23"}, {"TK_NEW", "r23"}, {"TK_NUM", "r23"}, {"TK_PRINT", "r23"}, {"TK_RCURLY", "r23"}, {"TK_RETURN", "r23"}, {"TK_STRING", "r23"}, {"TK_STRUCT", "r23"}, {"TK_WHILE", "r23"}};
	 actTab[107] = {{"TK_ASSIGN", "r54"}, {"TK_COMMA", "r54"}, {"TK_DIV", "r54"}, {"TK_EQU", "r54"}, {"TK_GT", "r54"}, {"TK_LPAREN", "r54"}, {"TK_LSQB", "r54"}, {"TK_LT", "r54"}, {"TK_MINUS", "r54"}, {"TK_MUL", "r54"}, {"TK_NEQ", "r54"}, {"TK_PLUS", "r54"}, {"TK_RPAREN", "r54"}, {"TK_RSQB", "r54"}, {"TK_SEMI", "r54"}};
	 actTab[108] = {{"TK_AMPER", "r24"}, {"TK_DEF", "r24"}, {"TK_EOI", "r24"}, {"TK_ID", "r24"}, {"TK_IF", "r24"}, {"TK_LCURLY", "r24"}, {"TK_LET", "r24"}, {"TK_LPAREN", "r24"}, {"TK_LSQB", "r24"}, {"TK_MINUS", "r24"}, {"TK_NEW", "r24"}, {"TK_NUM", "r24"}, {"TK_PRINT", "r24"}, {"TK_RCURLY", "r24"}, {"TK_RETURN", "r24"}, {"TK_STRING", "r24"}, {"TK_STRUCT", "r24"}, {"TK_WHILE", "r24"}};
}
