#include <vector>
#include <map>
#include <set>
#include <functional>
#include "production.hpp"
using namespace std; 
enum NTSYMBOL {
ADDOP, AEXPR, ARGLIST, ASSIGNSTMT, COMPOUNDSTMT, 
DECLLIST, DECLSTMT, EXPR, EXPRLIST, FACT, 
IDENTLIST, IFSTMT, MULOP, OPTSTMT, PARAMLIST, 
POST, PRI, PRINTSTMT, PROCSTMT, PROCTSMT, 
PROG, PROGHEADER, PROGT, RELOP, RETSTMT, 
SIMPEXPR, STANDTYPE, STMT, STMTLIST, SUBDECL, 
SUBDECLLIST, SUBHEAD, TERM, TYPE, WHILESTMT, 
sp
};
map<int, Production> prod;
void initprod() {
	 prod[1]  = Production(1,"sp", SymbolString({"PROG"}),"");
	 prod[2]  = Production(2,"PROG", SymbolString({"PROGHEADER","DECLLIST","SUBDECLLIST","PROGT"}),"@mkProgram");
	 prod[3]  = Production(3,"PROGHEADER", SymbolString({"TK_PROGRAM","TK_ID","TK_LPAREN","IDENTLIST","TK_RPAREN","TK_SEMI"}),"@mkProgramHeader");
	 prod[4]  = Production(4,"PROGT", SymbolString({"COMPOUNDSTMT","TK_PERIOD"}),"@through");
	 prod[5]  = Production(5,"IDENTLIST", SymbolString({"IDENTLIST","TK_COMMA","PRI"}),"@mkList");
	 prod[6]  = Production(6,"IDENTLIST", SymbolString({"PRI"}),"");
	 prod[7]  = Production(7,"DECLLIST", SymbolString({"DECLSTMT","TK_SEMI","DECLLIST"}),"@mkList");
	 prod[8]  = Production(8,"DECLLIST", SymbolString(),"");
	 prod[9]  = Production(9,"DECLSTMT", SymbolString({"TK_VAR","IDENTLIST","TK_COLON","TYPE"}),"@mkLet");
	 prod[10]  = Production(10,"TYPE", SymbolString({"STANDTYPE"}),"");
	 prod[11]  = Production(11,"TYPE", SymbolString({"TK_ARRAY","TK_LSQB","EXPR","TK_RANGE","EXPR","TK_RSQB","TK_OF","STANDTYPE"}),"@mkArray");
	 prod[12]  = Production(12,"STANDTYPE", SymbolString({"TK_INTEGER"}),"");
	 prod[13]  = Production(13,"STANDTYPE", SymbolString({"TK_REAL"}),"");
	 prod[14]  = Production(14,"STANDTYPE", SymbolString({"TK_STRING"}),"");
	 prod[15]  = Production(15,"SUBDECLLIST", SymbolString({"SUBDECL","TK_SEMI","SUBDECLLIST"}),"@mkList");
	 prod[16]  = Production(16,"SUBDECLLIST", SymbolString(),"");
	 prod[17]  = Production(17,"SUBDECL", SymbolString({"SUBHEAD","DECLLIST","COMPOUNDSTMT"}),"@mkFunc");
	 prod[18]  = Production(18,"SUBHEAD", SymbolString({"TK_DEF","TK_ID","ARGLIST","TK_COLON","TYPE","TK_SEMI"}),"@mkFuncHeader");
	 prod[19]  = Production(19,"ARGLIST", SymbolString({"TK_LPAREN","PARAMLIST","TK_RPAREN"}),"@pass");
	 prod[20]  = Production(20,"PARAMLIST", SymbolString({"PARAMLIST","TK_SEMI","IDENTLIST","TK_COLON","TYPE"}),"@mkList");
	 prod[21]  = Production(21,"PARAMLIST", SymbolString({"IDENTLIST","TK_COLON","TYPE"}),"");
	 prod[22]  = Production(22,"COMPOUNDSTMT", SymbolString({"TK_BEGIN","OPTSTMT","TK_END"}),"@mkBlock");
	 prod[23]  = Production(23,"OPTSTMT", SymbolString({"STMTLIST"}),"");
	 prod[24]  = Production(24,"OPTSTMT", SymbolString(),"");
	 prod[25]  = Production(25,"STMTLIST", SymbolString({"STMTLIST","TK_SEMI","STMT"}),"@mkList");
	 prod[26]  = Production(26,"STMTLIST", SymbolString({"STMT"}),"");
	 prod[27]  = Production(27,"STMT", SymbolString({"ASSIGNSTMT"}),"");
	 prod[28]  = Production(28,"STMT", SymbolString({"PROCSTMT"}),"");
	 prod[29]  = Production(29,"STMT", SymbolString({"COMPOUNDSTMT"}),"");
	 prod[30]  = Production(30,"STMT", SymbolString({"IFSTMT"}),"");
	 prod[31]  = Production(31,"STMT", SymbolString({"WHILESTMT"}),"");
	 prod[32]  = Production(32,"STMT", SymbolString({"PRINTSTMT"}),"");
	 prod[33]  = Production(33,"STMT", SymbolString({"RETSTMT"}),"");
	 prod[34]  = Production(34,"ASSIGNSTMT", SymbolString({"AEXPR"}),"");
	 prod[35]  = Production(35,"IFSTMT", SymbolString({"TK_IF","EXPR","TK_THEN","STMT","TK_ELSE","STMT"}),"@mkIf");
	 prod[36]  = Production(36,"WHILESTMT", SymbolString({"TK_WHILE","EXPR","TK_DO","STMT"}),"@mkWhile");
	 prod[37]  = Production(37,"PRINTSTMT", SymbolString({"TK_PRINT","EXPR"}),"@mkPrint");
	 prod[38]  = Production(38,"RETSTMT", SymbolString({"TK_RETURN","EXPR"}),"@mkRet");
	 prod[39]  = Production(39,"PROCTSMT", SymbolString({"TK_ID","TK_LPAREN","EXPRLIST","TK_RPAREN"}),"@mkCall");
	 prod[40]  = Production(40,"EXPRLIST", SymbolString({"EXPRLIST","TK_COMMA","EXPR"}),"@mkList");
	 prod[41]  = Production(41,"EXPRLIST", SymbolString({"EXPR"}),"");
	 prod[42]  = Production(42,"AEXPR", SymbolString({"EXPR","TK_ASSIGN","EXPR"}),"@binop");
	 prod[43]  = Production(43,"AEXPR", SymbolString({"EXPR"}),"");
	 prod[44]  = Production(44,"EXPR", SymbolString({"SIMPEXPR","RELOP","SIMPEXPR"}),"@binop");
	 prod[45]  = Production(45,"EXPR", SymbolString({"SIMPEXPR"}),"");
	 prod[46]  = Production(46,"SIMPEXPR", SymbolString({"SIMPEXPR","ADDOP","TERM"}),"@binop");
	 prod[47]  = Production(47,"SIMPEXPR", SymbolString({"TERM"}),"");
	 prod[48]  = Production(48,"TERM", SymbolString({"TERM","MULOP","FACT"}),"@binop");
	 prod[49]  = Production(49,"TERM", SymbolString({"FACT"}),"");
	 prod[50]  = Production(50,"FACT", SymbolString({"TK_MINUS","POST"}),"@unary");
	 prod[51]  = Production(51,"FACT", SymbolString({"POST"}),"");
	 prod[52]  = Production(52,"POST", SymbolString({"PRI","TK_LPAREN","EXPRLIST","TK_RPAREN"}),"@mkCall");
	 prod[53]  = Production(53,"POST", SymbolString({"PRI"}),"");
	 prod[54]  = Production(54,"PRI", SymbolString({"TK_ID"}),"@mkId");
	 prod[55]  = Production(55,"PRI", SymbolString({"TK_NUM"}),"@mkNum");
	 prod[56]  = Production(56,"PRI", SymbolString({"TK_STRING"}),"@mkString");
	 prod[57]  = Production(57,"PRI", SymbolString({"TK_LPAREN","EXPR","TK_RPAREN"}),"@pass");
	 prod[58]  = Production(58,"RELOP", SymbolString({"TK_LT"}),"");
	 prod[59]  = Production(59,"RELOP", SymbolString({"TK_GT"}),"");
	 prod[60]  = Production(60,"RELOP", SymbolString({"TK_EQU"}),"");
	 prod[61]  = Production(61,"RELOP", SymbolString({"TK_NEQ"}),"");
	 prod[62]  = Production(62,"ADDOP", SymbolString({"TK_PLUS"}),"");
	 prod[63]  = Production(63,"ADDOP", SymbolString({"TK_MINUS"}),"");
	 prod[64]  = Production(64,"ADDOP", SymbolString({"TK_OR"}),"");
	 prod[65]  = Production(65,"MULOP", SymbolString({"TK_MUL"}),"");
	 prod[66]  = Production(66,"MULOP", SymbolString({"TK_DIV"}),"");
	 prod[67]  = Production(67,"MULOP", SymbolString({"TK_MOD"}),"");
	 prod[68]  = Production(68,"MULOP", SymbolString({"TK_AND"}),"");
}
map<int,map<string,string>> goTab;
void initgoTab() {
	 goTab[0] = {{"PROG", "3"}, {"PROGHEADER", "2"}};
	 goTab[2] = {{"DECLLIST", "7"}, {"DECLSTMT", "6"}};
	 goTab[5] = {{"IDENTLIST", "14"}, {"PRI", "13"}};
	 goTab[7] = {{"SUBDECL", "18"}, {"SUBDECLLIST", "19"}, {"SUBHEAD", "17"}};
	 goTab[8] = {{"IDENTLIST", "20"}, {"PRI", "13"}};
	 goTab[9] = {{"EXPR", "27"}, {"FACT", "23"}, {"POST", "22"}, {"PRI", "21"}, {"SIMPEXPR", "25"}, {"TERM", "24"}};
	 goTab[15] = {{"DECLLIST", "30"}, {"DECLSTMT", "6"}};
	 goTab[17] = {{"DECLLIST", "32"}, {"DECLSTMT", "6"}};
	 goTab[19] = {{"COMPOUNDSTMT", "35"}, {"PROGT", "36"}};
	 goTab[24] = {{"MULOP", "43"}};
	 goTab[25] = {{"ADDOP", "51"}, {"RELOP", "52"}};
	 goTab[26] = {{"POST", "53"}, {"PRI", "21"}};
	 goTab[28] = {{"PRI", "55"}};
	 goTab[29] = {{"STANDTYPE", "60"}, {"TYPE", "61"}};
	 goTab[31] = {{"ARGLIST", "63"}};
	 goTab[32] = {{"COMPOUNDSTMT", "64"}};
	 goTab[33] = {{"SUBDECL", "18"}, {"SUBDECLLIST", "65"}, {"SUBHEAD", "17"}};
	 goTab[34] = {{"AEXPR", "69"}, {"ASSIGNSTMT", "68"}, {"COMPOUNDSTMT", "75"}, {"EXPR", "72"}, {"FACT", "23"}, {"IFSTMT", "76"}, {"OPTSTMT", "67"}, {"POST", "22"}, {"PRI", "21"}, {"PRINTSTMT", "78"}, {"PROCSTMT", "71"}, {"RETSTMT", "79"}, {"SIMPEXPR", "25"}, {"STMT", "70"}, {"STMTLIST", "81"}, {"TERM", "24"}, {"WHILESTMT", "77"}};
	 goTab[38] = {{"EXPR", "84"}, {"EXPRLIST", "85"}, {"FACT", "23"}, {"POST", "22"}, {"PRI", "21"}, {"SIMPEXPR", "25"}, {"TERM", "24"}};
	 goTab[43] = {{"FACT", "86"}, {"POST", "22"}, {"PRI", "21"}};
	 goTab[51] = {{"FACT", "23"}, {"POST", "22"}, {"PRI", "21"}, {"TERM", "87"}};
	 goTab[52] = {{"FACT", "23"}, {"POST", "22"}, {"PRI", "21"}, {"SIMPEXPR", "88"}, {"TERM", "24"}};
	 goTab[62] = {{"IDENTLIST", "90"}, {"PARAMLIST", "91"}, {"PRI", "13"}};
	 goTab[66] = {{"EXPR", "93"}, {"FACT", "23"}, {"POST", "22"}, {"PRI", "21"}, {"SIMPEXPR", "25"}, {"TERM", "24"}};
	 goTab[73] = {{"EXPR", "96"}, {"FACT", "23"}, {"POST", "22"}, {"PRI", "21"}, {"SIMPEXPR", "25"}, {"TERM", "24"}};
	 goTab[74] = {{"EXPR", "97"}, {"FACT", "23"}, {"POST", "22"}, {"PRI", "21"}, {"SIMPEXPR", "25"}, {"TERM", "24"}};
	 goTab[80] = {{"EXPR", "98"}, {"FACT", "23"}, {"POST", "22"}, {"PRI", "21"}, {"SIMPEXPR", "25"}, {"TERM", "24"}};
	 goTab[87] = {{"MULOP", "43"}};
	 goTab[88] = {{"ADDOP", "51"}};
	 goTab[89] = {{"EXPR", "102"}, {"FACT", "23"}, {"POST", "22"}, {"PRI", "21"}, {"SIMPEXPR", "25"}, {"TERM", "24"}};
	 goTab[92] = {{"STANDTYPE", "60"}, {"TYPE", "106"}};
	 goTab[95] = {{"EXPR", "107"}, {"FACT", "23"}, {"POST", "22"}, {"PRI", "21"}, {"SIMPEXPR", "25"}, {"TERM", "24"}};
	 goTab[99] = {{"AEXPR", "69"}, {"ASSIGNSTMT", "68"}, {"COMPOUNDSTMT", "75"}, {"EXPR", "72"}, {"FACT", "23"}, {"IFSTMT", "76"}, {"POST", "22"}, {"PRI", "21"}, {"PRINTSTMT", "78"}, {"PROCSTMT", "71"}, {"RETSTMT", "79"}, {"SIMPEXPR", "25"}, {"STMT", "110"}, {"TERM", "24"}, {"WHILESTMT", "77"}};
	 goTab[100] = {{"EXPR", "111"}, {"FACT", "23"}, {"POST", "22"}, {"PRI", "21"}, {"SIMPEXPR", "25"}, {"TERM", "24"}};
	 goTab[103] = {{"STANDTYPE", "60"}, {"TYPE", "113"}};
	 goTab[104] = {{"IDENTLIST", "114"}, {"PRI", "13"}};
	 goTab[108] = {{"AEXPR", "69"}, {"ASSIGNSTMT", "68"}, {"COMPOUNDSTMT", "75"}, {"EXPR", "72"}, {"FACT", "23"}, {"IFSTMT", "76"}, {"POST", "22"}, {"PRI", "21"}, {"PRINTSTMT", "78"}, {"PROCSTMT", "71"}, {"RETSTMT", "79"}, {"SIMPEXPR", "25"}, {"STMT", "116"}, {"TERM", "24"}, {"WHILESTMT", "77"}};
	 goTab[109] = {{"AEXPR", "69"}, {"ASSIGNSTMT", "68"}, {"COMPOUNDSTMT", "75"}, {"EXPR", "72"}, {"FACT", "23"}, {"IFSTMT", "76"}, {"POST", "22"}, {"PRI", "21"}, {"PRINTSTMT", "78"}, {"PROCSTMT", "71"}, {"RETSTMT", "79"}, {"SIMPEXPR", "25"}, {"STMT", "117"}, {"TERM", "24"}, {"WHILESTMT", "77"}};
	 goTab[112] = {{"EXPR", "118"}, {"FACT", "23"}, {"POST", "22"}, {"PRI", "21"}, {"SIMPEXPR", "25"}, {"TERM", "24"}};
	 goTab[119] = {{"STANDTYPE", "60"}, {"TYPE", "122"}};
	 goTab[120] = {{"AEXPR", "69"}, {"ASSIGNSTMT", "68"}, {"COMPOUNDSTMT", "75"}, {"EXPR", "72"}, {"FACT", "23"}, {"IFSTMT", "76"}, {"POST", "22"}, {"PRI", "21"}, {"PRINTSTMT", "78"}, {"PROCSTMT", "71"}, {"RETSTMT", "79"}, {"SIMPEXPR", "25"}, {"STMT", "123"}, {"TERM", "24"}, {"WHILESTMT", "77"}};
	 goTab[124] = {{"STANDTYPE", "125"}};
}
map<int,map<string,string>> actTab;
void initactTab() {
	 actTab[0] = {{"TK_PROGRAM", "s1"}};
	 actTab[1] = {{"TK_ID", "s4"}};
	 actTab[2] = {{"TK_BEGIN", "r8"}, {"TK_DEF", "r8"}, {"TK_EOI", "r8"}, {"TK_VAR", "s5"}};
	 actTab[3] = {{"$", "accept"}};
	 actTab[4] = {{"TK_LPAREN", "s8"}};
	 actTab[5] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[6] = {{"TK_SEMI", "s15"}};
	 actTab[7] = {{"TK_BEGIN", "r16"}, {"TK_DEF", "s16"}};
	 actTab[8] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[9] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[10] = {{"TK_AND", "r56"}, {"TK_ASSIGN", "r56"}, {"TK_COLON", "r56"}, {"TK_COMMA", "r56"}, {"TK_DIV", "r56"}, {"TK_DO", "r56"}, {"TK_ELSE", "r56"}, {"TK_END", "r56"}, {"TK_EQU", "r56"}, {"TK_GT", "r56"}, {"TK_LPAREN", "r56"}, {"TK_LT", "r56"}, {"TK_MINUS", "r56"}, {"TK_MOD", "r56"}, {"TK_MUL", "r56"}, {"TK_NEQ", "r56"}, {"TK_OR", "r56"}, {"TK_PLUS", "r56"}, {"TK_RANGE", "r56"}, {"TK_RPAREN", "r56"}, {"TK_RSQB", "r56"}, {"TK_SEMI", "r56"}, {"TK_THEN", "r56"}};
	 actTab[11] = {{"TK_AND", "r55"}, {"TK_ASSIGN", "r55"}, {"TK_COLON", "r55"}, {"TK_COMMA", "r55"}, {"TK_DIV", "r55"}, {"TK_DO", "r55"}, {"TK_ELSE", "r55"}, {"TK_END", "r55"}, {"TK_EQU", "r55"}, {"TK_GT", "r55"}, {"TK_LPAREN", "r55"}, {"TK_LT", "r55"}, {"TK_MINUS", "r55"}, {"TK_MOD", "r55"}, {"TK_MUL", "r55"}, {"TK_NEQ", "r55"}, {"TK_OR", "r55"}, {"TK_PLUS", "r55"}, {"TK_RANGE", "r55"}, {"TK_RPAREN", "r55"}, {"TK_RSQB", "r55"}, {"TK_SEMI", "r55"}, {"TK_THEN", "r55"}};
	 actTab[12] = {{"TK_AND", "r54"}, {"TK_ASSIGN", "r54"}, {"TK_COLON", "r54"}, {"TK_COMMA", "r54"}, {"TK_DIV", "r54"}, {"TK_DO", "r54"}, {"TK_ELSE", "r54"}, {"TK_END", "r54"}, {"TK_EQU", "r54"}, {"TK_GT", "r54"}, {"TK_LPAREN", "r54"}, {"TK_LT", "r54"}, {"TK_MINUS", "r54"}, {"TK_MOD", "r54"}, {"TK_MUL", "r54"}, {"TK_NEQ", "r54"}, {"TK_OR", "r54"}, {"TK_PLUS", "r54"}, {"TK_RANGE", "r54"}, {"TK_RPAREN", "r54"}, {"TK_RSQB", "r54"}, {"TK_SEMI", "r54"}, {"TK_THEN", "r54"}};
	 actTab[13] = {{"TK_COLON", "r6"}, {"TK_COMMA", "r6"}, {"TK_RPAREN", "r6"}};
	 actTab[14] = {{"TK_COLON", "s29"}, {"TK_COMMA", "s28"}};
	 actTab[15] = {{"TK_BEGIN", "r8"}, {"TK_DEF", "r8"}, {"TK_EOI", "r8"}, {"TK_VAR", "s5"}};
	 actTab[16] = {{"TK_ID", "s31"}};
	 actTab[17] = {{"TK_BEGIN", "r8"}, {"TK_VAR", "s5"}};
	 actTab[18] = {{"TK_SEMI", "s33"}};
	 actTab[19] = {{"TK_BEGIN", "s34"}};
	 actTab[20] = {{"TK_COMMA", "s28"}, {"TK_RPAREN", "s37"}};
	 actTab[21] = {{"TK_AND", "r53"}, {"TK_ASSIGN", "r53"}, {"TK_COMMA", "r53"}, {"TK_DIV", "r53"}, {"TK_DO", "r53"}, {"TK_ELSE", "r53"}, {"TK_END", "r53"}, {"TK_EQU", "r53"}, {"TK_GT", "r53"}, {"TK_LPAREN", "s38"}, {"TK_LT", "r53"}, {"TK_MINUS", "r53"}, {"TK_MOD", "r53"}, {"TK_MUL", "r53"}, {"TK_NEQ", "r53"}, {"TK_OR", "r53"}, {"TK_PLUS", "r53"}, {"TK_RANGE", "r53"}, {"TK_RPAREN", "r53"}, {"TK_RSQB", "r53"}, {"TK_SEMI", "r53"}, {"TK_THEN", "r53"}};
	 actTab[22] = {{"TK_AND", "r51"}, {"TK_ASSIGN", "r51"}, {"TK_COMMA", "r51"}, {"TK_DIV", "r51"}, {"TK_DO", "r51"}, {"TK_ELSE", "r51"}, {"TK_END", "r51"}, {"TK_EQU", "r51"}, {"TK_GT", "r51"}, {"TK_LT", "r51"}, {"TK_MINUS", "r51"}, {"TK_MOD", "r51"}, {"TK_MUL", "r51"}, {"TK_NEQ", "r51"}, {"TK_OR", "r51"}, {"TK_PLUS", "r51"}, {"TK_RANGE", "r51"}, {"TK_RPAREN", "r51"}, {"TK_RSQB", "r51"}, {"TK_SEMI", "r51"}, {"TK_THEN", "r51"}};
	 actTab[23] = {{"TK_AND", "r49"}, {"TK_ASSIGN", "r49"}, {"TK_COMMA", "r49"}, {"TK_DIV", "r49"}, {"TK_DO", "r49"}, {"TK_ELSE", "r49"}, {"TK_END", "r49"}, {"TK_EQU", "r49"}, {"TK_GT", "r49"}, {"TK_LT", "r49"}, {"TK_MINUS", "r49"}, {"TK_MOD", "r49"}, {"TK_MUL", "r49"}, {"TK_NEQ", "r49"}, {"TK_OR", "r49"}, {"TK_PLUS", "r49"}, {"TK_RANGE", "r49"}, {"TK_RPAREN", "r49"}, {"TK_RSQB", "r49"}, {"TK_SEMI", "r49"}, {"TK_THEN", "r49"}};
	 actTab[24] = {{"TK_AND", "s41"}, {"TK_ASSIGN", "r47"}, {"TK_COMMA", "r47"}, {"TK_DIV", "s40"}, {"TK_DO", "r47"}, {"TK_ELSE", "r47"}, {"TK_END", "r47"}, {"TK_EQU", "r47"}, {"TK_GT", "r47"}, {"TK_LT", "r47"}, {"TK_MINUS", "r47"}, {"TK_MOD", "s39"}, {"TK_MUL", "s42"}, {"TK_NEQ", "r47"}, {"TK_OR", "r47"}, {"TK_PLUS", "r47"}, {"TK_RANGE", "r47"}, {"TK_RPAREN", "r47"}, {"TK_RSQB", "r47"}, {"TK_SEMI", "r47"}, {"TK_THEN", "r47"}};
	 actTab[25] = {{"TK_ASSIGN", "r45"}, {"TK_COMMA", "r45"}, {"TK_DO", "r45"}, {"TK_ELSE", "r45"}, {"TK_END", "r45"}, {"TK_EQU", "s47"}, {"TK_GT", "s48"}, {"TK_LT", "s49"}, {"TK_MINUS", "s44"}, {"TK_NEQ", "s46"}, {"TK_OR", "s45"}, {"TK_PLUS", "s50"}, {"TK_RANGE", "r45"}, {"TK_RPAREN", "r45"}, {"TK_RSQB", "r45"}, {"TK_SEMI", "r45"}, {"TK_THEN", "r45"}};
	 actTab[26] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[27] = {{"TK_RPAREN", "s54"}};
	 actTab[28] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[29] = {{"TK_ARRAY", "s58"}, {"TK_INTEGER", "s57"}, {"TK_REAL", "s56"}, {"TK_STRING", "s59"}};
	 actTab[30] = {{"TK_BEGIN", "r7"}, {"TK_DEF", "r7"}, {"TK_EOI", "r7"}};
	 actTab[31] = {{"TK_LPAREN", "s62"}};
	 actTab[32] = {{"TK_BEGIN", "s34"}};
	 actTab[33] = {{"TK_BEGIN", "r16"}, {"TK_DEF", "s16"}};
	 actTab[34] = {{"TK_BEGIN", "s34"}, {"TK_END", "r24"}, {"TK_ID", "s12"}, {"TK_IF", "s73"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_PRINT", "s74"}, {"TK_RETURN", "s66"}, {"TK_STRING", "s10"}, {"TK_WHILE", "s80"}};
	 actTab[35] = {{"TK_PERIOD", "s82"}};
	 actTab[36] = {{"TK_EOI", "r2"}};
	 actTab[37] = {{"TK_SEMI", "s83"}};
	 actTab[38] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[39] = {{"TK_ID", "r67"}, {"TK_LPAREN", "r67"}, {"TK_MINUS", "r67"}, {"TK_NUM", "r67"}, {"TK_STRING", "r67"}};
	 actTab[40] = {{"TK_ID", "r66"}, {"TK_LPAREN", "r66"}, {"TK_MINUS", "r66"}, {"TK_NUM", "r66"}, {"TK_STRING", "r66"}};
	 actTab[41] = {{"TK_ID", "r68"}, {"TK_LPAREN", "r68"}, {"TK_MINUS", "r68"}, {"TK_NUM", "r68"}, {"TK_STRING", "r68"}};
	 actTab[42] = {{"TK_ID", "r65"}, {"TK_LPAREN", "r65"}, {"TK_MINUS", "r65"}, {"TK_NUM", "r65"}, {"TK_STRING", "r65"}};
	 actTab[43] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[44] = {{"TK_ID", "r63"}, {"TK_LPAREN", "r63"}, {"TK_MINUS", "r63"}, {"TK_NUM", "r63"}, {"TK_STRING", "r63"}};
	 actTab[45] = {{"TK_ID", "r64"}, {"TK_LPAREN", "r64"}, {"TK_MINUS", "r64"}, {"TK_NUM", "r64"}, {"TK_STRING", "r64"}};
	 actTab[46] = {{"TK_ID", "r61"}, {"TK_LPAREN", "r61"}, {"TK_MINUS", "r61"}, {"TK_NUM", "r61"}, {"TK_STRING", "r61"}};
	 actTab[47] = {{"TK_ID", "r60"}, {"TK_LPAREN", "r60"}, {"TK_MINUS", "r60"}, {"TK_NUM", "r60"}, {"TK_STRING", "r60"}};
	 actTab[48] = {{"TK_ID", "r59"}, {"TK_LPAREN", "r59"}, {"TK_MINUS", "r59"}, {"TK_NUM", "r59"}, {"TK_STRING", "r59"}};
	 actTab[49] = {{"TK_ID", "r58"}, {"TK_LPAREN", "r58"}, {"TK_MINUS", "r58"}, {"TK_NUM", "r58"}, {"TK_STRING", "r58"}};
	 actTab[50] = {{"TK_ID", "r62"}, {"TK_LPAREN", "r62"}, {"TK_MINUS", "r62"}, {"TK_NUM", "r62"}, {"TK_STRING", "r62"}};
	 actTab[51] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[52] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[53] = {{"TK_AND", "r50"}, {"TK_ASSIGN", "r50"}, {"TK_COMMA", "r50"}, {"TK_DIV", "r50"}, {"TK_DO", "r50"}, {"TK_ELSE", "r50"}, {"TK_END", "r50"}, {"TK_EQU", "r50"}, {"TK_GT", "r50"}, {"TK_LT", "r50"}, {"TK_MINUS", "r50"}, {"TK_MOD", "r50"}, {"TK_MUL", "r50"}, {"TK_NEQ", "r50"}, {"TK_OR", "r50"}, {"TK_PLUS", "r50"}, {"TK_RANGE", "r50"}, {"TK_RPAREN", "r50"}, {"TK_RSQB", "r50"}, {"TK_SEMI", "r50"}, {"TK_THEN", "r50"}};
	 actTab[54] = {{"TK_AND", "r57"}, {"TK_ASSIGN", "r57"}, {"TK_COLON", "r57"}, {"TK_COMMA", "r57"}, {"TK_DIV", "r57"}, {"TK_DO", "r57"}, {"TK_ELSE", "r57"}, {"TK_END", "r57"}, {"TK_EQU", "r57"}, {"TK_GT", "r57"}, {"TK_LPAREN", "r57"}, {"TK_LT", "r57"}, {"TK_MINUS", "r57"}, {"TK_MOD", "r57"}, {"TK_MUL", "r57"}, {"TK_NEQ", "r57"}, {"TK_OR", "r57"}, {"TK_PLUS", "r57"}, {"TK_RANGE", "r57"}, {"TK_RPAREN", "r57"}, {"TK_RSQB", "r57"}, {"TK_SEMI", "r57"}, {"TK_THEN", "r57"}};
	 actTab[55] = {{"TK_COLON", "r5"}, {"TK_COMMA", "r5"}, {"TK_RPAREN", "r5"}};
	 actTab[56] = {{"TK_RPAREN", "r13"}, {"TK_SEMI", "r13"}};
	 actTab[57] = {{"TK_RPAREN", "r12"}, {"TK_SEMI", "r12"}};
	 actTab[58] = {{"TK_LSQB", "s89"}};
	 actTab[59] = {{"TK_RPAREN", "r14"}, {"TK_SEMI", "r14"}};
	 actTab[60] = {{"TK_RPAREN", "r10"}, {"TK_SEMI", "r10"}};
	 actTab[61] = {{"TK_SEMI", "r9"}};
	 actTab[62] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[63] = {{"TK_COLON", "s92"}};
	 actTab[64] = {{"TK_SEMI", "r17"}};
	 actTab[65] = {{"TK_BEGIN", "r15"}};
	 actTab[66] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[67] = {{"TK_END", "s94"}};
	 actTab[68] = {{"TK_ELSE", "r27"}, {"TK_END", "r27"}, {"TK_SEMI", "r27"}};
	 actTab[69] = {{"TK_ELSE", "r34"}, {"TK_END", "r34"}, {"TK_SEMI", "r34"}};
	 actTab[70] = {{"TK_END", "r26"}, {"TK_SEMI", "r26"}};
	 actTab[71] = {{"TK_ELSE", "r28"}, {"TK_END", "r28"}, {"TK_SEMI", "r28"}};
	 actTab[72] = {{"TK_ASSIGN", "s95"}, {"TK_ELSE", "r43"}, {"TK_END", "r43"}, {"TK_SEMI", "r43"}};
	 actTab[73] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[74] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[75] = {{"TK_ELSE", "r29"}, {"TK_END", "r29"}, {"TK_SEMI", "r29"}};
	 actTab[76] = {{"TK_ELSE", "r30"}, {"TK_END", "r30"}, {"TK_SEMI", "r30"}};
	 actTab[77] = {{"TK_ELSE", "r31"}, {"TK_END", "r31"}, {"TK_SEMI", "r31"}};
	 actTab[78] = {{"TK_ELSE", "r32"}, {"TK_END", "r32"}, {"TK_SEMI", "r32"}};
	 actTab[79] = {{"TK_ELSE", "r33"}, {"TK_END", "r33"}, {"TK_SEMI", "r33"}};
	 actTab[80] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[81] = {{"TK_END", "r23"}, {"TK_SEMI", "s99"}};
	 actTab[82] = {{"TK_EOI", "r4"}};
	 actTab[83] = {{"TK_BEGIN", "r3"}, {"TK_DEF", "r3"}, {"TK_EOI", "r3"}, {"TK_VAR", "r3"}};
	 actTab[84] = {{"TK_COMMA", "r41"}, {"TK_RPAREN", "r41"}};
	 actTab[85] = {{"TK_COMMA", "s100"}, {"TK_RPAREN", "s101"}};
	 actTab[86] = {{"TK_AND", "r48"}, {"TK_ASSIGN", "r48"}, {"TK_COMMA", "r48"}, {"TK_DIV", "r48"}, {"TK_DO", "r48"}, {"TK_ELSE", "r48"}, {"TK_END", "r48"}, {"TK_EQU", "r48"}, {"TK_GT", "r48"}, {"TK_LT", "r48"}, {"TK_MINUS", "r48"}, {"TK_MOD", "r48"}, {"TK_MUL", "r48"}, {"TK_NEQ", "r48"}, {"TK_OR", "r48"}, {"TK_PLUS", "r48"}, {"TK_RANGE", "r48"}, {"TK_RPAREN", "r48"}, {"TK_RSQB", "r48"}, {"TK_SEMI", "r48"}, {"TK_THEN", "r48"}};
	 actTab[87] = {{"TK_AND", "s41"}, {"TK_ASSIGN", "r46"}, {"TK_COMMA", "r46"}, {"TK_DIV", "s40"}, {"TK_DO", "r46"}, {"TK_ELSE", "r46"}, {"TK_END", "r46"}, {"TK_EQU", "r46"}, {"TK_GT", "r46"}, {"TK_LT", "r46"}, {"TK_MINUS", "r46"}, {"TK_MOD", "s39"}, {"TK_MUL", "s42"}, {"TK_NEQ", "r46"}, {"TK_OR", "r46"}, {"TK_PLUS", "r46"}, {"TK_RANGE", "r46"}, {"TK_RPAREN", "r46"}, {"TK_RSQB", "r46"}, {"TK_SEMI", "r46"}, {"TK_THEN", "r46"}};
	 actTab[88] = {{"TK_ASSIGN", "r44"}, {"TK_COMMA", "r44"}, {"TK_DO", "r44"}, {"TK_ELSE", "r44"}, {"TK_END", "r44"}, {"TK_MINUS", "s44"}, {"TK_OR", "s45"}, {"TK_PLUS", "s50"}, {"TK_RANGE", "r44"}, {"TK_RPAREN", "r44"}, {"TK_RSQB", "r44"}, {"TK_SEMI", "r44"}, {"TK_THEN", "r44"}};
	 actTab[89] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[90] = {{"TK_COLON", "s103"}, {"TK_COMMA", "s28"}};
	 actTab[91] = {{"TK_RPAREN", "s105"}, {"TK_SEMI", "s104"}};
	 actTab[92] = {{"TK_ARRAY", "s58"}, {"TK_INTEGER", "s57"}, {"TK_REAL", "s56"}, {"TK_STRING", "s59"}};
	 actTab[93] = {{"TK_ELSE", "r38"}, {"TK_END", "r38"}, {"TK_SEMI", "r38"}};
	 actTab[94] = {{"TK_ELSE", "r22"}, {"TK_END", "r22"}, {"TK_PERIOD", "r22"}, {"TK_SEMI", "r22"}};
	 actTab[95] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[96] = {{"TK_THEN", "s108"}};
	 actTab[97] = {{"TK_ELSE", "r37"}, {"TK_END", "r37"}, {"TK_SEMI", "r37"}};
	 actTab[98] = {{"TK_DO", "s109"}};
	 actTab[99] = {{"TK_BEGIN", "s34"}, {"TK_ID", "s12"}, {"TK_IF", "s73"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_PRINT", "s74"}, {"TK_RETURN", "s66"}, {"TK_STRING", "s10"}, {"TK_WHILE", "s80"}};
	 actTab[100] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[101] = {{"TK_AND", "r52"}, {"TK_ASSIGN", "r52"}, {"TK_COMMA", "r52"}, {"TK_DIV", "r52"}, {"TK_DO", "r52"}, {"TK_ELSE", "r52"}, {"TK_END", "r52"}, {"TK_EQU", "r52"}, {"TK_GT", "r52"}, {"TK_LT", "r52"}, {"TK_MINUS", "r52"}, {"TK_MOD", "r52"}, {"TK_MUL", "r52"}, {"TK_NEQ", "r52"}, {"TK_OR", "r52"}, {"TK_PLUS", "r52"}, {"TK_RANGE", "r52"}, {"TK_RPAREN", "r52"}, {"TK_RSQB", "r52"}, {"TK_SEMI", "r52"}, {"TK_THEN", "r52"}};
	 actTab[102] = {{"TK_RANGE", "s112"}};
	 actTab[103] = {{"TK_ARRAY", "s58"}, {"TK_INTEGER", "s57"}, {"TK_REAL", "s56"}, {"TK_STRING", "s59"}};
	 actTab[104] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[105] = {{"TK_COLON", "r19"}};
	 actTab[106] = {{"TK_SEMI", "s115"}};
	 actTab[107] = {{"TK_ELSE", "r42"}, {"TK_END", "r42"}, {"TK_SEMI", "r42"}};
	 actTab[108] = {{"TK_BEGIN", "s34"}, {"TK_ID", "s12"}, {"TK_IF", "s73"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_PRINT", "s74"}, {"TK_RETURN", "s66"}, {"TK_STRING", "s10"}, {"TK_WHILE", "s80"}};
	 actTab[109] = {{"TK_BEGIN", "s34"}, {"TK_ID", "s12"}, {"TK_IF", "s73"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_PRINT", "s74"}, {"TK_RETURN", "s66"}, {"TK_STRING", "s10"}, {"TK_WHILE", "s80"}};
	 actTab[110] = {{"TK_END", "r25"}, {"TK_SEMI", "r25"}};
	 actTab[111] = {{"TK_COMMA", "r40"}, {"TK_RPAREN", "r40"}};
	 actTab[112] = {{"TK_ID", "s12"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_STRING", "s10"}};
	 actTab[113] = {{"TK_RPAREN", "r21"}, {"TK_SEMI", "r21"}};
	 actTab[114] = {{"TK_COLON", "s119"}, {"TK_COMMA", "s28"}};
	 actTab[115] = {{"TK_BEGIN", "r18"}, {"TK_SEMI", "r18"}, {"TK_VAR", "r18"}};
	 actTab[116] = {{"TK_ELSE", "s120"}};
	 actTab[117] = {{"TK_ELSE", "r36"}, {"TK_END", "r36"}, {"TK_SEMI", "r36"}};
	 actTab[118] = {{"TK_RSQB", "s121"}};
	 actTab[119] = {{"TK_ARRAY", "s58"}, {"TK_INTEGER", "s57"}, {"TK_REAL", "s56"}, {"TK_STRING", "s59"}};
	 actTab[120] = {{"TK_BEGIN", "s34"}, {"TK_ID", "s12"}, {"TK_IF", "s73"}, {"TK_LPAREN", "s9"}, {"TK_MINUS", "s26"}, {"TK_NUM", "s11"}, {"TK_PRINT", "s74"}, {"TK_RETURN", "s66"}, {"TK_STRING", "s10"}, {"TK_WHILE", "s80"}};
	 actTab[121] = {{"TK_OF", "s124"}};
	 actTab[122] = {{"TK_RPAREN", "r20"}, {"TK_SEMI", "r20"}};
	 actTab[123] = {{"TK_ELSE", "r35"}, {"TK_END", "r35"}, {"TK_SEMI", "r35"}};
	 actTab[124] = {{"TK_INTEGER", "s57"}, {"TK_REAL", "s56"}, {"TK_STRING", "s59"}};
	 actTab[125] = {{"TK_RPAREN", "r11"}, {"TK_SEMI", "r11"}};
}
map<string, function<AST*(vector<AST*>&)>> actions;
void initActions() {
	 actions.insert({"binop",binop});
	 actions.insert({"mkArray",mkArray});
	 actions.insert({"mkBlock",mkBlock});
	 actions.insert({"mkCall",mkCall});
	 actions.insert({"mkFunc",mkFunc});
	 actions.insert({"mkFuncHeader",mkFuncHeader});
	 actions.insert({"mkId",mkId});
	 actions.insert({"mkIf",mkIf});
	 actions.insert({"mkLet",mkLet});
	 actions.insert({"mkList",mkList});
	 actions.insert({"mkNum",mkNum});
	 actions.insert({"mkPrint",mkPrint});
	 actions.insert({"mkProgram",mkProgram});
	 actions.insert({"mkProgramHeader",mkProgramHeader});
	 actions.insert({"mkRet",mkRet});
	 actions.insert({"mkString",mkString});
	 actions.insert({"mkWhile",mkWhile});
	 actions.insert({"pass",pass});
	 actions.insert({"through",through});
	 actions.insert({"unary",unary});
}
